### ISSUE TITLE
Use default icon when no icon link in search engine config

### ISSUE THREAD

**Issue by marcelpaulo** [CanisLupus/swift-selection-search#103]
Could SSS use the default icon when no icon link is filled in a search engine config ? For most search engines, the default site favicon can be used, so there should be no need to configure it unless one wants something different. I'm migrating from Google Chrome where I used extension [Selections Search](https://chrome.google.com/webstore/detail/selection-search/gipnlpdeieaidmmeaichnddnmjmcakoe) which does this, and it's very very practical. The default SSS search engines, for instance, could all use the default favicons.

**Comment by CanisLupus** [comment]
Hey Paulo, maybe I can do something about this. I'll look into it when I can. There are a lot of pending things and time is not currently on my side. ;) Thanks for the suggestion!

**Comment by CanisLupus** [comment]
Hello again, Paulo, I had some time to look into this today and went ahead and implemented it. :)

Version 3.24.0 should soon be in the addon market and has favicons being automatically acquired for new search engines, in this case using https://api.faviconkit.com.

I'll keep the issue open until feedback comes in or some time passes, in case something is wrong with it.

Cheers!
Daniel

**Comment by marcelpaulo** [comment]
Hey, Daniel, good to hear that ! I had given up on Firefox, and this kind of stimulated me to try it again.

I followed the instructions from _README.md_, cloned the git repo, loaded the extension with `Load Temporary Add-on` on _about:debugging#addons_ (by the way, there's an **s** missing on _README.md_), and then:

1. `Reset search engines`
1. Removed the icon from `Google`:
![image](https://user-images.githubusercontent.com/10074769/43371337-e975ef64-9365-11e8-9160-ebd3aa65fd74.png)
1. Selected a word and fired the extension:
![image](https://user-images.githubusercontent.com/10074769/43371343-0ac819d0-9366-11e8-8cd3-4966af1190a4.png)
    But the favicon wasn't loaded :-(
1. Added a new search engine, `Rutracker`, and the favicon was acquired automatically:
![image](https://user-images.githubusercontent.com/10074769/43371393-2379dab2-9367-11e8-9e36-0290e8d3b996.png)
1. Looking at the favicon search URL on `Rutracker`, I filled in `Google`'s with _https://api.faviconkit.com/google.com_, and then the favicon was acquired:
![image](https://user-images.githubusercontent.com/10074769/43371401-839d16b6-9367-11e8-8882-5a42e2f505ac.png)

**Comment by CanisLupus** [comment]
Thanks for trying it out. :) I appreciate it!

Nice catch with the README typo. Fixed!

This is actually the intended behaviour, but I may change it. I'll explain:

SSS only sets the favicon URL automatically under these 3 circumstances:

1. A new engine is added.
2. You change the search URL and the icon URL is already a faviconkit.com link for the previous search URL. (so it essentially updates the domain for the icon)
3. You change the search URL and the icon URL is empty.

So in your steps it was left empty but the search URL was not changed. In this case, I assume it is the user's intention to have an empty link (for some reason) and that they will write something afterward. Maybe I shouldn't... I'll think about it. Maybe some people will actually try to remove their icons to get the favicon.

If you try to change the search URL it will update to a favicon since it's empty, though (due to point 3). :)

So the summary is that it is doing what I expect, but probably not what the user expects. :)

Thanks a lot for the feedback! This helps.

Cheers!
Daniel

**Comment by marcelpaulo** [comment]
> Thanks for trying it out. :) I appreciate it!

It's the very least all of us users of your fantastic extension could and should do !

> This is actually the intended behaviour, but I may change it
> A new engine is added.
> You change the search URL and the icon URL is already a faviconkit.com link for the previous search URL. (so it essentially updates the domain for the icon)
> You change the search URL and the icon URL is empty.

It makes perfect sense to me.

> So in your steps it was left empty but the search URL was not changed

In hindsight, I see that my first test case was rather artificial. It's not something I would have done if I were trying to configure the search engines for real.

> Maybe some people will actually try to remove their icons to get the favicon

At first sight, this seems unlikely, but … perhaps as a safety net it might be useful never to allow an empty link. Or, as an alternative, to have a button to reset an individual search engine. After I removed the link, I wondered how I could recover it, so I just reset **all** search engines. It might have been more useful if I could have reset just that engine that I messed up.

Once again, congrats on your extension: it's really useful !

**Comment by CanisLupus** [comment]
> It's the very least all of us users of your fantastic extension could and should do !

Heheh thanks! ;)

> At first sight, this seems unlikely, but … perhaps as a safety net it might be useful never to allow an empty link. Or, as an alternative, to have a button to reset an individual search engine. After I removed the link, I wondered how I could recover it, so I just reset all search engines. It might have been more useful if I could have reset just that engine that I messed up.

I agree. Probably any of the two would be good. A reset button would be nice, though I don't think I want to commit to that just yet due to the extra cluttering of the engines table. But you raise a valid point about resetting a single engine.

Perhaps not letting it be empty is what I'll do for now. i.e. Force the favicon URL if the input field is empty when it loses focus. I hope nobody really really wants an empty icon...

> Once again, congrats on your extension: it's really useful !

Much appreciated! :D

**Comment by marcelpaulo** [comment]
> A reset button would be nice, though I don't think I want to commit to that just yet due to the extra cluttering of the engines table

Best to keep things as lean as possible, you're right.

> Force the favicon URL if the input field is empty when it loses focus. I hope nobody really really wants an empty icon...

In practice, that will cover all cases. I doubt a single soul will want an empty icon.

**Comment by CanisLupus** [comment]
Yes, I hope that is the case. I'll try to implement that for the next update when I can. Adding that should be quick.

**Comment by CanisLupus** [comment]
I submitted v3.24.1 with a few fixes. One of them is auto-setting the favicon if it is left empty. It should deal with this. :)

Cheers!

**Comment by marcelpaulo** [comment]
Indeed ! Did the same I did before, wiped the favicon from `Google`, and the extension filled it back:
![image](https://user-images.githubusercontent.com/10074769/43688479-fcdc2d52-98bf-11e8-9ea7-3bba53a2d77f.png)

Wow, thanks for that ! I guess this issue is completely done with now.

**Comment by CanisLupus** [comment]
Awesome! You're welcome :)
