### ISSUE TITLE
Popup not shown on this situation.

### ISSUE THREAD

**Issue by thelastfantasy** [CanisLupus/swift-selection-search#105]
[https://gfycat.com/FlimsyNegligibleGenet](https://gfycat.com/FlimsyNegligibleGenet)

In this video, I started to select text on the 3rd table cell and ended selection on the image of the 2nd table cell, the popup did not appare.

The source page: http://blog.livedoor.jp/geek/archives/51568400.html

**Comment by CanisLupus** [comment]
Interesting find. It may have to do with the "mouse up" event being caught in some strange way. Thanks for the report!

**Comment by CanisLupus** [comment]
Hey there! SSS version 3.26.2 and more recent should have this problem fixed. :)

For future reference, it was not related to mouse up events, but simply the fact that the JavaScript selection object seems to sometimes not report the correct text content of the selection even though the selection ranges themselves have that content. Fixed by checking the ranges if the selection is reported empty.

Unfortunately, it still happens for the context menu (i.e. text selected in this situation will now make the popup appear but the context menu still won't detect a selection, so the SSS submenu won't appear). That is a problem on Firefox's end, so it might be a bug. I'll think about reporting it when I have time.

Cheers!

**Comment by CanisLupus** [comment]
Submitted a bug report for Mozilla here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1484953
