### ISSUE TITLE
Use new search API / automatically import engines from Firefox

### ISSUE THREAD

**Issue by Riajyuu** [CanisLupus/swift-selection-search#106]
Check this out
https://bugzilla.mozilla.org/show_bug.cgi?id=1352598

**Comment by CanisLupus** [comment]
Hello! I've been following that thread for a while, from time to time. It seems it's not complete yet and will likely only come in a later Firefox version even then. When we get there... :)

Cheers,
Daniel

**Comment by Riajyuu** [comment]
I think it is now the time to look into it as it is launched in 63

**Comment by CanisLupus** [comment]
I will look into this when possible. :) Thanks for the heads up!

**Comment by Riajyuu** [comment]
Quick catching up:
docs is complete right now
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/search

**Comment by FatOrangutan** [comment]
Hi, the new API is available [now on the Stable channel](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/63#Search)

**Comment by CanisLupus** [comment]
Hey everyone, I finally had a look at the new API.

Each search engine in the list of browser engines is essentially a name and an icon URL, so there's no access to the actual URL they use for search. This is fine since no one needs to know it as long as the `search` method works.

But... the API can only distinguish between opening the search in a new tab (at the end of all tabs) OR replacing the content of an existing tab. This means that the only SSS opening behaviours that can be used are `Open in this tab` and `Open in new tab`. No other option can be used for these "native" search engines (i.e. no background tabs, no windows, no "next to current tab").

I guess I can live with this, but I'll have to make it very clear for the users if they choose options that work fine with some icons but not with others.

I'll keep working on this since it's my top priority right now, but it may take a while!

Cheers!
Daniel

**Comment by CanisLupus** [comment]
Hey everyone, I have news about this issue. After this became my priority almost 2 years ago (!!), I ended up discarding it "for the time being" since importing engines via search.json.mozlz4 was more powerful, albeit more cumbersome for the user. Sorry.

However, yesterday and today I got reports that importing engines through search.json.mozlz4 was not working anymore, since most engines from that file don't even have search URL information anymore. So I figured I'd implement this now to at least have a way for users to import browser engines.

SSS version 3.45.0 is awaiting review and uses the WebExtensions search API. The imported engines are significantly more limited, since they don't have a customizable URL and only support 2 of the opening behaviours, but it's what we have now!

Cheers,
Daniel

**Comment by CanisLupus** [comment]
Just letting you know that SSS 3.47.0 got an internal reimplementation of click behaviours as part of the "group engines" feature (thanks to @igorofc) that now also allows browser-imported engines to use any click behaviour (whereas previously only 2 were usable for them).

Cheers!
