### ISSUE TITLE
two small suggestions

### ISSUE THREAD

**Issue by persianphilosopher** [CanisLupus/swift-selection-search#11]
Thank you so much for all your work. I can't use a browser without a popup search and yours is truly wonderful and I have switched to it permanently. 

1. Unless I missed it, I would love one more tweak option for the tab to open next to the active one. With many open tabs for research, that would help a lot. 

2. Again, I hope I did not miss it, but if there a way to back up and restore settings? It does not matter  if it's in the folders somewhere and not a GUI option. I would manually then "sync" it between my different computers.

Again, thank you.

**Comment by CanisLupus** [comment]
Hi there!

You're welcome! I really appreciate your kind words. :)

1. That has actually been in my TO-DO list for a long time, but I haven't worked on SSS for a while. I've simply used Firefox's default behavior until now. I just searched around a bit and found [this](http://stackoverflow.com/questions/25861762/open-a-tab-next-to-the-active-tab-in-firefox-add-on-sdk), which will certainly help me.
When I add that I'll be sure to let you know!

2. Unfortunately, there isn't an "SSS-way" of doing this. You didn't miss it! Yes, you can save the settings from files manually, but you're probably not going to like it. :) Let's see...

SSS saves its settings using Firefox's "simple prefs" and "simple storage" modules. In SSS, "simple storage" contains the list of engines you have enabled for the popup. All other settings are in "simple prefs". You can see them if you write "about:config" as your URL and then search for "extensions.jid1-KdTtiCj6wxVAFA@jetpack" (it's the ID for SSS). All about:config settings are saved here:

`C:\Users\<username>\AppData\Roaming\Mozilla\Firefox\Profiles\<something>.default\prefs.js`

You _could_ backup this whole file, but I advise against that because it contains settings from other addons and Firefox itself. If you wish, you could probably copy the lines that have SSS's ID. Write them to the prefs.js file of another machine (with Firefox closed) to apply the settings. You decide if this is worth the trouble. :)

As for "simple storage", it's easier, as Firefox saves it under:

`C:\Users\<username>\AppData\Roaming\Mozilla\Firefox\Profiles\<something>.default\jetpack\jid1-KdTtiCj6wxVAFA@jetpack\simple-storage\store.json`

Which is only related to SSS and hence much nicer to backup.

If I knew a good addon for backing up some about:config settings, I would give you a link, but I don't know any. There might exist something, though.

I hope I have helped....somewhat!

- Daniel

**Comment by CanisLupus** [comment]
PS: I believe I could make SSS support Firefox Sync and sync settings without user intervention, but would have to look into that. :)

**Comment by persianphilosopher** [comment]
Thank you so much for your detailed response. I don't mind digging in the files a bit more and finding the preferences. I found that file and tomorrow will try to manually "sync" and see. I have about twenty search icons that pop up and could not do without them. So it's nice to have them in the same order...

But all that I suggested is just luxurious and not in the least pressing. So please don't turn your attention back to this project for this! If and when, I'd be even more grateful. Thanks again.

**Comment by Gitoffthelawn** [comment]
@CanisLupus Out of curiosity, why did you choose to use *simple prefs* and *simple storage* instead of only *simple prefs*?  The contents of *simple storage* are minimal, but require an additional open file, file handle, and directory traversal.  On systems that scan every file for malware, it also gets scanned every time Firefox is opened and closed.

No big deal, but was wondering the rationale, and if it still makes sense.

**Comment by CanisLupus** [comment]
@persianphilosopher You're welcome! :) And don't worry about it. I intend to complete a few TO-DOs on SSS _soon_. There have just been other things for me to do these previous months.

Two points to note:

1. If engine order is important to you, SSS displays engines in the order defined in Firefox itself, so you can go to Firefox's Option, Search, and drag the engines around. The engines (and respective order) could be synced by Firefox automatically, but I found [this](https://support.mozilla.org/en-US/questions/1089479) and [this](https://bugzilla.mozilla.org/show_bug.cgi?id=444284), which say otherwise. The first link says that you should backup the "searchplugins" folder in:

`C:\Users\<username>\AppData\Roaming\Mozilla\Firefox\Profiles\<something>.default\searchplugins`

The more I find out about this, the less I like it. :( Could you tell me if you usually backup those 20+ engines already?

2. If the general SSS settings are not important and only which engines are active, you can simply backup the second file I mentioned.


@Gitoffthelawn Fair point! The reasoning was that _simple prefs_ is quite limited in the data types that you can save (I assume because Firefox must know how to present them in the preferences page of the addon). I wanted to save an array or an object with the IDs of the active engines, and there was no type for that, so I resorted to _simple storage_ instead.

On the other hand, if every preference had gone to _simple storage_ I wouldn't have the automatic addon page with all the settings. I intended to keep the addon simple and make use of the provided API where possible, which in some cases proved not to be the best approach. In fact, I think that SSS has way more settings than the addon page handles nicely, and that can only be solved by creating custom menus.

That said, at the time I didn't consider serializing the array/object to a JSON string and storing it in _simple prefs_ as a hidden string. That would probably be more sensible in terms of keeping it all to a single place. :)

**Comment by Gitoffthelawn** [comment]
Good conversation.  We've branched into two topics, and I think we can handle it! :smile: 

1. I backup search engines by copying the folder you mentioned above.
2. I like the idea of just putting everything in *simple prefs*.  There seems to be a trend in other direction, but often the road less traveled is a better choice.  My biggest concern about only using *simple prefs* is that I'm not sure if it introduces a privacy issue.  Can other extensions read all *simple prefs* or is there a scope limiter to only allow them to read their own prefs and Firefox's global prefs?

**Comment by CanisLupus** [comment]
@Gitoffthelawn

1. Alright, so that became the common way to backup engines because Firefox does not sync them. Fair enough. :)

2. An addon can't _easily_ read prefs from other addons. When you access the simple-prefs module, you can only access your own addon's prefs. For example:
```
simplePrefs = require('sdk/simple-prefs')
simplePrefs.prefs['popupPanelOpenBehavior'] // get value for setting "popupPanelOpenBehavior"
```
As you can see, I don't need to specify my addon's ID. It automatically assumes I only want prefs from my addon (which makes sense). It's a scope in and of itself. :)

However, an addon can use the file IO module, with which they might be able to access the prefs.js file on disk. Mozilla's review should in theory look into harmful usage of files by an addon. I think it's the same issue with _simple storage_. You can always access the files themselves. In fact, I have an addon installed that can look into the simple storage of any addon:
https://addons.mozilla.org/en-US/firefox/addon/simple-storage-editor-for-a/

I believe that unless well encrypted, no information is completely safe!

**Comment by Gitoffthelawn** [comment]
Great conversation. :)

Regarding prefs, it sounds like moving everything to simple storage is likely more efficient.  It also puts everything in one place, making backups easier than having data in two places.

Out of curiosity, how do extensions access Firefox (not extension) prefs, given the scope being restricted to the extension? (btw, thank you for your generous explanation above!)

**Comment by CanisLupus** [comment]
@Gitoffthelawn You're welcome!

Do you mean _simple prefs_? Because moving eveything to _simple storage_ is not advisable for me, unless I'd decide to create custom menus for everything settings-related. :)

Good question. While searching for the answer to your question (I didn't know either) I found that there is another, lower level module [preferences/service](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/preferences_service) (does this ever end? :p) that actually seems to let you get any pref, as long as you know its full ID.

So even though the simple-prefs module doesn't let you access other prefs, this one does. I guess that throws my "An addon can't _easily_ read prefs from other addons." out the window (I was just thinking about simple-prefs). ;)

**Comment by Gitoffthelawn** [comment]
LOL... oops... yes, I meant *simple prefs*.

Thanks for answering my questions regarding prefs.

In light of the answers you provided, I'm a little torn as to what is the best decision.

It seems like putting everything in *simple prefs* makes things easier to implement, more efficient, and use fewer resources.  It also makes data easier to backup over the current situation of having data stored in two places (and the other alternative, putting everything into *simple storage*, would require creating custom menus for everything).

But, on the other hand, putting everything into *simple prefs* makes it a little easier for another extension to read the data.

Overall, I think I lean towards putting everything in *simple prefs* because if a user already has a malware extension installed, nothing is private/secure.

What do you think?

**Comment by CanisLupus** [comment]
@Gitoffthelawn I agree! :) Though I would have to keep compatibility with old versions of SSS (so users don't lose their selection of engines), so I will at least have to try to access simple storage to see if there's anything there. When I can I will look into this and try to complete a few TO-DOs, including the copy icon you suggested a long time ago. :)

**Comment by Gitoffthelawn** [comment]
Sounds great!  (Sorry for the delay!)

**Comment by CanisLupus** [comment]
Just an update on this:

I've updated SSS and decided to NOT remove simple storage access for now. I've actually changed the code to port everything to simple prefs and use it there, and it seems to work, but then I saved those changes elsewhere and reverted them.

I found out that Firefox doesn't keep the simple storage file open. It actually only seems to write to it when I close the application (not sure if it saves when a lot of time passes, too, but it does for sure on exiting). Furthermore, the simple fact that I must use the storage module to check if the user has data there will cause Firefox to create an empty storage file, so this wouldn't be a great advantage anyway.

The advantage would be related to backing up settings (one place instead of two), but the current state of backups for SSS is hardly any good even if everything is in simple prefs, so I decided to not risk creating a bug when porting and leave this as-is for now. I'm also thinking that something might show up later where I really have to save data in simple storage, and in that case all this would be wasted. :) It's the path of least resistance and it's also safer, I think.

Now... I really really really have to solve issue #7 before anything else, as soon as I'm able to work on SSS again, as it seems that Mozilla won't do anything about the bugs that the text selection module faces in the multiprocess environment.

**Comment by CanisLupus** [comment]
@persianphilosopher I also moved the "opening tab next to active tab" idea to a new issue (#12). Wasn't able to work on that yet. :)

**Comment by persianphilosopher** [comment]
thank you for all your work!

**Comment by CanisLupus** [comment]
@persianphilosopher You're welcome!

I've updated SSS to 2.24.0 and added multiprocess support as well as the feature to open tabs next to the current tab (among a few other things). It disregards Firefox's behavior but I honestly prefer it too!

**Comment by persianphilosopher** [comment]
You are the best!
