### ISSUE TITLE
Search Terms in added engines

### ISSUE THREAD

**Issue by LeeHSkinner** [CanisLupus/swift-selection-search#111]
I've added 6 new search engines (Dictionary.com, Thesaurus,com, RottenTomatoes.com, Amazon.com, Blu-ray.com and Anagram Solver (wordsmith.org/anagram).  For each of these, I can't find the proper string to put the highlighted text into the search field of the engine since the URL doesn't change when I type in a search term.  I work around this by first putting the search string in the clipboard, then reselecting it to go to the engine, and pasting it into the search box.  Any help appreciated.

Lee Skinner

**Comment by LeeHSkinner** [comment]
I've gotten Dictionary.com, Thesaurus,com, and RottenTomatoes.com to pass on the highlighted string, but not Amazon.com, Blu-ray.com and Anagram Solver (wordsmith.org/anagram).

Lee Skinner

**Comment by CanisLupus** [comment]
Hi Lee, sorry for the delay, I didn't come here yesterday.

You seem to have already found the links for the sites in the original question. As far as I could see, all of them change the URL when searching. I got this back by searching for "great":

https://www.dictionary.com/browse/great?s=t
https://www.thesaurus.com/browse/great?s=t
https://www.rottentomatoes.com/search/?search=great
https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias%3Daps&field-keywords=great
http://www.blu-ray.com/search/?quicksearch=1&quicksearch_country=US&quicksearch_keyword=great&section=bluraymovies
https://new.wordsmith.org/anagram/anagram.cgi?anagram=great&t=500&a=n

And from these I replaced "great" with "{searchTerms}" for SSS:

https://www.dictionary.com/browse/{searchTerms}?s=t
https://www.thesaurus.com/browse/{searchTerms}?s=t
https://www.rottentomatoes.com/search/?search={searchTerms}
https://www.amazon.com/s?field-keywords={searchTerms}
(I simplified this one just because I could :p)
http://www.blu-ray.com/search/?quicksearch=1&quicksearch_country=US&quicksearch_keyword={searchTerms}&section=bluraymovies
(can probably be simplified)
https://new.wordsmith.org/anagram/anagram.cgi?anagram={searchTerms}&t=500&a=n

But you probably got this already.

As for the final link you posted, it doesn't seem to be working for me:

![image](https://user-images.githubusercontent.com/532708/43684502-4c4a25e6-9899-11e8-9c9e-cad092dcd843.png)

Is it working for you right now?

All the best,
Daniel

**Comment by LeeHSkinner** [comment]
Daniel,

Thanks for your help and comments.
>> As for the final link you posted, it doesn't seem to be working for me. <<
Zap2it.com may not be visible outside the USA.  Are you outside the USA?  I have a friend in France who can't access it either, even when I can.  But at least I can work around it by saving it to the clipboard.  But then, I have to reselect the search string before I go there even though its already highlighted.  Any way to get around reselecting the already highlighted string to show the icons again?

Regards,
Lee

**Comment by LeeHSkinner** [comment]
Thanks, Daniel!

Lee
