### ISSUE TITLE
Addon does not sync

### ISSUE THREAD

**Issue by frm1001xplrr** [CanisLupus/swift-selection-search#113]
SSS addon does not sync across to my other computers, though my other addons do. 

I have tried:
- Turning off/on sync for addons. 
- Remove SSS on both boxes, reinstalled SSS on one and synced, and the reverse. 
- "Refreshed" Firefox on both boxes, manually reinstalled all addons on one, synced to the other.
- Manually removed profile folders on both boxes, reinstalled all addons on one, synced. 

In all cases SSS does not sync to the other box. 
In all cases where I reinstalled one box, SSS does not come back on that same box. 

In the end I was so bugged out that i actually deleted my Mozilla sync profile. Manually reinstalled everything and synced. No luck. 

Does SSS simply not sync?
Any ideas what might be going on here?

FF v61.0.2 (64bit) MacOS 10.13.6 High Sierrra 
FF v61.0.2 (64bit) Windows 7 Ultimate SP1

**Comment by CanisLupus** [comment]
Hi there!

Sorry you went through so much trouble for this. Unfortunately, the reason is simple: SSS indeed does not use Sync (yet). :(

I _wanted_ to use Sync and have options to sync on demand, constantly, or not at all. I have most of the code implemented to use Sync since a long time ago and it seemed to be working.

...However, there is a bug in Firefox - which I reported [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1423744) - that causes it to not sync the addon at all if the storage limit for it was ever reached (and it's pretty small). Even if the addon requests clearing all its data, it still won't sync. I ran into this problem into my own Sync account and could never Sync SSS again even for my own tests. I reported the problem about 9 months ago but I don't think there's anyone working on it yet.

In general, SSS does not use a lot of space, but the icons for the engines can be "data" urls, which contain the contents of all the pixels of an image. In fact, engines imported from the browser (from the "search.json.mozlz4" file) are data URLs and a user could very easily run into this problem and Sync would silently fail without him/her knowing. There was not even an error I could use to detect the failure and show to the user, as far as I could understand. And even so the user wouldn't be able to Sync SSS again, supposedly.

So that's why I decided to postpone the feature. I may try again soon to see what's the current state. I'll leave this issue open as a reminder!

Cheers!
Daniel

**Comment by frm1001xplrr** [comment]
Hi CL, 

Well, that explains it :)

It sounds like the hold up is due to wanting to sync all the settings and data? 

Since SSS has an excellent import/export feature, and bug#1423744 probably won't be fixed in the near future, would you consider waiting with syncing data and just have the addon sync?
Or maybe discard the "data urls" and leave it up to users to import/export, if they have issues with missing icons?
(perhaps i'm misunderstanding, and the actual addon is supposed to sync, but not data, yet?)

Anyway, thanks very much for your work and effort!! SSS is by far my most used addon <3

Cheers :)
F1X

**Comment by CanisLupus** [comment]
Hi F1X,

To make it clear, Firefox should sync add-ons automatically only in the sense that it will automatically install the same add-ons that you have installed on another machine. It should do so even for SSS. Is this not the case? I may not have understood the original issue.

However, due to SSS not implementing Sync features, all the settings you change on the SSS options page, as well as any engines you add (internally these are all "settings", actually) won't be sent to Sync's online storage and so will not sync to another machine.

I mentioned SSS having code for doing that (for "all the settings and data" like you mentioned), and it does, but that code is _disabled_. Sorry, this was not clear at all in my reply! :)

Not syncing data URLs (but only simple link URLs) seems reasonable, especially now that SSS can automatically acquire icon URLs based on the website of the Search URL. Probably no one will reach the Sync limit if there are no data URLs being uploaded. I'll think about it as a compromise since the bug probably won't get fixed anytime soon. :)

Thank you for using SSS! I'm happy to know hehe :) <3

Daniel

**Comment by frm1001xplrr** [comment]
Thanks for your quick replies :)

> Firefox should sync add-ons automatically only in the sense that it will automatically install the same add-ons that you have installed on another machine. It should do so even for SSS. 

I thought so! This is not the case here though :(
In fact, i was so sure that addon sync was automatic that i went through all the work described first, ending with deleting/recreating a sync profile, to make it work...

I have only experienced this with one other addon before, ReloadMatic.
When i saw that both SSS and RM consistently did not sync to the other box, i thought that maybe addons need to actually code for syncing or set a flag or something. That seems to not be the case.  

Hmmm.. that sucks though, since there's no clear path to fixing this. 

Any clues as to how i could debug this? I haven't looked into addon dev. 

Cheers
F1X

**Comment by CanisLupus** [comment]
You are welcome. :) I see now. I thought the issue was with SSS not syncing settings, not itself. I tried some things and you are right in regards to not all extensions being synced. SSS seems to be synced, though, but not always. I don't see useful ways to debug this right now (you can check the about:sync-log URL, but it probably won't help a lot), but I can tell you what I tried.

I was using two Firefox installs on the same computer for simplicity, since I use the default Firefox and Firefox Developer Edition, which are separate installs and use different Firefox user profiles (so you could even use different add-ons on each).

Let's call the default Firefox the "main" install (it's the one I normally use). Trying to Sync inside Dev Edition, it synced 5 of my 7 add-ons. SSS was one of the 5.

Then I did a long-pending complete removal of all versions of Firefox and its user profiles from my system (I had several versions for testing) and reinstalled only the 2 mentioned versions again.

After logging in to Sync in the main install, it synced 3 of the 7 addons, SSS not included. I manually added 2 of the missing add-ons from the add-on market, so got 5 out of the 7. I synced again, not knowing if this would override what was in Sync or not.

Apparently, it still remembered all 7 add-ons, because syncing on Dev Edition (from scratch) made it get 6 of the 7, including SSS and one other that wasn't even currently in the main install.

Then I tried installing a completely new extension (one I had never installed) in the main install, syncing, and then syncing Dev Edition. It did get the newly installed extension.

So, at best, Sync is not being consistent on my end/account. Do you get similar results or is it always able to get the same add-ons?

Cheers!
Daniel

**Comment by frm1001xplrr** [comment]
Something's going on here...

On Machine#1 (FF v61.0.2 64bit, MacOS 10.13.6 High Sierrra)
1) Setup new Firefox test profile
2) Create brand new Sync account
3) Install SSS
4) Sync

On Machine#2 (FF v61.0.2 64bit, Windows 7 Ultimate SP1)
5) Setup new Firefox test profile
6) Sign in to new Sync account and Sync

Expected result: SSS automatically installs on Machine#2
Actual result: SSS does NOT install

7) Delete test profile on Machine#1
8) Create new test2 profile
9) Sign in to same Sync account and Sync

Expected result: SSS automatically installs on Machine#1 (where it was installed minutes ago)
Actual result: SSS does NOT install

Conclusion: SSS does not sync ***at all***.

I did steps 1-9 again, but this time i installed other addons before *and* after installing SSS, and synced *every* time on both machines. *Every* time the installed addon syncs across to the other machine, but SSS does *not*.

Did this again with ReloadMatic. Exactly same result. SSS and ReloadMatic do not sync across machines....

Reproduce? 

F1X

**Comment by frm1001xplrr** [comment]
Damn, 36 seconds between posts, hahaha

**Comment by CanisLupus** [comment]
Your findings are very interesting and at least consistent! It is possible that an addon needs to implement Sync to be sync-installed on another machine... I'm honestly not sure about any of this. But I have at least one add-on that installed on sync but lost all settings, so I'm not sure if that is the case.

If it is, however, my Sync tests from 9 months ago with SSS (in which I uploaded SSS settings from SSS to Sync) might have caused it to be considered for "sync-installing" on my account and made me thing this is the default behaviour. This is all very strange indeed...

**Comment by frm1001xplrr** [comment]
I didn't find a way to delete all data in the sync profile, so i created a new one. 

You don't have another emailadress?

**Comment by CanisLupus** [comment]
I can use another email for testing, I'd just like to keep using the current email for personally using Sync. When I have more time I'll try creating another account and see if I can reuse the address after deleting it.

**Comment by frm1001xplrr** [comment]
>When I have more time I'll try creating another account and see if I can reuse the address after deleting it.

I deleted my only sync account, then created a new account with the same email address immediately after...

**Comment by CanisLupus** [comment]
I see. Good to know, thanks!

**Comment by CanisLupus** [comment]
Hey! I've submitted a new version (3.27.0) with Sync support, if you want to try it out and see if anything changed. It's not automatic sync (at least there's no option for that yet), so you should go to the options page and do it in the "Storage & backup" section.

I was able to delete my Sync account, but upon re-creating it with the same email, the sync error logs seem to still remember what extensions were previously used (including test ones I have that are not on Mozilla's Add-ons), so I'm not sure that it deletes anything, or at least not with the given short time between deleting and creating a new account...

I ended up replacing any long icon URLs with automatic favicon versions when uploading to Sync, to avoid running in the before-mentioned Sync problem that I encountered.

Please let me know if you find any problem. Thanks!

Cheers,
Daniel

**Comment by CanisLupus** [comment]
I'm closing this issue, but feel free to reply if you have more details about this since the above mentioned update. Thanks!

**Comment by CanisLupus** [comment]
That's fantastic! :) Thank you for the kind words and have a great weekend as well!

Daniel

**Comment by cipri-tom** [comment]
It works greatly ! Thanks a lot, Daniel ! I wish it was on by default, or at least better documented. But still, only 2 clicks away, so really nice solution ! Thank you !

**Comment by CanisLupus** [comment]
Hey, you're welcome! :) At the time there were a few problems that made me _not_ do it automatically, but I can take a look at this again in the future (there's an eternal list of "to-do"s). And you are right, it's not very well documented. If I add auto sync I can surely improve that as well. ;)

Cheers!
