### ISSUE TITLE
how to add this site?

### ISSUE THREAD

**Issue by iMpervert** [CanisLupus/swift-selection-search#114]
http://www.citcat.com/

**Comment by CanisLupus** [comment]
Hi there!

Unfortunately that site does not use the contents of the URL to create searches, so it cannot be used in SSS. :(

SSS would have to support different kinds of requests to support it (and other similar sites), and those kinds of requests would already be hard for most users to configure, since they require knowledge of what the website sends to their servers, which is not always obvious, even with development knowledge.

I hope that explains it, even if it doesn't exactly help.

Daniel

**Comment by ZIEXED** [comment]
`http://www.wikiilmu.com/wiki_i.jsp?l=2&query={searchTerms}&wk=y`

**Comment by CanisLupus** [comment]
Hey @ZIEXED, thanks for your input. :) Your reply got me thinking that I assumed @iMpervert wanted to use the translation fields, which is what came up when I opened the site. But yeah, maybe it's the search.

So, @iMpervert, if what you wanted was the first tab, "Wikillmu", ZIEXED has your answer. If it is the "Translation" tab, it can't be done currently. If it is the "Search" tab, it doesn't seem to work for me.

Cheers!
Daniel

**Comment by ZIEXED** [comment]
For this to work you must block scripts on that site or you will be redirected to the main page
`http://www.citcat.com/Green/trans.jsp?l=2&lp_select=1&scl=Malaysia&i_src={searchTerms}`
We can workaround the redirection that way but I'm wondering how this could be even supported without blocking scripts?

**Comment by CanisLupus** [comment]
That's.... interesting... ;) Nice find. I'm not sure what could be done either.

I'm closing this issue, but feel free to comment anyway!

Cheers!
Daniel
