### ISSUE TITLE
Integrate google translator icon in popup (if addon installed and enabled)

### ISSUE THREAD

**Issue by matijakovacevic** [CanisLupus/swift-selection-search#116]
now interferes with the addon in mention,
but could it be added so they can coexist?

https://add0n.com/google-translator.html

**Comment by CanisLupus** [comment]
Hey there!

I'm sorry, I don't know exactly what you mean but if this is an add-on then SSS doesn't support it. Only search URLs can be used in SSS. I've also noticed that the Google Translator add-on is not compatible with the current version of Firefox, so that's an additional problem. :)

However, if you want to translate words you can use something similar to what comes in SSS by default as an example, which is:

https://translate.google.com/#en/pt/{searchTerms}

This translates from English (en) to Portuguese (pt) using Google Translate (it comes disabled but you can enable it). You can use other languages instead of en/ and pt/.

I hope that helps somewhat!

Cheers!
Daniel

**Comment by matijakovacevic** [comment]
Yeah, sorry, now that I've read it again (my issue), I can see why you didn't understand what I meant :P

I'm using Firefox Developer Edition and Google Translator (GT) works there. I haven't tested it on the stable version.
The extension (GT) has great functionality where, upon selecting text, gives you a popup to be able to translate that selection on the fly, in the same popup.

But now your add-on has taken over (the popup I mean) and shows itself upon selecting text, thus overriding the behavior of GT.
Was thinking that it would be possible to make a custom btn if the addon in mention is installed and enabled, that when is clicked, simply triggers the usual behavior of GT.
