### ISSUE TITLE
Cannot change character encoding

### ISSUE THREAD

**Issue by Wcw5504** [CanisLupus/swift-selection-search#118]
I guess the extension always use  UTF-8 when searching. 
But some websites use others character encoding. for example [Getchu.com](http://www.getchu.com/) use EUC-JP for search terms.
Please add a option to change character encoding.

**Comment by CanisLupus** [comment]
Hello! :) Can you give me an example URL of a search that results in a wrong result (because of the wrong encoding), and then the correct URL (i.e. what it should be using the correct encoding?

To begin looking into this I need an example that I can check while I try fixing it.

Cheers!
Daniel

**Comment by Wcw5504** [comment]
This is correct [search sesult](http://www.getchu.com/php/search.phtml?search_keyword=%A5%BD%A1%BC%A5%C9%A5%A2%A1%BC%A5%C8%A1%A6%A5%AA%A5%F3%A5%E9%A5%A4%A5%F3)
As I using SSS to search, I would get this [result](http://www.getchu.com/php/search.phtml?search_keyword=%E3%82%BD%E3%83%BC%E3%83%89%E3%82%A2%E3%83%BC%E3%83%88%E3%83%BB%E3%82%AA%E3%83%B3%E3%83%A9%E3%82%A4%E3%83%B3).

Thanks.

**Comment by CanisLupus** [comment]
Okay, that helps a lot. Thanks! I'll look into this when possible, just can't promise when right now. Cheers!

**Comment by artyfox** [comment]
Character encoding options would also useful for Kanji language learning. For example,

- [http://www.zhongwen.com/bushou.htm](http://www.zhongwen.com/bushou.htm) Chinese dictionary uses Big5 encoding
- [http://www.nomfoundation.org/nom-tools/Nom-Lookup-Tool/](http://www.nomfoundation.org/nom-tools/Nom-Lookup-Tool/) Vietnamese dictionary uses Unicode encoding
- [http://zonmal.com/hanja_sen.asp](http://zonmal.com/hanja_sen.asp) Korean dictionary uses EUC-KR encoding

I found a useful javascript library for encoding conversion, that might help you :)

[https://github.com/ashtuchkin/iconv-lite](https://github.com/ashtuchkin/iconv-lite)

🦊

**Comment by darkj2k** [comment]
Any progress on this? With the option to defining character encoding for search terms is very useful especially for Asia web sites.

**Comment by CanisLupus** [comment]
So first of all, I apparently completely forgot to thank @artyfox for the links, but I did see them. Sorry and thanks! :)

@darkj2k I didn't have a lot of time to look into this (or much else SSS-related recently). To implement this I will very likely need a library like artyfox linked, since the encodings are complex and many. I searched for other libs and saw some limitations in the encodings they support, so iconv-lite is actually a good option. The problem I see is that it targets NodeJS and not web-based JavaScript, so it may or may not work out of the box. Regardless, I'll need to understand which files to use and in which way and, at worst, it will need some porting to include in SSS.

So, not a lot of progress, but I definitely recognize the importance of this feature.

Cheers,
Daniel

**Comment by CanisLupus** [comment]
This is not available yet but it's going well. ;) When I finish the next SSS version, the encodings option should be included. Work-in-progress image:

![image](https://user-images.githubusercontent.com/532708/67432864-f72d5980-f5de-11e9-9a58-fb19b9a41298.png)

NOTE: I'm trying to add a few things to SSS and this is one of them. Unfortunately the minimum Firefox version that SSS supports will be increased to 63 (from 52) due to using Shadow DOM and for my own sanity. Shadow DOM is not at all related to the encodings but it requires FF 63. It greatly simplified some things internally.

**Comment by artyfox** [comment]
Hey @CanisLupis, I just want to say your welcome and this looks awesome!

Can't wait to start using SSS with all my online dictionaries. 🦊

**Comment by CanisLupus** [comment]
@artyfox I should say that the library you referenced (iconv-lite) is a massive help and that SSS is currently using it for these encodings. :) I managed to use it without NodeJS since it supports Browserify and can therefore be bundled for the browser (or for a WebExtension like SSS).

As for the dictionaries, I hope you can use SSS with them. For the 3 examples that you mentioned I only managed to create a search engine for the last one (using encoding EUC-KR works nicely). The others seem to not change the URL when searching (they might use POST methods, which SSS doesn't support). That said, I haven't tried many things, especially since it's not easy to navigate websites in other languages. ;)

**Comment by artyfox** [comment]
That's really neat using Browserify to package up all the dependencies. Nice job! 👍

Yeah those 2 dictionaries I listed are tricky...I needed to inspect the HTTP requests to get the proper search format:

- For zhongwen.com -> http://www.zhongwen.com/cgi-bin/zis.cgi?ju={searchTerms}
- For www.nomfoundation.org -> http://www.nomfoundation.org/nom-tools/Nom-Lookup-Tool/Nom-Lookup-Tool?uiLang=en&anything=rNom&hiddenText=&inputText={searchTerms} (looks like this one supports UTF-8 now, hurray)

(Haha oops, sorry mispelled your name!) Anyways, keep up the great work @CanisLupus!

**Comment by CanisLupus** [comment]
Ah, fantastic, that helps. Much appreciated. :) Big5 encoding seems to be working fine for zhongwen.com in my WIP version of SSS, so that's great.

(No problem at all!) Cheers!

- Daniel

**Comment by CanisLupus** [comment]
SSS version 3.40.2 finally adds this feature, among other things. The tests I made seemed to be working, but I think you would be better judges of that. :)

If you find anything wrong, please let me know. If everything works we can happily close this issue.

NOTE: version 3.40.2 has two already-reported bugs (see #156) that will be fixed in 3.40.3 as soon as it is accepted to Mozilla Addons).

**Comment by Sasa358** [comment]
Hi, Daniel!
*I apologize for my poor English and I have no programming experience, but whatever...
I tried to add a search engine from the site https://www.rlsnet.ru/ (as https://www.rlsnet.ru/search_result.htm?word={searchTerms})  and everything was fine except for the character encoding (UTF-8, KOI8-RU and others from list did not help). «Парацетамол» looked like «БаБаБаБаБаБ» or «¶P¶P¶P¶P¶P&»...
So I used Ctrl+U on this site, then ctrl+F and "charset" on view-source, and found «charset=windows-1251"».
In SSS settings.js I added new item in EncodingGroup "Native" - ["Windows-1251","windows1251"], started the extension with about:debugging#/runtime/this-firefox Load temporary add-ons, and selected necessary win1251 encoding. «Парацетамол» now remains «Парацетамол».
Unfortunately, my programming knowledge ended there and although the result I needed was saved in the settings after Firefox restarting (and this search still work correctly), I couldn't save the encoding in the list (with UTF-8 and other).
So I guess it is possible to automatically detect the encoding on a specified page selected as a search engine and add it to the Text encoding list?
Or maybe it's useful to create a customization file to which the user can manually add the necessary encodings, like an user.js for Firefox, from which SSS will fill the Text encoding list?
What you  think about it?
And thank you for you great job )

**Comment by CanisLupus** [comment]
Hi! After a short search Windows-1251 seems like a relatively common encoding. I didn't know! Oops.

I will add it in the next update. I haven't had time for updates lately but I intend to return soon. What you did in the code is mostly what I'll do, regardless of your programming experience, but there were probably some steps missing. I'm afraid it's hard to know right now. :)

Regarding the encodings being user-configurable... the supported encodings are fully dependent on a third party code library named iconv-lite, so it's not guaranteed that the user will always try to use something that exists. It's probably better if I add new options on request, so that I can check if they work. Your example website will be helpful for this case, so thanks! :)

And thank you for reporting! Will look into this, hopefully soon.

Cheers,
Daniel

**Comment by classic81** [comment]
+1 to Sasa358. The same problem with lack of charset "Windows-1251". Can't do searching with russian words on https://forum.ru-board.com/. Please add it to your excellent extension. Thank you!

**Comment by CanisLupus** [comment]
SSS version 3.41.0 adds Windows-1251 encoding. I'm closing this issue, but please let me know of any related problems if they appear. :) Cheers!
