### ISSUE TITLE
Popup position

### ISSUE THREAD

**Issue by Fritz56** [CanisLupus/swift-selection-search#122]
Hi
Would it be possible to move the popup to another position. Directly on the crusor is bad, because there are other icons that are not visible then.

Thank you very much

**Comment by CanisLupus** [comment]
Hey Fritz, can you ellaborate on what you mean by other icons not being visible?

In any case, you can try the options page. Under "Popup/icons behaviour" you have the "Popup location", which you can change to the bottom corner of the selection instead of the cursor's position.

Additionally, under "Popup/icons look" you can set a "Popup vertical offset" and "Popup horizontal offset", both given in pixels, so that the popup appears further away from the cursor.

I hope this helps! :)
Daniel

**Comment by CanisLupus** [comment]
Closing this issue. Please reply with more information if you still need assistance with this.
