### ISSUE TITLE
Alt-click activation option is same as Auto

### ISSUE THREAD

**Issue by satnatantas** [CanisLupus/swift-selection-search#124]
Picking "Alt-click" in "Opening behavior" acts same way as "Auto". Other options work as expected.

v3.27.2
Waterfox 56.2.5 64b W7X64SP1

**Comment by CanisLupus** [comment]
Thanks for the report, you are right! It also happens on Firefox. I didn't notice the problem because it seems to work fine on the settings page itself, but not on other pages. I'll try looking into this as soon as possible.

Cheers!
Daniel

**Comment by CanisLupus** [comment]
I finally had some time to implement a few fixes. Version 3.28.0 should deal with this correctly. If not, please let me know! :)

This was caused by an issue typical of using TypeScript with WebExtensions _sigh_. My fault for not noticing, since I only tested the feature in the options page, which was the only place where it actually worked after I ported SSS to TypeScript.

Cheers!
Daniel
