### ISSUE TITLE
Context search on https://www.magnetdl.com/

### ISSUE THREAD

**Issue by MJ1979** [CanisLupus/swift-selection-search#125]
I'm sorry for posting here, as it is probably the site protection that is causing me trouble and not your extension, but I can't for the life of me do a search on https://www.magnetdl.com/

I have never seen the result of a search displayed in this weird behavior. Results of a search for the word 'gift are displayed as...
https://www.magnetdl.com/g/gift/
The site adds the first letter of the searched word in front and by doing this it makes it impossible to make a search link.  

Thank you for your hard work on this great extension...

**Comment by CanisLupus** [comment]
You are welcome to post here. :) Actually I had never seen this behaviour either, so it's nice to know and consider.

Unfortunately this means that SSS does not support that website, since the only feature that allows changing the searchTerms are the text replacements, which can't select just a part of the text (in this case the first character only).

I guess this means searchTerms needs more configurations in the future hehe (or support for random user code, which could prove difficult due to security policies). I haven't been able to work on SSS for a while because I've been working on other things in my spare time lately, but I'll try dealing with this and some other issues in the next update (don't know when yet! :p).

Thanks!
Daniel

**Comment by CanisLupus** [comment]
Trying to support this website (any other similar websites with weird query formats) has sent me down a loooong rabbit hole in searchTerms configuration haha. Totally worth it ;)

SSS v3.29.1 now supports several new things in searchTerms, including indexing/slicing to select only part of the selected text, regular expressions for complex replacements, and what I called "function", which right now is just a way to convert the text to lower case or upper case.

The way MagnetDL works is REALLY weird, but in SSS v3.29.1 you should be able to create something like this beautiful (_ahem!_) search URL:

`https://www.magnetdl.com/{searchTerms[0]}/{searchTerms{re/[']/g|}{re/[+_ ]/g|-}(lowercase)}`

- `[0]` is used to select only the first character of the text, to allow creating the path the site uses.
- `{re/[']/g|}` is a regular expression that matches any `'` characters and replaces them with nothing (the thing after the |). If you don't know regular expressions it's normal if this is confusing (unless you are a programmer you probably don't know them), but the regular expression is just `[']`. The `re/.../` is just my way of indicating to SSS that it is an expression and not simple text, and is similar to JavaScript regular expressions. The `g` indicates that the expression should match all occurrences of the thing, not just the first (to replace all `'` and not just the first). Again, this is to mimic JavaScript.
- `{re/[+_ ]/g|-}` is another regular expression (just `[+_ ]`) that matches the plus, underscore and space characters and replaces them with a dash. MagnetDL does that a lot.
- These expressions probably need some tweaks as you find new characters that the website removes or converts to dashes. Just add other characters inside the [ ].
- `(lowercase)` converts the text to lower case, because MagnetDL does not support upper case in the URL.

However, because you could select text that starts with upper case or a weird character, it's probably safer to use this (essentially same thing twice) to always get a valid one-char for that specific URL part:

`https://www.magnetdl.com/{searchTerms{re/[']/g|}{re/[+_ ]/g|-}(lowercase)[0]}/{searchTerms{re/[']/g|}{re/[+_ ]/g|-}(lowercase)}`

I hope this helps, even if it's very confusing. Please let me know. I can explain some part better if you want. :)

I guess I'm closing this unless something bad comes up.

Cheers and nice holidays!
Daniel

**Comment by MJ1979** [comment]
You were right, I'm not a programmer but you for sure are a good one. Your url works flawlessly. I can't thank you enough...

Thank you again for your hard work and happy holidays!!!

**Comment by CanisLupus** [comment]
Haha thanks! I'm happy that it works. :)

Just remember, if you search for something and it doesn't work, it's probably because the search contains more characters that MagnetDL does not support (I only added a few). For example, if you find that `!` is not supported (haven't tested it!), MagnetDL will either remove it or transform it to a dash. If it is the first case add it to the `[']` blocks, so they become `['!]`. If it converts it to a dash, add it to the `[+_ ]` blocks, like this: `[+_ !]`. You can keep adding more characters.

You are welcome. :) Thank you!
