### ISSUE TITLE
Question about favicons and referer privacy

### ISSUE THREAD

**Issue by AdKiller** [CanisLupus/swift-selection-search#127]
I was wondering when the extension popup loads a favicon inside a website, does the address of current site get referred to the source of the favicon?

**Comment by CanisLupus** [comment]
I must say that I haven't thought about this, so thanks for bringing it to my attention.

The best answer I can give is "probably not, but possibly". Maybe someone with more expertise on web protocols and tracking cookies can give us more information.

Usually this is not a problem, since SSS creates a local cache for each icon the first time it is added in the options page, also reducing it to 48px if too big. It does so to avoid requesting the icon via the URL each time it appears in the popup. Usually, any icon you add in the options page will from then on be using cache and not making any requests when shown.

However, it is possible that you leave the options page before the cache is generated. You would have to add the link and close the tab before its icon appears. If the cache is not present when the popup is requested in a page, SSS will use the original link.

If the link is visited, it is beyond my knowledge what information can be acquired, especially if the page includes Google Analytics or other tracking mechanisms. On SSS's side nothing special is done besides loading the image into an `img`.

Additionally, the SSS popup must be added to the layout/DOM of the page you are visiting, so unless I'm mistaken if that page has some malicious JavaScript that knows what it's looking for then it can figure out what icons you are using (their images and names only). Their search links are safe since they aren't added to the DOM and are scoped in the SSS content script for that page.

I'm not sure if this helps. Does it? :)

Cheers!
Daniel

**Comment by AdKiller** [comment]
Thanks for your detailed reply. 
Since I clear Firefox cache when it closes, I am not sure if SSS cache persists or not. but I noticed your addon at least does not use the favicons directly, it uses faviconkit.com. To me that is better than all the other similar addons.

**Comment by CanisLupus** [comment]
The cache in SSS is saved along its setting, using the local storage reserved for the addon, so it doesn't get cleared even if you delete full browser history, cookies and site data. In that regard you should be covered. ;)

Favicon Kit is very nice to find icons. I use some favicons from the actual websites in the engines that come by default with SSS, to give examples, but I'm thinking of relying only on Favicon Kit in the future (for consistency). New engines use it unless you specify another URL.

Cheers!
Daniel
