### ISSUE TITLE
Copy as plain text

### ISSUE THREAD

**Issue by simonbcn** [CanisLupus/swift-selection-search#130]
An additional option for copying plain text or that the current copy option could be configured would be very useful.

**Comment by CanisLupus** [comment]
Good suggestion! I don't use the copy function a lot myself, but this makes sense for a future update. Cheers! :)

**Comment by CanisLupus** [comment]
Hey Simón, I added an extra "plain text" option for "Copy to clipboard" in version 3.31.0. Please let me know if it's working for you or if it requires tweaks.

Turns out that forcing text to plain text using JavaScript is not very straightforward and required some... let's call them "hacks". ;)

Cheers,
Daniel

**Comment by CanisLupus** [comment]
Well since I already got 1 star for the plain text feature not respecting paragraphs, some improvements are probably in order :p

Due to the way I had to implement this feature, I also found it won't work on pages that forbid page modifications (such as addons.mozilla.org). And it fails silently, which is also not good.

**Comment by CanisLupus** [comment]
Resubmitted as v3.31.1 with much simpler code for the same effect, with the advantage of not needing to modify pages (still doesn't work on addons.mozilla.org due to other restrictions the site has).

**Comment by Gitoffthelawn** [comment]
OK... I must not be seeing something obvious... where is the copy as plain text option in v.3.31.1?

**Comment by simonbcn** [comment]
Same problem, I just updated the extension but I don't see that option. The actual copy does the same.

**Comment by simonbcn** [comment]
> OK... I must not be seeing something obvious... where is the copy as plain text option in v.3.31.1?

You must click on `Copy to clipboard` to open the options:
![captura_20190619_095034](https://user-images.githubusercontent.com/428231/59746715-c2e40e00-9277-11e9-92d1-f3b40355b336.png)

**Comment by simonbcn** [comment]
Thanks for the enhancement. It works well.

**Comment by CanisLupus** [comment]
Great!

Sorry for the location of the setting. I actually didn't think too much about it because when I implemented "expanding" engines in the table my intention was to allow adding individual engine settings in the future, so it felt normal to me.

But yes, for now it's a bit hard to find, especially since there's usually little reason to select "Copy to clipboard" (there's nothing to edit) and also because no other engines have more settings than "Show in popup" and "Show in context menu". Hopefully this will feel more natural with time (or else I'll have to find a way to make sub-options clearer).

Daniel
