### ISSUE TITLE
Chrome equivalence

### ISSUE THREAD

**Issue by lflee** [CanisLupus/swift-selection-search#132]
Thanks for the add-on. It's perfect as far as I can see.
My simple question is, does SSS have a Chrome equivalence? My feeling is that if a Chrome extension is recommended by you, it must be in good quality.
Thanks very much!

**Comment by CanisLupus** [comment]
Hello! Thank you, I'm happy that you like it. :)

Well, unfortunately I don't use Chrome and my time with it many years ago was short-lived so I feel like I'm not the best person to recommend an alternative to SSS on Chrome.

Perhaps you could try the one named "Selection Search" since it's generally well rated, but I really don't know much about it. There are also others like "Context Menu Search". They are always going to be different to SSS, for better or worse. :)

Cheers,
Daniel

**Comment by lflee** [comment]
Thanks for your advice. Found https://chrome.google.com/webstore/detail/selection-search/gipnlpdeieaidmmeaichnddnmjmcakoe . Closing the issue now 😊

**Comment by CanisLupus** [comment]
Yeah, that's the first one I mentioned. No problem, glad you found one that works for you. ;)
