### ISSUE TITLE
Blank Search Box

### ISSUE THREAD

**Issue by mortyobnoxious** [CanisLupus/swift-selection-search#136]
Hi, thank you for this great extension.

This is how extension behaves when i middle-click on a selected text which is fantastic: 

![image](https://user-images.githubusercontent.com/42044258/54866962-2f8c6100-4d8c-11e9-98ad-9ac2f6a881de.png)

So far so good.

I know this is a lot to ask but here is the request: what i want is when i middle-click on selected "space/blank character", can extension open a popup for "Blank Search Box" as in picture below?

![image](https://user-images.githubusercontent.com/42044258/54867095-6dd65000-4d8d-11e9-8c46-e63bf9d81618.png)

This will allow users to search whatever they want by typing it on "Blank Search Box".

![image](https://user-images.githubusercontent.com/42044258/54867157-18e70980-4d8e-11e9-959a-b935a93a8f94.png)

**Comment by CanisLupus** [comment]
Hi! First of all, thank you for the idea and for the work that went into your feature request (and example images). :)

Adding a search box is something I wanted to do (there's at least one related request in #64), but I have been away from SSS development for a while due to other priorities, so my apologies in advance if this won't get started soon.

I was thinking of adding an option to show a search box above the icons. It would show the selected text, and you could change it before pressing one of the icons to search for the text. So if you selected "some text" on a page, the popup would appear with a search box above the search icons, pre filled with "some text". Then you could change "some text" (for example, append something to improve the search), and afterwards click one of the search engines.

I realize your request is different, since it is directed to selections of empty space only, but maybe the above could generalize the behaviour. Ideally it would be possible to call the popup even without text selected, though. Something to consider. :)

Cheers!
Daniel

**Comment by mortyobnoxious** [comment]
That's actually better. Thank you for your consideration. No hurry, it can wait. :)

**Comment by CanisLupus** [comment]
Hi! Version 3.40.2 finally adds a text box. I think you noticed already. ;) I'll say that it's not as pretty as the one in your images, but works as I mentioned above. ;) The box seemed useful enough that I activated it by default. You may disable it in the options menu here:

Popup/icons look > Display text box

Please let me know if you find any issues with it (or with other things besides #156). This was a big update (at least comparatively to a normal SSS update!).

Cheers!

**Comment by mortyobnoxious** [comment]
It works great, with CSS, it looks better than images I posted above. Thank you.
![image](https://user-images.githubusercontent.com/42044258/70323887-1571b080-183f-11ea-9a55-ed274198d109.png)

**Comment by CanisLupus** [comment]
Hey, that looks great. :) You are welcome!
