### ISSUE TITLE
Popup behavior not consistent shows when selecting in editable fields via keyboard 

### ISSUE THREAD

**Issue by kswartz26** [CanisLupus/swift-selection-search#141]
I am finding the behavior of the "Allow on editable fields" option to be inconsistent when selecting text using the keyboard (e.g.: shift-ctrl-LEFT). 

The description on the options page states "Show the popup when text is selected with the mouse....", and gives email composition windows as an example. But it's not clear whether it SHOULD be doing this when selecting via a keyboard.

On github (where I'm typing this text now), when I select text with the keyboard here, it does not display the popup. It does do so when selecting with the mouse.

However, on GMail, it pops up the dialog even when I am selecting the previous characters to delete them.

If the description of the behavior on the options page is accurate, then the behavior on GMail appears to be a bug.

If the description on the options page is wrong, and the feature is acting as it is intended, then it's inconsistent (as in the case of github), and also, it's so distracting on GMail, that an additional option to limit that feature to mouse-selection only would be a highly desirable enhancement.

Using Waterfox 56.2.10 (I acknowledge it's not a mainstream browser, and respectfully apologize for not yet attempting to reproduce on Firefox 67. :) )

**Comment by CanisLupus** [comment]
Hello and thank you for the clear explanation. I can confirm the behaviour you are seeing, even on the most recent version of Firefox, so there's definitely something going on. ;)

I'm feeling like I should remember something related to this, but it was long ago so I'm not sure anymore. Either way, due to consensus on issue #33 (admitedly from a very small sample of users), I made the "Allow on editable fields" option work only when using the mouse, as it felt too annoying to work with keyboard selections too.

So indeed, the problem in Gmail seems like a bug. It also seems to be triggering when an existing selection _changes_ with the keyboard, not when it is _created_. I'll look into this whenever possible and get back to you.

Cheers!
Daniel

**Comment by CanisLupus** [comment]
Hey Simón, I added an extra "plain text" option for "Copy to clipboard" in version 3.31.0. Please let me know if it's working for you or if it requires tweaks.

Turns out that forcing text to plain text using JavaScript is not very straightforward and required some... let's call them "hacks". ;)

Cheers,
Daniel

**Comment by CanisLupus** [comment]
Hey, I had some time and SSS version 3.31.0 now tries to fix this issue. Hopefully this won't cause other problems. ;) Can you try it (whenever you can) and let me know if it works for you? Thanks!

Cheers,
Daniel

**Comment by kswartz26** [comment]
Tested it, and the problem is gone. I had also recently found the same problem reproduced when editing Confluence pages -- I can confirm it no longer happens there witih 3.31.0 either. Thank you!

**Comment by CanisLupus** [comment]
Fantastic, thanks for confirming! :)
