### ISSUE TITLE
Version for Chrome?

### ISSUE THREAD

**Issue by DavidBE-UK** [CanisLupus/swift-selection-search#148]
Have you considered putting up a version for Google Chrome? Now both Firefox and Chrome use WebExtensions, I gather it should be quite easy to do. I mostly use Firefox, but occasionally have to use Chrome, and it would be great to have the same extension for both, as I do with quite a few other extensions (and the equivalent to this by someone else for Chrome has stopped working after the last Chrome update). Also, I gather Chrome extensions also work in the new upcoming Chrome based Microsoft Edge browser too..

**Comment by CanisLupus** [comment]
Hi David,

I have considered this in the past, but there are 2 things that were and still are a problem for me. :)

1. Although they both use WebExtensions, some WebExtensions APIs are only available on some browsers. Not sure if I am using any of those in SSS, though. It's also possible that the manifest file for the extension must be different for each release, since it cannot contain browser-specific differences all in one (for example, Firefox for Android, which I tried porting SSS to at one point, would not support some manifest entries and required a completely different file). Not a big issue, however.

2. Time. This is the bigger reason. I don't use Chrome, so my ability to provide support and test the addon is greatly reduced, already discarding the time to go around any eventual browser differences in the implementation. It happens more frequent that I'd like that I make an update and break something in SSS for an older Firefox version that I still want to support. I can only imagine what would happen if I tried supporting SSS for a browser and addons market that I don't use. ;)

So... it's easier to have it working on more browsers now than it was a few years ago, but it's still bad because I'd never have the time to support it (and there are a lot more people on Chrome too, which is both a blessing and a curse). I think it's mostly a matter of SSS being free. For a paid thing I'd do what would reasonably get me more revenue, but in this case I focus on keeping SSS consistent for Firefox, which is easier. I hope this is understandable. ;) I, too, wish it was simply on all browsers, but probably not in any near future.

I write a lot, don't I? x)

Cheers!
Daniel

**Comment by mikelei8291** [comment]
Don't worry, there is already a Chrome version of "SSS", while these "S" stand for ["**S**imple=**S**elect+**S**earch"](https://chrome.google.com/webstore/detail/aagminaekdpcfimcbhknlgjmpnnnmooo), and it is also open source on [GitHub](https://github.com/frenetix/SimpleSelectSearch). I can also confirm that it still works for the latest stable version of Chrome (76.0.3809.100) at the time of posting this reply.

I used to use it on Chrome before I switched to Firefox, and missed it a lot (even thought about porting it to Firefox) before one day Firefox told me: "Hey, check out this great extension for searching selected texts on Firefox Add-ons!". Then you know what happened next. Fun story, isn't it? 🤣

To be honest, I still missed some of the features like grouping and directly searching in private browsing, so maybe Daniel can focus on adding more features like these on the "Firefox version of SSS", rather than porting it to Chrome?

**Comment by CanisLupus** [comment]
Wow... I had no idea there was another plugin with similar functionality with the same acronym. Definitely an interesting coincidence! At least it's on Chrome, so I guess that's why I didn't know.

;) Mozilla showing SSS in the featured addons section causes a few funny interactions. I've had a friend of mine randomly see SSS and my name and realize something... :p

I also think it would be best to focus on the features (when I'm able to work on them again, that is) than on porting to Chrome.

Thank you very much for being open to help. :) I accept pull requests and I'm up for correcting and integrating them. It was probably easier for other people to change my code when it wasn't in TypeScript, but the type checking helps me (although it's very quirky because of WebExtensions). I wish I could just use C#.

**Comment by CanisLupus** [comment]
Hey, I forgot that this issue was still open but I'm closing it since there are no plans to port SSS to Chrome due to the reasons stated above. I hope this is understandable!

Cheers!
