### ISSUE TITLE
[Feature Request] Allow pop-up to close on keyboard input

### ISSUE THREAD

**Issue by e-t-l** [CanisLupus/swift-selection-search#151]
**Describe your suggestion**
A minor bug I noticed is that when I have text highlighted (in an editable field), if I type some characters to replace the highlighted text (or if I hit backspace or delete), then the highlight disappears but the SSS pop-up remains. Would it be possible to add an checkbox to the options to allow the pop-up to close when a keyboard key is pressed? (Not including keys like Alt, Ctrl, Fn keys, arrow keys, etc).

**Comment by CanisLupus** [comment]
Thanks for the report! It was not supposed to work like this. :)

I've tested it and it seems to depend on the text box. For me, on google.com it doesn't send the popup away if you press backspace/delete OR if you write characters. However, in the GitHub search box it does if you write characters, but not for backspace/delete. Furthermore, on Firefox 52 (the oldest version supported by SSS) it seems to work as expected, so something might have changed at some point and I'm not aware.

Cheers,
Daniel

**Comment by CanisLupus** [comment]
Hey, can you take a look and tell me if the just-released SSS update 3.40.2 fixes this for you? Whenever you can. :)

NOTE: version 3.40.2 has two already-reported bugs (see #156) that will be fixed in 3.40.3 as soon as it is accepted to Mozilla Addons.

As said, the popup should already close on (most) keyboard inputs, but backspace/delete had a few particular issues, which I fixed in this version.

**Comment by e-t-l** [comment]
Seems to work for me!

**Comment by CanisLupus** [comment]
Awesome, thanks for confirming. :)
