### ISSUE TITLE
Some popup searches don't work after upgrading to V.3.40.2 

### ISSUE THREAD

**Issue by Thomasc5** [CanisLupus/swift-selection-search#156]
After upgrading to V.3.40.2, some popup searches don't work. (yet some do)

I'm not sure if it is due to the search URLs? For example, the Google search works , yet the Amazon search doesn't.  (i.e. it doesn't launch a new search page in the background):

![Capture](https://user-images.githubusercontent.com/5540385/69924723-d9a9b480-14e7-11ea-9ecb-04d1dfd289c1.JPG)

Reverting to the previous SSS version (v.3.33.1) solves the problem.

Browser: Firefox 70.0.1 
OS: Windows 7

Thank you.

**Comment by xyzcheese** [comment]
Me too ! Same problem here.

**Comment by Mobius-BC** [comment]
Also seeing the above issue with V.3.40.2.
In addition; I can no longer hold down Ctrl while clicking (to open in New Tab), as the Popup disappears as soon as I press the Ctrl key

**Comment by T-Halen** [comment]
add me to the 'me too' list.

**Comment by CanisLupus** [comment]
Hey everyone, thanks for the reports. Only now was I able to return on my computer since the update went live, but I'll be looking into this now (lunch hour) and later today.

I can easily see the problem mentioned by @Mobius-BC, but I'm not seeing the issues with searches. Amazon.com (default SSS search engine) works for me. May be a problem with different settings than mine.

Does this happen consistently for Amazon? Only when opening in the background or always? (like when opening on the same page)

Can someone please export their settings and leave at least one engine that causes the problem so I can take a look? (please delete anything private!) I would really appreciate it.

Cheers!
Daniel

**Comment by T-Halen** [comment]
I've attached my settings. Amazon doesn't work for me. In fact, none of the searches work for me except Google.
[SSS settings backup (2019-12-02T13.50.05.698Z).json.txt](https://github.com/CanisLupus/swift-selection-search/files/3911571/SSS.settings.backup.2019-12-02T13.50.05.698Z.json.txt)

**Comment by mortyobnoxious** [comment]
Same here. Some of the websites that doesn't work:
```
https://eksisozluk.com/?q={searchTerms}
https://www.youtube.com/results?search_query={searchTerms}&page=&utm_source=opensearch
https://twitter.com/search?q={searchTerms}
http://www.imdb.com/find?s=all&q={searchTerms}
```

**Comment by CanisLupus** [comment]
Thank you very much for the extra info. :)

I believe it is fixed, along with the problem @Mobius-BC was seeing (Ctrl, Cmd, Shift, and Alt keys were closing the popup but weren't supposed to). I submitted version 3.40.3 but now it's up to Mozilla reviewers to complete the process, so you'll have to wait a bit more. :(

Turns out that this only happens with browser-imported engines, so that's why only some engines had the problem and why I wasn't seeing it. It was a change I made on the 22nd of August (this update has slowly been getting done over a few months :p) which ironically said:
> inconsequential type checking and namespace changes

Sorry for the trouble! I'm leaving this open until we can all confirm that the problems are gone.

**Comment by Mobius-BC** [comment]
@CanisLupus Many thanks for the quick response and solution. :) 
Ctrl issue and all the search engines I use, work as they should now.
A great little add-on. Respect!

**Comment by T-Halen** [comment]
I forced the update this morning, and all seems well here now (so far). Thanks for the quick action on the issues!

**Comment by CanisLupus** [comment]
You are welcome! Thank you all for reporting it so quickly too, because I really need that to know the problems that slipped past my tests. :)

I'm closing this. Feel free to reopen if any of the bugs are not completely fixed after all.

Cheers!
