### ISSUE TITLE
Blacklist needed to disable the add-on on certain websites.

### ISSUE THREAD

**Issue by Surfingserenity** [CanisLupus/swift-selection-search#161]
Blacklist needed to disable the add-on on certain websites, especially Facebook that auto-selects anything you've typed into the search box when you click on to it, which brings up the swift-selection dialog box which blocks the search box.

**Comment by CanisLupus** [comment]
Hi! This is now probably the most requested feature for SSS, along with engine folders. :p I'm closing this issue since this suggestion is already covered in #145. I hope you don't mind. You can subscribe to that issue for future updates.

One way to avoid these kinds of problem is to change the opening behaviour to something like "middle mouse click" so that the popup only appears when you actually want it, but this is a workaround, of course. :)

Cheers!

**Comment by CanisLupus** [comment]
Just letting you know that the feature was added for the new version 3.42.0. "Website blocklist" setting, located inside "Popup/icons behaviour" ;)

Please check the other issue (#145) for more details!

**Comment by Surfingserenity** [comment]
Thanks, this is working like a charm :)

**Comment by CanisLupus** [comment]
Great! Thanks for letting me know. :)
