### ISSUE TITLE
Add option to auto-copy text only outside editable text areas

### ISSUE THREAD

**Issue by do-bo** [CanisLupus/swift-selection-search#163]
Hi, 
I would like to suggest a feature: add option that will stop auto-copy working in editable text areas.

Right now, when you have some text in the clipboard and select text in an editable text area to paste over it, that text gets automatically copied, which is counterproductive. I know I can disable the popup completely in text fields as a workaround, but I would like to retain this functionality.

I think the best way would be to add another position to the "Auto copy to clipboard" combo box:

- Off
- Outside editable text areas
- Always

Cheers and thank you for this addon!

**Comment by CanisLupus** [comment]
Hi!

Thanks for the suggestion. I think the reason you give makes sense. :) It's not an option I use myself, so I never noticed that potential problem. I have noted it down.

Cheers!
Daniel

**Comment by markran** [comment]
Adding this capability would be *very* valuable for me as well. I love the auto-copy feature but I had to stop using it just because of what it did in edit fields. In an edit field, the act of selecting [Old Edit Field Text] to replace with the clipboard contents [New Clipboard Text], replaces [New Clipboard Text] in the clipboard with [Old Edit Field Text] - right before I'm about to CTRL-V/Paste it. 

In fact, I would suggest you make this behavior the default for auto-copy because I can't think of a practical use case in an edit field where the current behavior would be desired. Also, if someone did want to select text and have it copied, they can still use the "Copy to Clipboard" icon. Whereas in the more common case, there's no workaround other than stop using auto-copy.

**Comment by CanisLupus** [comment]
I'll try checking adding this to the next update. NOTE: There will be a new version in the next few days (3.43.0) since it is currently awaiting review, but I don't mean that one. Hopefully the one after that, when I implement this. ;)

**Comment by markran** [comment]
Hi, just checking in to see if there's been any progress...

**Comment by CanisLupus** [comment]
Hi @markran, unfortunately I haven't had time for any SSS updates lately (since the last one), so no progress, but I'm thinking that this should be easy to add so probably the next version will have this. I'll let you all know.

**Comment by markran** [comment]
Thanks! Will wait anxiously but patiently. :-) Sorry to pester you about it. I wish I had the code chops to help but alas I do not...

**Comment by CanisLupus** [comment]
Hey everyone! SSS version 3.44.0 finally adds this feature. :) I just submitted it, so it will be awaiting review by Mozilla in the following days.

![image](https://user-images.githubusercontent.com/532708/89123398-f22efc00-d4c6-11ea-89bb-138a1dd8d99d.png)

When you are able to test it out, please let me know if there are any problems with it.

Cheers!

**Comment by markran** [comment]
It works great! Thanks Canis! Much appreciated!

**Comment by CanisLupus** [comment]
Glad to hear it! Thanks for confirming. ;) I'll close this issue then.
