### ISSUE TITLE
popup pannel not working

### ISSUE THREAD

**Issue by ale82to** [CanisLupus/swift-selection-search#17]
in firefox nightly 53 and mac osx pop up panel is not working it just opens a new tab of serach engine without previously  selected text for search.

**Comment by CanisLupus** [comment]
I downloaded Firefox Nightly 53 just now (I only had 47 and Developer Edition at 52) and I'm actually writing this from it. :)

Unfortunately I couldn't reproduce your issue. It seems to work as normal here. I'm using Windows, however, and I have no way to test it on a Mac. Could you please attach a screenshot of the issue here? From what I understood, in your case it opens a new tab with the search engines instead of a small popup.

Could you also please try disabling other addons and see if any of them is conflicting with SSS?

Thanks!
Daniel

**Comment by CanisLupus** [comment]
Closing this for lack of additional info. Sorry! Please reply if you still have problems, especially since I've just updated SSS for WebExtensions and it's a whole new version.
