### ISSUE TITLE
Multiple rows for search engines

### ISSUE THREAD

**Issue by peter099** [CanisLupus/swift-selection-search#172]
It will be useful if there is a option to separate search engines in multiple horizontal rows instead of just one?

**Comment by CanisLupus** [comment]
Hi Peter, there is an option for this:

![image](https://user-images.githubusercontent.com/532708/71767429-43ace380-2f04-11ea-93e7-7c37b816b323.png)

The difference is that instead of specifying how many lines, you specify how many icons per line (meaning you can't ask for more lines than needed).

I hope this helps!
Daniel

**Comment by peter099** [comment]
Thanks! I missed this option somehow.

**Comment by CanisLupus** [comment]
You're welcome! :)
