### ISSUE TITLE
Use preconfigured and customized search engines

### ISSUE THREAD

**Issue by frankgerhardt** [CanisLupus/swift-selection-search#176]
I spent quite some time and intelligence setting up my search engines. The green plus icon in the search field helps with that. 

![2020-02-04-164425_3840x3240_scrot](https://user-images.githubusercontent.com/550621/73841711-73108200-481b-11ea-9625-21da0ec8ff21.png)

In SSS I was surprised to see that my search engines are not use but another set.

It would be great if SSS would use the search engines I have defined already.

Without that SSS is too hard to seup up for me because I would have to reconfigure every search engine. My workaround is to select text and then drag it into the search field. There I can select one of engines I have configured.

This is a bit similar to #166, #37, #77, #111, #172.

**Comment by CanisLupus** [comment]
Hi Frank,

These are engines that you added to Firefox itself, correct? In SSS's options page you should see this below the list of engines:
![image](https://user-images.githubusercontent.com/532708/73888472-9a8c3c80-4865-11ea-9fe2-d32f716e6889.png)

You can use this button and select the right file (see instructions to the right) to import all your Firefox engines into SSS without too much trouble (hopefully :)).

The problem of SSS not doing this automatically is actually tracked in issue #106, which admitedly is not titled in the best way. ;) In my last post there I mention some of the reasons that ultimately led me to not implement this right now and reduce it's priority in my view. Currently the information that SSS can get from Firefox is limited. I could work around some things, but I expect that it would be confusing for users that some engines would not have a link at all or support some features, and I didn't find a good compromise yet.

I'll close this issue eventually since it's already tracked (but with a better title, no doubt), but please tell me if the search file solves the problem acceptably for you. :)

Cheers!
Daniel

**Comment by frankgerhardt** [comment]
Thank you for your answer. I didn't see this import feature. I reinstalled SSS and did the import. Everything is fine. Just a minor thing was, that the search engines are randomly ordered after the import.

**Comment by CanisLupus** [comment]
Great! :)

Hmm... I believe SSS imports them in the order they appear in the file, but there may be something that specifies their actual order. I'll note it down to look into at some point.

Cheers!

**Comment by frankgerhardt** [comment]
I'm glad to find that SSS also supports export/import so I can move the setting between machines.

**Comment by CanisLupus** [comment]
I'm glad it's useful to you. :) When SSS began having more than a handful of options this quickly became important. It can also upload to Firefox Sync, if you use it, but only on demand (by clicking the Save/Load buttons).
