### ISSUE TITLE
Searching "Link Text"

### ISSUE THREAD

**Issue by mortyobnoxious** [CanisLupus/swift-selection-search#179]
Hi, is it possible to add an option to search "link text" with mouse shortcuts.

For example, when mouse is over a link "**pressing down right click** + **middle click**" will open popup with the text of link.

Example:
![image](https://user-images.githubusercontent.com/42044258/74396909-6ea02680-4e24-11ea-8afe-988e4400f03f.png)

It's sometimes hard to select link texts, this would be useful, i think, if you consider.

**Comment by CanisLupus** [comment]
Hello! I believe this idea is similar to issue #120 (though at the time there was no text field) but I'll confirm at a later time. This is one of the things I'd like to do but never got around to.

By the way, the user on that issue mentioned using the Alt key when selecting text (totally unrelated to SSS shortcuts; this is a Firefox thing) to allow selecting text in links without "dragging" the text. I'm letting you know since it's useful and not a very well-known feature. ;)

**Comment by mortyobnoxious** [comment]
Thanks. I was aware of "alt+selecting link texts" but I was looking for a mouse only solution. :) If this is duplicate, you can close it.

**Comment by Mike-Reddick** [comment]
Try the extension "Drag-Select Link Text"
