### ISSUE TITLE
Find {searchTerms} on this page

### ISSUE THREAD

**Issue by markran** [CanisLupus/swift-selection-search#181]
The use case is quickly finding an earlier reference in a long article or paper, such as where a character is introduced without doing CTRL-F and retyping or pasting the term. Maybe this is already possible but I couldn't find how to do it.

BTW, I really love SSS. It is definitely my most valuable plug-in of all time. I pretty much can't use the internet without it anymore!

**Comment by CanisLupus** [comment]
Hi @markran! That kind of search is a browser feature, not a search engine that has a well-formed URL, and SSS only supports those. In other words, SSS only supports opening new pages with a search, not searching already open pages.

Unfortunately it's a completely different kind of operation that SSS is not built for (even then, searching backwards is probably second in the list of most common search directions ;)), so I would really really really recommend using Ctrl+F since it's unlikely that SSS will come to support that.

I can, however, suggest using keyboard shortcuts. :) If you first select the words you want to search for before pressing Ctrl+F, the search will be filled with the text already (this is common). Then you can press F3 to search forward in the page and Shift+F3 to search backwards (less commonly known).

Thank you for the kind words, I'm happy to hear that it is so useful to you! :)

Cheers,
Daniel

**Comment by markran** [comment]
Ah, that makes complete sense. Thanks for your prompt and thorough explanation! 

After pondering it for a bit, based on your tip about Shift+F3, I think I can cobble together an almost as good solution by having Logitech's mouse macro software send a Shift+F3 when over Firefox.

**Comment by CanisLupus** [comment]
You're welcome! That sounds like a good compromise. :)
