### ISSUE TITLE
Unintentional URL encoding of {href}

### ISSUE THREAD

**Issue by in4u** [CanisLupus/swift-selection-search#183]
**Describe the problem**

`{href}` search parameter somehow automatically gets URL encoded while searching as `https://web.archive.org/web/*/{href}`.

This auto encoding doesn't happen on other websites, e.g. `https://webcache.googleusercontent.com/search?q=cache:{href}` or `https://archive.is/{href}`.

**How to reproduce the problem**

1. Add search engine for `Web Archive` as `https://web.archive.org/web/*/{href}`.
2. Navigate to `https://www.mozilla.org/en-US/firefox/`
3. Select any text on the page and click the `Web Archive` search engine option.
4. There will be no result because the search will somehow be done for `https://web.archive.org/web/*/https%3A%2F%2Fwww.mozilla.org%2Fen-US%2Ffirefox%2F` instead of `https://web.archive.org/web/*/https://www.mozilla.org/en-US/firefox/`.

**System info:**
- Browser: Firefox
- Browser version: 74.0
- System: Windows 10

**Comment by CanisLupus** [comment]
Ah, interesting. I could reproduce it nicely with your steps and engines, thanks! It is likely that web.archive does not recognize the escaped URL format but Google and archive.is do.

However, the root problem is that I call encodeURIComponent for all JavaScript properties (href included), I guess with the intention of making sure that they can be used in a URL. I clearly didn't give this as much thought as it needed, since the properties already come from a URL, so of course they should already be valid. :p

I think I can fix this in the next update after I become more confident that this won't break anything. I've been away from work on SSS for a while but I'm preparing a few fixes for "soon-ish". :)

Cheers for the report!
Daniel

**Comment by CanisLupus** [comment]
Hey @in4u, I fixed this in version 3.41.1 by removing the forced encoding on all those variables like href. :)

Please let me know if the problem persists in any way!

**Comment by in4u** [comment]
Thanks @CanisLupus, it's working great! Will let you know if something's still amiss.

#### *BTW off-topic because not sure if it's an issue you're already aware of:*

I've noticed this addon breaks on some sites when adblocker is enabled. Almost every adblocker uses [Easylist](https://github.com/easylist/easylist) filter as default. And Easylist blocks ads on some sites with rules like `##[src*="base64"]` and `##[src*="data:"]`. What these rules do is block all elements whose `src` attribute contains the string `base64` or `data:`.

This addon gets impacted because its text selection popup then has all the customized search engines missing on any such site. You can test yourself by using uBlock Origin or any other adblocker of your choice which has Easylist filter enabled and triggering the search popup by selecting any text on `https://www.opensubtitles.org` for example.

More such sites on which this addon breaks due to Easylist can be found in [this](https://github.com/easylist/easylist/blob/master/easylist/easylist_specific_hide.txt) section of Easylist. Look at specific rules on [this](https://github.com/easylist/easylist/blob/462be31ea4864abb2fafdd5c181a7eb9ff156ff7/easylist/easylist_specific_hide.txt#L9890) and [this](https://github.com/easylist/easylist/blob/462be31ea4864abb2fafdd5c181a7eb9ff156ff7/easylist/easylist_specific_hide.txt#L9892) line, all those sites are impacted and this addon's popup is broken in those cases.

It'd be awesome if you can figure out a way to work around or with Easylist. Looping in @ryanbr to see if he can suggest a possible solution.

**Comment by CanisLupus** [comment]
Great, thanks!

I am aware of the issue, though thanks for the heads up. :) Users had problems in the past because of ad blockers so I added this to the top of the options menu:

![image](https://user-images.githubusercontent.com/532708/77225453-14069280-6b67-11ea-87ca-6936af709014.png)

It's not directly related to the `src` filters you mentioned, but from there people should understand that it's a problem caused by the ad blocker (that is, of course, if they read it, which probably won't happen most of the time :p).

As for actually fixing the problem, I'm not sure. This would be a case of an extension fighting with another extension, and all extensions are sovereign in the browser space, so I'm not sure what is possible exactly. I've never tried researching possible solutions, or even how AdBlockers achieve the blockings.

Cheers!

**Comment by in4u** [comment]
If I add the following whitelisting rules in adblocker for say, `opensubtitles.org`, then the addon works as expected for that site:

`opensubtitles.org#@#[src*="base64"]`
`opensubtitles.org#@#[src*="data:"]`

I think if you are not able to work around it then perhaps Easylist should update their filters to be more narrow and specific instead of being broad and generic.

Am waiting to hear if @ryanbr has a solution you could try at your end otherwise will have to open an issue over there.

**Comment by in4u** [comment]
Hey @CanisLupus, this Easylist related adblocker problem of missing search engine icons in the popup has almost been fixed now. But while testing I ran into a new problem with `magnetdl.com` on which text selection doesn't even trigger the popup despite disabling adblocker. Can you reproduce the same?

**Comment by CanisLupus** [comment]
Hey, I've read the issue you opened on uBlockOrigin's side. They were very fast. :) It's unfortunate that the list blocks things inside ShadowDOM by default (SSS uses ShadowDOM precisely to avoid these kinds of problems!).

Regarding magnetdl.com, without the adblocker I see the popup as normal, even on a search page. Are you on any specific page? However, a user reported #185, which was caused by the previous SSS update, and this could be related.

**Comment by in4u** [comment]
Yes, they're pretty fast and responsive indeed! A [suggestion](https://github.com/uBlockOrigin/uAssets/issues/7129#issuecomment-602197542) that you could try has come up over there. See if you can work out something to iron out the compatibility issues.

As for `magnetdl.com`, I don't get the popup on any page of that site. Even resetting the addon's settings yielded no luck.

**Comment by CanisLupus** [comment]
Version 3.41.2 should be available now. Do you still have the same problem on magnetdl.com?

I see the popup:
![image](https://user-images.githubusercontent.com/532708/77355465-651baf80-6d3c-11ea-9c03-e0c4c557558c.png)

I've also left a reply in the other thread and acknowledge the suggestions. Maybe I can try them out in the future. I'm glad they resolved it so quickly, though. :)

**Comment by in4u** [comment]
Even with 3.41.2, I had this `magnetdl.com` problem on two different systems but with exact same settings. Resetting settings failed. Removing and reinstalling addon didn't work either.

What resolved the issue was: exporting settings as backup > installing the XPI as a temporary extension > removing it via debug addons menu > installing the XPI as normal extension > importing the backed up settings.

Maybe one of the past updates included a breaking change or messed up something in the addon's settings which were not getting reset.

And yes, that thread did have good recommendations. The current resolution was more like a temporary band-aid because it's just for a handful of rules I managed to find on a cursory glance. There are tons of other rules and lists which people regularly use. You should seriously consider implementing those suggestions so as to avoid getting hit by adblockers!

**Comment by CanisLupus** [comment]
Well, SSS reading the settings from a file or from an exported file _supposedly_ runs the exact same retrocompatibility code to add settings that weren't present previously. The fact that that process fixed it is really strange!

Regarding the other thread, I understand this is mostly a patch. Sadly, there are no guarantees that implementing the suggestions will work, but I'll try them when I have some time, also taking into account the other TODOs I have.

**Comment by in4u** [comment]
Export/import step was optional and just to bring back my prefs. The key was installing as temporary extension and then removing via debug addons menu. Am wondering why the regular removal of addon didn't work?!

**Comment by CanisLupus** [comment]
Maybe Firefox keeps the saved data for the extension if you remove it (not sure how it deals with this, or if there is a duration for that supposed data) but completely deletes it when removing a temporary addon...?

That said, I don't get why that would solve this problem since the settings reset didn't. Reset creates a copy of the hardcoded default settings. Weird!

**Comment by in4u** [comment]
I suspect one of the older updates in the past may have been buggy in the sense that some setting(s) may not have properly carried over or got messed up with newer ones or something. But I got it working now, so all's well that end's well. Cheers!

**Comment by CanisLupus** [comment]
I suppose, but reset should have solved that. Maybe this mistery will show up somewhere else eventually... :) Cheers!
