### ISSUE TITLE
Could you add a option that close the popup window after  6  seconds

### ISSUE THREAD

**Issue by lyscop** [CanisLupus/swift-selection-search#188]
If it is convenient that take it to concern that add an option that close the popup window after 6 seconds if I select the context. I know there are some options like strolling, click the icon, etc. Someone may need it also.

**Comment by CanisLupus** [comment]
Hi there! Well, this could be added, but I fear that this is an option that people would try and then find out that it doesn't work that well, and it would add a lot of unwanted complexity. Can you tell me why this option would be great for you? I might not be seeing something! I have added a timer in the past, for "Popup delay". I didn't like it but it fixed a problem for some people (ex.: triple click to select paragraphs, which causes the popup to blink twice).

I can think "the popup going away after some time is good because if I've not used it in X seconds it means I won't use it after that", but in that case you can also be explicit and scroll or click to deselect the text and dismiss it. If it is bothering you at some point, would you wait for it to go away instead of just dismissing it?

The worst situation is when you actually want to use it and it disappears because you took too long, and then you have to select the text again (or use the keyboard shortcut).

It also raises a few questions:

Would it close X seconds after the popup appears? Would the timer stop while you are hovering the popup? What if you are not hovering but just writing into the text box? When you hover-out, does the timer restart? How do the other "hide" options (on scroll, click, etc) play with it? Do they just override it and close the popup regardless of the timer?

All of these things (and a few more) need code to deal with this, and the timer introduces asynchronous behaviour which then several other parts of the code have to deal with by checking, setting, and stopping the timer.

Cheers!
Daniel

**Comment by lyscop** [comment]
Dear Dan, I am glad that you take this small issue seriously, and I find how kind of you are that you have thought about all of the possible aspects of this option. 

Sorry that this similar request troubles you again. I hope SSS will be better and better.

**Comment by CanisLupus** [comment]
There's absolutely no problem in requesting it. :) It's just that I've thought about this feature before and it doesn't seem like it would be worth the trouble. I could be wrong, of course, so it helps if people can justify why it would be a good thing to have.

Regarding the Chrome request, I will refer you to issue #148 (it's closed so it's not easy to find, unfortunately), where I have given my current reasons for not working on a Chrome version.

Maybe you can try [this](https://chrome.google.com/webstore/detail/simple-select-%20-search/aagminaekdpcfimcbhknlgjmpnnnmooo) Chrome extension (even has the same letters as SSS), but I've never used it, so I don't know if it's a good replacement!

I have even thought of making a Chrome version of SSS that requires a small payment to access more advanced features (the Firefox version would still be free). This would support development on Chrome, but I'm not sure what I want to do about that!

Thank you for understanding. :)
