### ISSUE TITLE
Is There A Workaround For Google Docs?

### ISSUE THREAD

**Issue by s3hMC** [CanisLupus/swift-selection-search#197]
This question has already been asked (#131), but I would like to know if there are any possible workarounds to using this add-on in Google Docs.
Thanks for any help!

**Comment by CanisLupus** [comment]
Sadly I don't know of any. :( Recap from the other issue, with some more info:

If you select text on a page and right click, Firefox normally shows you the "Search Google for" entry (replace "Google" with your default search engine) and other selection-related options. This doesn't happen in Google Docs.

1. Google Docs overrides the context menu with its own.
2. In issue #131 I mentioned that you also won't see the usual text selection options when right clicking outside the document's editable area (such as above the tools header) after selecting something inside, but that could simply be due to Google Docs using different frames, which have separate selections.
3. If you `Shift+Right Click` inside the document to force the browser's context menu to show up, it STILL won't have the usual options for text selection.
4. You may notice that as soon as the browser's context menu shows up, the selection in the doc gets greyed out, as if it's out of focus. That may be why Firefox doesn't see the selection, but Google Docs may also simply do things differently.

Well... This is all I know right now. :\

Daniel

**Comment by s3hMC** [comment]
Okay. Thanks!

**Comment by s3hMC** [comment]
If it helps, LanguageTool has a Google Docs mode. Maybe you could see how they do it? I don't know - I'm no expert.

--s3hMC
