### ISSUE TITLE
SSS lost all my settings and reset to default by itself, how to restore?

### ISSUE THREAD

**Issue by opav** [CanisLupus/swift-selection-search#198]
I just noticed SSS reseted back to defaults and all my customization are gone.

My last backup was folder backup of my Firefox profiles back in Jan 2020.

Please advise which SSS files I need to restore back to fix this.

**Comment by CanisLupus** [comment]
Hi @opav, can you tell me when did this happen?

In version 3.43.0 I made a big mistake (see #195) that caused all settings to be cleared and for which I'm very sorry. However, that version was up for about 2 hours, and version 3.43.2 (current one, available since 18 days ago) completely fixed the problem, so seeing a problem like this come up _now_ is strange and could be due to some other unknown reason. Can you tell me more about this?

You can restore your older backup through here:

![image](https://user-images.githubusercontent.com/532708/83947538-85bdb680-a80f-11ea-9bb3-23d604b16857.png)

...but maybe you already know that and are just looking for a way to recover more recent changes. If that is the case I don't think it's possible, sorry (unless this is a different problem, such as a different Firefox profile being used, etc). :(

Daniel

**Comment by opav** [comment]
It happened more than a week ago, but I left it alone, thinking it was a temporary glitch.  But now finally it exceeded my tolerance limit and push me to find out what happened. :sweat_smile:

I know there is a import settings but I never export before.   Instead what I have is a filesystem level backup from Jan 2020.

So appreciate you can tell me which SSS specific file or files to restore back to which folder in my Profile folder to fix this.

**Comment by CanisLupus** [comment]
Aaaah, a filesystem backup. Somehow I didn't register that you wrote "backup of my Firefox profiles". I thought this was something else.

I was trying to find out how to do this just now. I believe Firefox stores things in multiple places, but I'm not sure what is needed.

If you write
`about:debugging#/runtime/this-firefox` in the URL you can see the IDs for each extension. SSS has extension ID `jid1-KdTtiCj6wxVAFA@jetpack`, so this next folder should contain part of the storage for the extension (in my case it contains nothing relevant, however):

C:\Users\<user>\AppData\Roaming\Mozilla\Firefox\Profiles\<profile>\browser-extension-data\jid1-KdTtiCj6wxVAFA@jetpack

Then again in `about:debugging#/runtime/this-firefox` you can see that SSS has an internal UUID (not sure if it's always the same, so please copy the one you see). The main storage should be located here:

C:\Users\<user>\AppData\Roaming\Mozilla\Firefox\Profiles\<profile>\storage\default\moz-extension+++<internal uuid>^userContextId=<user context>

So maybe if you get these two folders it works...? Sorry I'm not being very reassuring, but this is what I could find. I hope it helps, but please let me know.

Daniel

**Comment by opav** [comment]
I looked at the folders, no obvious SSS settings there.  Seems like a lot have changed under the hood. 

Thought it will be as simple as copying a file back.

**Comment by ZIEXED** [comment]
SSS settings are stored in {**%FirefoxProfile%\storage\default**}

You can **open** your **profile folder** using **about:support**

look carefully in the **storage\default** folder as mentioned above the folder that contains SSS settings should **start with** "**moz-extension+++**" and then **followed by** the extension Internal **UUID** (which is different per user) to get the UUID that belongs to SSS as explained above from here

`about:debugging#/runtime/this-firefox`

**Comment by opav** [comment]
Thanks Ziexed.  But in the end, I restored the previously backup profile, started Firefox on it, exported my original SSS settings, switched back to current Firefox profile and got SSS to imported it back successfully.

What a joy seeing my custom base64 icons and search engines back at last.

**Comment by ZIEXED** [comment]
Whichever the way; I'm glad you were able to get them back :)

**Comment by CanisLupus** [comment]
Just coming here to say that I'm also glad you were able to recover everything. :) Phew...

I'll be closing this now. Cheers!
