### ISSUE TITLE
Sometimes Pops Up When Playing A Youtube Video

### ISSUE THREAD

**Issue by s3hMC** [CanisLupus/swift-selection-search#200]
Sometimes when I play a YouTube video, SSS pops up. Is there any way to stop this from happening without disabling the entire add-on on YouTube?
Thanks!

**Comment by CanisLupus** [comment]
I'm 90% sure this is due to the language zone "superscript" in the YouTube logo at the top left. :)

![image](https://user-images.githubusercontent.com/532708/84010127-20cba300-a96c-11ea-91dc-8619fea636e0.png)
(notice how "PT" is selected)

Sometimes when clicking the video to pause/play, if you _slightly_ drag the mouse, Firefox will select the text in that place. It is annoying but there's a better solution than disabling the popup:
![image](https://user-images.githubusercontent.com/532708/84010411-828c0d00-a96c-11ea-85c8-688b7b176273.png)

Set the value of "Minimum selected characters" to at least 3 to avoid this problem. Although I personally prefer to simple use this opening behaviour, in which you only call the popup when actually needed:

![image](https://user-images.githubusercontent.com/532708/84010480-9e8fae80-a96c-11ea-9925-eb1f56fdebf8.png)

Let me know if this solves the problem. ;)

Cheers!
Daniel

**Comment by CanisLupus** [comment]
I haven't heard back from you, but I'll assume this was solved and close it. :) Let me know if it's not!

**Comment by s3hMC** [comment]
> 
> 
> I haven't heard back from you, but I'll assume this was solved and close it. :) Let me know if it's not!

Sorry, forgot to respond. Yes, it fixed the issue. Thanks!

**Comment by CanisLupus** [comment]
No problem! Great to hear that it helped. ;) Cheers!
