### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by AlexFundorin** [CanisLupus/swift-selection-search#216]
Hi, Daniel.
Could you, please, add folders option to SSS?
I'm already using 12 engines with SSS, including "copy to clipboard". I have them divided by two rows in the pop-up. It would be nice to add some extra, without cluttering the pop-up view, like Discogs, eBay, Bing, etc. These aren't used often, but I still use them, occasionally.
I see this as a folder icon (customizable) placed alongside the regular search engines. It would change the contents of the pop-up, while being clicked, by displaying a ".." icon first and then all the other search engines, contained inside that folder.
As for the context menu, it would be displayed as a regular context folder.
What do you think about this idea?

**Comment by CanisLupus** [comment]
Hi Alex, thanks for the suggestion! This was requested by some users but I never got around to doing it. Igor Costa has been working on engine groups for searching multiple engines with a single click, and I have been reviewing the changes. Since the groups feature is closely related to folders it will hopefully make it easier to eventually add support for folders similar to what you described. :)

We already have issues #152 and #100 for folder requests, so I think I'll close yours (please subscribe to those issues for eventual updates).

Cheers!
Daniel
