### ISSUE TITLE
Click Behaviour options not working?

### ISSUE THREAD

**Issue by torporous** [CanisLupus/swift-selection-search#218]
I've recently started using SSS and it does everything I could want, except that most of the the click behaviour options don't seem to be working properly.

The "Open in this tab" option works as expected, but all other options work the way I assume "Open in new tab" is supposed to - they all open the search results in a new tab at the end of the tab list, and switch to that tab. 
"Open in new window" does not open a new window, the "background tab" options still switch to the new tab, and the "next to current tab" options still open the new tab at the end of the list.

The problem is the same on both the context menu and the popup, and with all three mouse buttons, and disabling all of my other extensions didn't fix it.

Win 10 Pro x64 1909, FF 82.0.3, SSS 3.46.0

**Comment by CanisLupus** [comment]
Hi there!

I realize this doesn't help much, but on my end all click behaviour options seem to work. Since I haven't got other user reports about this and the version has been live for a while, either the issue is in your Firefox or you have a very particular combination of options that cause this. You said you disabled all other extensions and the problem persisted, which is intriguing.

Can you please try exporting all your settings to a file as a backup (bottom of the options menu) and resetting the options (very last button in the page)? Does the problem persist? After checking you can re-import the settings file as normal.

When you disabled the other extensions, did you restart Firefox? Not sure if it makes a difference, but better to try. :)

If it persists then I currently have no clue of what it could be. Maybe some setting in Firefox's about:config?

**Comment by torporous** [comment]
I've done some more testing, and it looks like it only happens when the search engine is imported from the browser. The default or manually entered ones all work fine.

**Comment by CanisLupus** [comment]
Ah, it didn't cross my mind that that was what you were seeing! But yes, browser engines are currently limited in the way described in this "note":
![image](https://user-images.githubusercontent.com/532708/99573914-9c775480-29ce-11eb-9fda-bbd1966c4d66.png)

I've been slowly reviewing a pull request by Igor that, along with a new feature, also adds support for all opening behaviours on browser engines too, so hopefully in the future this problem will disappear too. :)
