### ISSUE TITLE
Popup appears when clicking on video to play / pause

### ISSUE THREAD

**Issue by J0n1k4** [CanisLupus/swift-selection-search#219]
Popup appears when clicking on video to play / pause on YouTube (maybe on some other sites too).

Might be related to:
https://github.com/CanisLupus/swift-selection-search/issues/140[https://github.com/CanisLupus/swift-selection-search/issues/140](url)
Lot of times when I click on a video to play. The popup appears. and then I have to click again on the video to remove the popup. But, by clicking again - I paused the video again, so I have to click on it again to play... And there we go again...
I am not sure why is it not happening every time, but maybe I just move a mouse a little bit while I click the mouse button...

A bit annoying, would be nice if you could look into this... As I read, you have a lot of priorities. I understand, I can't find time for some important things myself, but wanted to let you know that there could be some issues - if anybody else has the same problem...

Cheers

**Comment by CanisLupus** [comment]
You have convinced me to add this issue to the "Problems?" section of the options page hahah. From time to time I get a report like this. I blame webpages in general and YT in particular.

So, this probably happens to you because of this:

![image](https://user-images.githubusercontent.com/532708/99711502-bd58ac00-2a99-11eb-89a2-82f63519ae0a.png)

If you click the YT video and very slightly move the mouse while you do that, you will select the country code right beside the YT logo. This is what causes the SSS popup to appear (i.e. the browser selects that text).

To fix this, I suggest either:
1. Set this option to 3.
![image](https://user-images.githubusercontent.com/532708/99711691-01e44780-2a9a-11eb-985b-fc1832df206d.png)
2. Change you opening behaviour to something other than automatic (I use "Middle mouse button").

I hope this helps! Please let me know. ;)

**Comment by J0n1k4** [comment]
Yep. That's it. Now that you pointed out - I see the 2 little bastards myself... 
I have changed the min. sel. characters - it does the trick... 
Thanks, and sorry for taking your time...
Cheers,
Nika

**Comment by markran** [comment]
Interestingly, I already have "Min Sel Chars" set at 4 but have the same (or very similar) issue, however only sometimes. It only seems to happen when the mouse pointer is moving a bit when I click (or the page is scrolling slightly). If all is still and I click cleanly, it doesn't happen. Also, I'm using YT in the US (so no two-letters on my page). Instead, the attached image is what I see.

<img width="363" alt="firefox_G0BdFkEUZd" src="https://user-images.githubusercontent.com/6378626/99999307-d18bfa00-2d74-11eb-9693-ddb6a5910673.png">

The text in the dialog appears to be the entire page's source.

` (function(a,b){if(!window.EnhancerForYouTube){var f=JSON.parse(localStorage.getItem("`

**Comment by CanisLupus** [comment]
No problem, @J0n1k4. Glad it was just that. :)

@markran Wow, that is very bizarre. SSS only writes in the text box what was selected, so the problem is likely that something is getting selected when it shouldn't. Did you notice that `EnhancerForYouTube` in the source you pasted? Can you disable all plugins other than SSS and see if the problem persists?

**Comment by Slevest** [comment]
I set the maximum number of characters to 30. This solved the problem. about 2,300,000 characters are captured on YouTube, Notepad ++ slowed down when inserting :)

**Comment by CanisLupus** [comment]
Oh wow, do you have any idea why this happens to you too, @Slevest? Indeed, the max chars solution works and I completely forgot about it, so thanks! But that selection should really not be happening, and I suspect it's an addon, since I've never seen this.

**Comment by J0n1k4** [comment]
> I set the maximum number of characters to 30. This solved the problem. about 2,300,000 characters are captured on YouTube, Notepad ++ slowed down when inserting :)

Acctualy - I use the select - popup-menu - copy option quite often when I want to copy some longer text from FF... But - I suppose that it is better to limit the max char. no. to, say, 2000, then to copy 2+ million...

**Comment by CanisLupus** [comment]
SSS 3.47.0 adds a new item to the "Problems?" section, about this common YouTube play/pause thing that was the original issue. ;)

Regarding the other issue of selections with thousands/millions of characters, sadly I don't have enough information to research this, but I still suspect it may be caused by another addon. If anyone can confirm that this is a problem in SSS, could you please create another issue if you have the time? Thanks!

Cheers!
