### ISSUE TITLE
Can't Type Spacebar into SSS Text Box

### ISSUE THREAD

**Issue by markran** [CanisLupus/swift-selection-search#220]
Canis, 

I hope this finds you doing well. 

I can type any character into the pop-up's text box *except* Spacebar because that scrolls the browser page down, which closes the pop-up even if "Hide popup on page scroll" is deselected. Spacebar scrolling the page appears to be a [long-term problem](https://www.google.com/search?q=firefox+spacebar+scroll) with FF and other browsers. Unfortunately, there appears to be no way to disable this behavior. It's a significant issue because it prevents the primary use case of SSS having a Text Box (per the SSS docs).

> "Shows a text box with the current text selection in the popup. Useful to make edits to the text before searching with one of the engines."

The edit I need to mostly do is adding an additional search term, which requires typing a space.

I found a [claimed solution](https://support.mozilla.org/en-US/questions/1205298) with this [UserScript](https://greasyfork.org/en/scripts/38545-prevent-spacebar-doing-page-down) but it doesn't fix the problem for me. I suspect the only solution may be to address the issue in SSS's code.

SSS 3.46.0 on Firefox 83.0 on Win10 x64 2H20.

**Comment by CanisLupus** [comment]
Hi there! For better or worse, this has never happened on my end and it's actually the first time I'm reading this. I was always able to add spaces in the box without issue. 🤔

Unrelated to SSS, I know that a few times I'm on YT and press space and the page scrolls because presumably the wrong thing is focused, but it has never happened to me on SSS, especially since there's no reason for it to do that when the text box has focus.

Can you please try with all other plugins disabled? If it persists, is there any setting you can remember changing in Firefox that could cause this?

**Comment by CanisLupus** [comment]
Hi @markran, any news?

**Comment by markran** [comment]
After more extensive testing the problem was some setting or other add-on outside of SSS. Unfortunately, I don't know what I changed exactly that fixed it. I'm closing the issue.
