### ISSUE TITLE
Incorrect favicons from api.faviconkit.com

### ISSUE THREAD

**Issue by Slevest** [CanisLupus/swift-selection-search#221]
For example:
https://api.faviconkit.com/sinonim.org/64
https://api.faviconkit.com/rutracker.org/64
Correct:
https://icons.duckduckgo.com/ip3/sinonim.org.ico
https://icons.duckduckgo.com/ip3/rutracker.org.ico

**Comment by CanisLupus** [comment]
Hi Slevest, if these icons are wrong it would be an issue with faviconkit, so could you report it to them? SSS is unrelated to faviconkit and already provides a way for the user to replace the icon URL with something else, so I don't think there's anything else I can do here. :)

**Comment by Slevest** [comment]
How can I load icons from folders on my computer?

**Comment by CanisLupus** [comment]
Normally, you'd add it using an icon URL like `file:///C:/Some/Folder/image.png`. However, images from your computer get blocked from showing on web pages for security reasons, otherwise the JavaScript in the site could access them, so they won't show up in the SSS popup OR the options page. They do work on the context menu, though.

So in general you can't. :| You could upload your icons to some image service and then use the public link they provide, however.

I hope this helps. I'll close this issue since this was a problem with faviconkit.
