### ISSUE TITLE
[feedback] No need to get the Steam search through Google

### ISSUE THREAD

**Issue by IvoAndonov** [CanisLupus/swift-selection-search#222]
I gotta say this addon is EPIC! Literally! Once you get how to add new search engines, it can be used as anything, not just for searching things. I'm using it as a quick translator, using this string: https://translate.google.com/?hl=bg&sl=auto&tl=en&text={searchTerms}&op=translate - guess what this string does to the selected text. :D 

**Describe your suggestion**
It's not so much of a suggestion as it is a feedback. I can see that by default the Steam search is run through Google by this string: https://www.google.com/search?btnI&q={searchTerms} site:steampowered.com
But this is unnecessary because Steam has its own search engine which can be used directly, like this: https://store.steampowered.com/search/?term={searchTerms}

**Anything else you'd like to include**
If you have any English files, can I have them, so that I can translate the addon's settings to my language? Once done, I'll send them back.

**Comment by CanisLupus** [comment]
Hi Ivo, thank you! :) Translation engines are indeed very useful, and you can also use `https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text={searchTerms}` to translate any language to English, for example (at the mercy of Google's auto language detection, of course :p)

Actually, that Steam engine existed as a way to show SSS users how you could use Google's "I'm feeling lucky" search, where it would open the first result automatically (hence the name "Open top Steam page"). However, it doesn't make as much sense now since "I'm feeling lucky" has changed. It should probably be removed or changed to something else, yes! I'll leave this issue open until we fix that.

Regarding the translations, I really appreciate you being open to translating SSS. I truly do. However, I simply can't have translations right now. Sorry! This is not even a technical limitation; it's just the fact that I wouldn't be able to handle contacting multiple people every time any piece of text changes, or every time more text is needed. Text would EITHER be perpetually out of date (or missing parts) on everything but English OR I would have to force myself to not update any text or not release features to avoid having text changes. :(

In the future I could think of providing support for translation files, where users could create "fan translations" for people to install, but I also feel that a lot of the appeal would be lost if languages weren't included in SSS by default and users had to search for them.

Cheers!
Daniel

**Comment by IvoAndonov** [comment]
There's no need for the users to search for languages. If you make the addon to detect which Firefox interface language is used, then you can match the translation to that language. Using my very basic knowledge of C# It would be easier to show you what I mean than explaining it.

if (browserInterface == bg || browserInterface == Bulgarian)
{  SSSlang = bg; }
else
{ SSSlang = en; }

I hope you understand what I mean. :) 

Thus the user won't have to search for the language to enable it, it will be enabled automatically.
As for the other thing - for as long as this addon is working in Firefox, I'm more than willing to translate it for those Bulgarians who don't speak English. Not just now but also translate every new feature you add to it in the future.

**Comment by CanisLupus** [comment]
I understand but the limitation is really not technical. :) The suggestion of users searching for translations was because that's an approach that doesn't have to go through me, although it's definitely not ideal and I don't like it either.

I more or less know how it would be implemented, but I simply don't have time to handle the process of translations, even if made by other people. At least not for a free addon like SSS. It isn't even translated to Portuguese, my native language.

Well, an explanation. :p

I work in games/apps. After we translate their content to several languages through multiple translators, any and all further changes to text (or sometimes other localized content like images) become extremely cumbersome to make. Suddenly, any text that changes or gets added must go through 10 or more different people that you have to contact (and pay them, in that case), you have to try to give them the text in a way that is easy for them to understand and easy for you to integrate, you have to validate their changes to make sure nothing breaks (translators frequently break by accident whatever format you give them the text in), you have to create translation notes like "this has to be a max of 100 characters" or "if this word doesn't exist in your language, try using something like X", etc.

You also have to decide what to do if a translator doesn't reply back in time or doesn't reply at all. Do you delay the release? Leave half of the new text untranslated and deal with the emails and bad reviews? Remove the language and piss off everyone? This is all besides the work to implement this and maintain the text IDs for each and every text. :)

So... while I really appreciate the intention and the fact that SSS would be more accessible to people all around the world, this is a big problem for me.

**Comment by CanisLupus** [comment]
And believe me, I thank you for wanting to translate this addon. I think that's great. It's just that I know how messy the process of translations is (even with very collaborative people!).

**Comment by IvoAndonov** [comment]
As you wish. Just so you know - I'm not asking you to pay me, that never crossed my mind nor it will.

Besides, I'm not that kind of person to stop answering. I too have other things to do + a job (though a freelance job, but a job nevertheless). But you're right - if the person isn't answering, that can be discouraging. I had started helping with translating KDE but the chief translator suddenly stopped answering my e-mails with translated files, so I eventually gave up. Plus it's hard to translate something you don't see in front of you (I'm using Cinnamon, not KDE). But in this case it won't be hard at all bc I'm using the addon, it's infront of me all the time. :) 
I just checked the settings.js file and noticed SSS' settings window supported dark mode - something I didn't know before I opened the settings.js, LOL

Anyway, if you change your mind, comment this feedback topic and I'll receive an e-mail for the new comment. ;)

**Comment by CanisLupus** [comment]
I understood that you meant to translate the addon for free. :) I was talking about industry, hence the "in that case".

I didn't mean you in particular when I said that people may stop replying. You may very well be fully cooperative and great to work with. :D But from the point where languages get implemented onwards it is expected that many languages get added, and that multiplies the chance of problems. Even with very cooperative people it is difficult.

If you are looking at a JS file then you are maybe seeing the package contents(?). That JS is automatically transpiled from the original code in TypeScript, and probably much harder to read than the original .ts. If you want to take a look at code, I highly recommend checking the .ts files in the "master" branch in this repository, as it represents the currently public version.

If languages ever get added in any form, I know who to contact for Bulgarian. ;) Thanks!

PS: I'll soon close this issue because the soon-to-be-public version 3.47.0 of SSS simply replaces the old "I'm feeling lucky" default engine with a simple Steam engine like you mentioned. But I can always comment here again in the future.

**Comment by IvoAndonov** [comment]
One last thing before you close the issue: the new version will remember my settings, right? I know I can export them to a file but I would prefer if I didn't have to import them back after the update.

**Comment by CanisLupus** [comment]
Ah yes, all versions are retrocompatible. :) (unless something really bad happens like the major f-up that you can read in #195) It's always good to backup to a file if you invested a long time creating your engines or settings, but in general it just works.

SSS 3.47.0 is now available. Hopefully without problems (there were big changes).

Closing! Thanks!

**Comment by IvoAndonov** [comment]
Well, it has updated (I didn't even notice when that happened and I don't need to :) ) and so far I don't see any problems; all of my settings from before 3.47 are there. If there are any problems, I'll come by again. ;)

**Comment by CanisLupus** [comment]
Great! Mozilla distributes addon updates gradually to all users, unless auto updates are disabled, so it's usually very silent. ;)
