### ISSUE TITLE
Add Search Engine: Infinity Search

### ISSUE THREAD

**Issue by InfinitySearch** [CanisLupus/swift-selection-search#227]
Would you consider adding our search engine, [Infinity Search](https://infinitysearch.co) to the list of search options to choose from?

**Comment by CanisLupus** [comment]
Hello there!

I've been asked before to add more search engines that respect user privacy, and while I'm definitely not against that, my answer will be similar to the one I gave in issue #196.

I tend to add engines that many people will want to use, so as to avoid clutter (people who don't know an engine will probably never use it, although sure, they could try), and because users can freely add their own engines as they wish.

I appreciate the focus on privacy and non-tracking ads. It's a big reason I use Firefox myself. Maybe if I believe that your engine is more well established among users I could add it. #196 has a couple more points, though.

For anyone stumbling here, to add Infinity Engine this is enough: `https://infinitysearch.co/results?q={searchTerms}`.

Cheers!
Daniel

**Comment by InfinitySearch** [comment]
@CanisLupus That is completely understandable. Thank you for showing how to manually add it!

**Comment by CanisLupus** [comment]
@InfinitySearch You are welcome! :) I will close this issue but keep this in mind for the future.
