### ISSUE TITLE
Right click on search engine in popup doesn't work

### ISSUE THREAD

**Issue by justsurfinhere** [CanisLupus/swift-selection-search#235]
The tab won't open with a right click in the popup although it works in the context menu.
The exception is the SSS settings page, there it works fine.

**System info:**
- Browser: Firefox Version 90.0
- System: Windows 10

**Comment by CanisLupus** [comment]
Hi @justsurfinhere :)

1. Does the problem persist when disabling all other addons? Conflicting addons would be the most common cause of problems.

2. If it persists, can you tell me what are your settings for opening with the right click? i.e. these two, from the "Popup/icons behaviour" and from "Context menu":

![image](https://user-images.githubusercontent.com/532708/126404211-bc156fa5-d0ff-4383-a578-67001bc95110.png)
![image](https://user-images.githubusercontent.com/532708/126404225-a7efa87d-356a-467f-a50b-5379bdd24684.png)

3. Is this happening for any particular site or simply for every site except the settings page?

Daniel

**Comment by justsurfinhere** [comment]
Hey Daniel,
sorry for the wait.
So I found the culprit addon to be Gesturefy. The workaround is to use the option to use it's deactivator button via ctrl/alt/shift, so there's that. Also I put the SSS right button click on 'Open in this site' which I rarely use, so it's fine, I guess.

Yet I found that context menu still pops up after clicking on a search engine. Is this intended by Mozilla possibly?

Furthermore, the placement of the popup within search fields via double- or triple-clicking is just a little bothersome. I switched to 'bottom right corner of selection' but that placement is just a little too close to text if its in one bar.

Lastly, big thanks for this addon. Can't express how much easier surfing is with this. There have been addons doing similar tasks in the past but eventually faded with newer versions. Keep on, hopefully Mozilla gets your attention and you get compensated.

**Comment by CanisLupus** [comment]
Hmm if the context menu still opens when right clicking an engine (if I understood it correctly), it probably means that Gesturefy or something else is still interfering with the right click. It shouldn't happen with SSS only (unless you "Shift+Right click", which forces the context menu (browser rules)).

For the popup position you can perhaps try changing the "Popup vertical/horizontal offset" values so that the popup shows below your cursor instead of above. It may help!

Thank you for your kind words! :) Mozilla got SSS into the group of recommended extensions a few years ago, so that was cool. I'm not actively developing the addon right now, so that's more than enough. :)

I'll close this but let me know if I can help with anything here and I'll get back to you when possible.
