### ISSUE TITLE
Help  for Gesturefy message to open SSS popup

### ISSUE THREAD

**Issue by kiyn** [CanisLupus/swift-selection-search#237]
Could anyone help me find the correct message to put in Gesturefy so that the Swift Selection Search popup is correctly opened?

Here is the gesturefy reference:
https://github.com/Robbendebiene/Gesturefy/wiki/Send-message-to-other-addon

Thanks!

**Comment by CanisLupus** [comment]
Hi! Late reply from me, but since SSS is not currently being developed I tend to not come here as often unless there's any severe problem. :)

To answer your request, as far as I understand, SSS would have to implement the Gesturefy API for this to work:
> (...) which then can be used to run other add-ons functionality, **if the add-on supports it**

So I don't think there's currently a way for you to configure things to open the SSS popup. Sorry!

**Comment by kiyn** [comment]
Thank you very much for answering me even if the addon is not being developed anymore and thanks for your great work.

**Comment by CanisLupus** [comment]
You're welcome! Thank you for your kind words :)

**Comment by Gitoffthelawn** [comment]
Just a thought as I don't currently use Gesturefy... can Gesturefy be configured to simulate the pressing of the user-definable shortcut key combination that opens the SSS popup?

**Comment by kiyn** [comment]
Unfortunately that is not possible:

https://github.com/Robbendebiene/Gesturefy/issues/325

**Comment by Gitoffthelawn** [comment]
> Unfortunately that is not possible:
> 
> [Robbendebiene/Gesturefy#325](https://github.com/Robbendebiene/Gesturefy/issues/325)

Bummer!  Maybe someday. :)
