### ISSUE TITLE
Always when I play a YouTube video, SSS pops up. Mentioned soultion of 3 char minimum not working. Clipboard appears blank but popup opens on youtube. 

### ISSUE THREAD

**Issue by Paramirage** [CanisLupus/swift-selection-search#248]
-------------------

**Always when I play a YouTube video, SSS pops up. Is there any way to stop this from happening without disabling the entire add-on on YouTube?
Thanks!**

**How to reproduce the problem**
1. Go to 'youtube.com'
2. Click on 'play/pause'
3. Popup appears. settng minimum length of character does not help. only auto open behavior change works. but i prefer auto selection open.
4. In my case there is no country code in youtube and after extensive try i did not find anything which is copied by sss in youtube as it appears always blank. Only popup appears. 
![Screenshot 2022-03-31 at 15-25-14 12 STRONG - Official Trailer](https://user-images.githubusercontent.com/37746522/161023116-8ddff9db-b202-4560-ae0e-a723355c82c2.png)

**System info:**
- Browser: [e.g. Firefox]
- Browser version: [98.0.2]
- System: [Windows 10 21H2]

**Comment by CanisLupus** [comment]
Hi there!

Looking at your screenshot, it seems to have some design changes from the YouTube norm. Do you have addons installed for YouTube? If you do, please try disabling all of them and see if the problem persists, so that we can find out if SSS is the culprit. :)

There was once a user that had problems using Enhancer for YouTube because it seemed to cause hidden text to be selected. You should be able to see what text is being selected if you enable the popup's text box:

![image](https://user-images.githubusercontent.com/532708/161584134-901ef72b-8aa2-4378-a3ab-54420371f60c.png)

Please let me know when you've had a chance to try these. Thanks!

**Comment by Paramirage** [comment]
Solved this by turning on your option . Greasemonkey is the culprit where i enabled remove dislike and auto loop script. I created solution by setting maximum character 300 as it selected more than 1000 character of utter non sense after selection in play/pause function.

**Comment by CanisLupus** [comment]
Ah, I see. I think last time I heard of something like this, the maximum character limit was also the "solution" (or rather, "workaround").

Glad you could solve it! :) I'm closing this, then.
