### ISSUE TITLE
Empty search with active Search term highlighter addon

### ISSUE THREAD

**Issue by nilsboy** [CanisLupus/swift-selection-search#25]
If Search term highlighter[1] is activated to highlight selected words in a page SSS searches for an empty string with the selected search engine.

Could you look into this?
Thank you!

PS. The Selected Search addon does not suffer from this - if that helps track the problem.

[1]: https://addons.mozilla.org/de/firefox/addon/searchtermhighlighter/?src=api

**Comment by CanisLupus** [comment]
Thank you for the report. :) I'll see if there's something I can do when I have time. I have been away from SSS for a while because of other stuff, unfortunately.

Daniel

**Comment by CanisLupus** [comment]
Hello! So... after many months I'm looking into this. I'm very sorry for the extreme delay. SSS is now a WebExtension so I can now take care of the less critical issues.

I installed the extension and successfully got it to highlight things on a page, in this case https://www.wikipedia.org/ with "wikipedia" as the highlighted text, but SSS still seems to work, even when selecting text inside or including a highlighted word.

If you still use both the highlighter and SSS, can you please confirm if it works for you now? Or if there's a specific setup that causes the problem. I don't think I have changed anything that could fix the issue, but maybe the other extension changed something...? :)

Daniel

**Comment by nilsboy** [comment]
Thank you for testing this.

It still happens - the settings have to be:
- Enable highlighting
- Enable keyword capture

But don't waste your time with this - maybe the hightlight addon will not even be ported to FF 47...

Thanx

**Comment by CanisLupus** [comment]
Unfortunately I couldn't reproduce it. My settings are already enabled by default, and it still works here.

![highlight settings](https://user-images.githubusercontent.com/532708/32299759-a684015a-bf4e-11e7-9e68-6f53d69e4d0c.PNG)

I wonder what might cause this to work differently on different computers. This is definitely _not_ the first issue that I can't reproduce. :( For me it works on Firefox 56.0.2 (and 57.0b13 dev edition), using SSS 3.4.0 (actually anything since 3.0.0) and Search term highlighter 7.9.

Thank you for your concern. :) Well, if the highlighter gets updated and there are still problems, feel free to reopen this.

Cheers!
