### ISSUE TITLE
Unable to remove swift-selection-search firefox extension shortcut

### ISSUE THREAD

**Issue by operammm** [CanisLupus/swift-selection-search#250]
Every time I clear the shortcuts for swift-selection-search in the Firefox extension shortcuts, close Firefox, and open it again, these shortcuts reappear. Other extensions do not have this problem, and they will not be automatically added again after clearing the shortcut keys, such as ublock.

The default shortcuts of swift-selection-search are in serious conflict with my other operations, and I have no more shortcuts to assign to swift-selection-search. In fact, for me, the settings in swift-selection-search give me enough quick access to various functions that no additional keyboard shortcuts are needed to control swift-selection-search.

Firefox 91.10.0esr (x64) 
Windows11

**Comment by CanisLupus** [comment]
Hi there! Currently SSS's shortcuts should be disabled from its settings menu under "Popup/icons behaviour", by deleting the shortcut (the text), here:

![image](https://user-images.githubusercontent.com/532708/116575508-9d5dcc00-a906-11eb-90eb-b98969840491.png)

My reply in issue https://github.com/CanisLupus/swift-selection-search/issues/233 ([this reply](https://github.com/CanisLupus/swift-selection-search/issues/233#issuecomment-829339301)) contains a brief history of why it's like this (not very good reasons, to be honest 😅). Sorry for the inconvenience!

Please let me know if this fixes the problem. If not I have to dig a bit more. :)

**Comment by Gitoffthelawn** [comment]
@CanisLupus Hi Daniel! I hope you are doing well!

Would resolving this issue be as simple as removing those two rows from the SSS settings page and setting the corresponding internal values (within SSS) to null?  The `manifest.json` file has good defaults, which as you know, can now be changed via Firefox's `about:addons` settings.

**Comment by operammm** [comment]
> Hi there! Currently SSS's shortcuts should be disabled from its settings menu under "Popup/icons behaviour", by deleting the shortcut (the text), here:
> 
> ![image](https://user-images.githubusercontent.com/532708/116575508-9d5dcc00-a906-11eb-90eb-b98969840491.png)
> 
> My reply in issue #233 ([this reply](https://github.com/CanisLupus/swift-selection-search/issues/233#issuecomment-829339301)) contains a brief history of why it's like this (not very good reasons, to be honest 😅). Sorry for the inconvenience!
> 
> Please let me know if this fixes the problem. If not I have to dig a bit more. :)

The workaround you provided is very detailed and the problem has been solved. thank you very much.

**Comment by CanisLupus** [comment]
@operammm Nice! Glad I could help! :) I'll close this issue since #233 already tracks the problem.

@Gitoffthelawn Maybe! I'd have to investigate. Ideally, we'd remove the settings, make sure any other text in the page related to this is up to date, and check that you can do what you need from Firefox's menu and that no functionality was lost.

I'm a bit concerned that there's no option to return the shortcut to the default value in the browser menu. I feel like I'm missing something obvious.

**Comment by Gitoffthelawn** [comment]
> @Gitoffthelawn Maybe! I'd have to investigate. Ideally, we'd remove the settings, make sure any other text in the page related to this is up to date, and check that you can do what you need from Firefox's menu and that no functionality was lost.

AFAIK, no functionality is lost except...

> I'm a bit concerned that there's no option to return the shortcut to the default value in the browser menu. I feel like I'm missing something obvious.

Yep, that seems to be what's lost.  I'm surprised Firefox doesn't have a "reset" button for keyboard shortcuts like they do for settings in `about:config`.

I suppose one option is to include text on the SSS Settings page (is that the SSSS page?) that simply states the default keyboard shortcuts and that they can be changed via the appropriate page in `about:addons`.

**Comment by CanisLupus** [comment]
> I'm surprised Firefox doesn't have a "reset" button for keyboard shortcuts like they do for settings in `about:config`.

I'm surprised as well. It seems essential, especially seeing how easy it is to delete shortcuts in that menu.

> I suppose one option is to include text on the SSS Settings page (is that the SSSS page?) that simply states the default keyboard shortcuts and that they can be changed via the appropriate page in `about:addons`.

Indeed, that looks like the best option right now. :) The shortcut options could be replaced with some kind of text, even if only to cover the case of existing users going there looking for the options that existed before.

I see this shortcut menu issue as a bug, since SSS doesn't see the changes to shortcuts happening there (though it's probably powerless to do so) and it's not obvious to users, so I feel it should be fixed in some way. I'll take a look when possible!

**Comment by CanisLupus** [comment]
SSS updated! Just leaving this here :) https://github.com/CanisLupus/swift-selection-search/issues/233#issuecomment-1233273449
