### ISSUE TITLE
{searchTerms} help

### ISSUE THREAD

**Issue by Andy2kk** [CanisLupus/swift-selection-search#257]
Hello,

I'd appreciate some advice on this.

I am attempting to fix a search engine that was working and suddenly stopped. I wanted ask if having the {} symbols in the search text would make {searchTerms} not work? 

The normal link is (edited)
,"orderIds":["5193138763"]},"orCriteria":{},"pageCriteria":{"page":1,"size":25}}&savedSearchName=

The one I'm using and doesn't work,
,"orderIds":["{searchTerms}"]},"orCriteria":{},"pageCriteria":{"page":1,"size":25}}&savedSearchName=

**Comment by CanisLupus** [comment]
Hi! Having `{}` should cause no problem with `{searchTerms}`. If you try that on Google, for example, you should see `{}` will be part of the search, plus the selected text replacing `{searchTerms}`.

SSS hasn't been updated in a while and you mentioned that this search engine suddenly stopped working, so if it was working before it must be that something else changed, maybe in the website/thingy you are using. :)

If you want you can provide the full link you are using so that I can take a look.
