### ISSUE TITLE
Doesn't work in Bugzilla

### ISSUE THREAD

**Issue by pintassilgo** [CanisLupus/swift-selection-search#27]
Example:
https://bugzilla.mozilla.org/show_bug.cgi?id=1346499

Select some text from page.

The popup will show up empty.

**Comment by OdinGitDat** [comment]
can confirm

**Comment by CanisLupus** [comment]
First of all, apologies for my long silence. I've been checking (again) how to port SSS to WebExtensions and I'm afraid that most issues and suggestions will have to be postponed to after this port becomes possible (as it stands it still can't exist without crippling some SSS features).

As for the bug in question, I can also confirm the issue on bugzilla. It seems the popup icons are blocked from showing on that page. Thank you both for your report! :)

**Comment by T-Halen** [comment]
While the popup seems to populate correctly for me on Bugzilla, I'm having trouble with it on Facebook, and IMDbPro.
https://pro.imdb.com/
https://www.facebook.com/

**Comment by CanisLupus** [comment]
@T-Halen, can you tell me if SSS still fails for you in pro.imdb.com and Facebook with the current version? (3.0.0 or higher) It seems to work well for me. :)

Bugzilla is still not working, however. It can only display icons of engines that are resource:// links (only some imported browser engines should be), which is funny, seeing that Firefox 57.0b13 seems to be _unable_ to display those anywhere, unless they are resource links from the extension itself and not Firefox (so imported engines with resource:// links are currently blank on 57).

bugzilla.mozilla.org seems to have a strict content policy which blocks images that don't belong to the site. This error shows up in the console opening the link given by pintassilgo above:

Content Security Policy: The page’s settings blocked the loading of a resource at data:image/png;base64,iVBORw0KGgoAAAANSU... (“img-src https://bugzilla.mozilla.org https://secure.gravatar.com https://bug1346499.bmoattachments.org/”).

**Comment by T-Halen** [comment]
I think the IMDbPro and Facebook issues were temporary. They work fine at the moment.  I'm also not seeing an issue with Bugzilla.

However, SSS has never seemed to work for the webmail site I use:
https://webmail.core.com/src/login.php
Thanks.

**Comment by pintassilgo** [comment]
Yep, this bug isn't SSS fault.

`security.csp.enable = true` fix it, but I would not recommend doing this.

**Comment by CanisLupus** [comment]
I'm surprised that Bugzilla works for you, T-Halen. :) For me the popup becomes a mess of white space with only a few icons. And I'm also surprised that https://webmail.core.com/src/login.php doesn't work for you, since it works for me (every icon shows) on the login page. Does it not open the popup? Or is it just the icons that don't appear? Is it when you edit an email? Because selecting text in editable fields is currently unsupported and a highly requested feature, but I'll work on that later.

Yes, I can confirm that changing security.csp.enable to false in about:config does the trick for bugzilla, but it's better to not go there as a solution. :)

**Comment by T-Halen** [comment]
> I'm surprised that Bugzilla works for you, T-Halen. :) For me the popup becomes a mess of white space with only a few icons. And I'm also surprised that https://webmail.core.com/src/login.php doesn't work for you, since it works for me (every icon shows) on the login page. Does it not open the popup? Or is it just the icons that don't appear? Is it when you edit an email?

For me, the popup works just fine on the Bugzilla page in the first post.
The popup was not working for me on the webmail login page when I posted, but it is now.  However, the popup doesn't work (open) at all when I'm logged in.  Just text on the screen (not an input box) when reading a message.  It's never worked there, but the context menu does.  The system is built on SquirrelMail, and another SquirrelMail installation I have access to has the same result, popup doesn't work.

**Comment by grahamperrin** [comment]
## Content security policy (CSP)

I never noticed the behaviour with Swift Selection Search because my initial response to seeing a pop-up, after installing the extension (months ago), was: disable the feature.

Today with the pop-up enabled, for test purposes: 

![2018-05-30 05 59 03](https://user-images.githubusercontent.com/192271/40699978-5c4d37f2-63cf-11e8-9c4d-7a0caf4f735b.png)

Then disabled: 

![2018-05-30 06 00 21](https://user-images.githubusercontent.com/192271/40700022-9195ca28-63cf-11e8-896f-a27c0ddb5082.png)

Waterfox 56.2.0.19 on FreeBSD-CURRENT. 

From [Not all icons show at Hacker News / ycombinator.com in Waterfox · Issue #92 …](https://github.com/CanisLupus/swift-selection-search/issues/92)

> … may be related to issue #27 …

I guess that _part of_ #92 is the **CSP** aspect. 

With [Cookies and HTTP Headers analyser](https://addons.mozilla.org/addon/cookies-and-headers-analyser/) at [Space Is Full of Planets, and Most of Them Don't Even Have Stars | Hacker News](https://news.ycombinator.com/item?id=17177036): 

![2018-05-30 06 53 41](https://user-images.githubusercontent.com/192271/40701616-7efd77ce-63d6-11e8-8233-a6b3708c055a.png)

**Comment by CanisLupus** [comment]
@grahamperrin The CSPs are indeed the culprits in the case of this issue and possibly many other sites where the icons don't appear. :)

Do you have any idea if a site's CSP is "bypassable" by an add-on in any way? For security reasons it probably shouldn't be... But I find it strange that some users can see the icons on those sites and others can't. Well, there's the `security.csp.enable = false` workaround but that shouldn't ever be done, not forgetting that it's user-related either.

**Comment by pintassilgo** [comment]
Working for me now, and I use `security.csp.enable = true`.
![](http://i.imgur.com/qTRh7VC.png)

**Comment by grahamperrin** [comment]
@CanisLupus I might be able to direct you to something, but it'll almost certainly not be the thing that you want for a 'respectable' extension. I'll ping you somehow offline. 

Would you like to change the title of this issue, to distinguish it without focusing on Bugzilla? Keyword CSP, I guess. (If no-one objects …). 

TIA

**Comment by CanisLupus** [comment]
@pintassilgo Interesting, it is working for me now as well... Maybe Firefox changed something in the last few versions so that add-ons work despite the policies...? Hmm... On Firefox 52, for example (I have it installed for tests), several sites including https://news.ycombinator.com and https://bugzilla.mozilla.org don't show most icon images, but on (my) Firefox 60 they all do.

@grahamperrin I probably wouldn't be able to use such a solution. :) Nevertheless, I don't know what it is about, so I'm still curious to know. As for the title, sure, we can change it, but I think this is probably an issue to close soon, judging from the fact that we are seeing the icons on more recent FF versions... or so it seems!

Does the problem on Bugzilla happen for anyone on Firefox 60? (probably some older versions too)

**Comment by pintassilgo** [comment]
Maybe https://bugzilla.mozilla.org/show_bug.cgi?id=1407056

**Comment by CanisLupus** [comment]
That may be it! :)

**Comment by CanisLupus** [comment]
Alright, @pintassilgo thank you very much for linking that issue from Bugzilla. I just installed Firefox 57 and 58 to test this and I can confirm that since 58 the icons seem to show on the popup despite the CSPs on the page. On 57 they still didn't show.

This explains why some of us didn't have the problem; some people were probably on beta/nightly channels.

So I guess this is solved...? :)

**Comment by grahamperrin** [comment]
> … guess this is solved…? :)

Without aiming to reopen this Swift Selection Search issue 27, I'll add a comment on the Waterfox side …
