### ISSUE TITLE
Doesn't work with startpage.com

### ISSUE THREAD

**Issue by OdinGitDat** [CanisLupus/swift-selection-search#28]
When I try to use swift popup menu to perform a search to startpage.com it doesn't work. Instead of the search results I get redirected to the main page of startpage. This is the only search engine it does this with afaik.

**Comment by OdinGitDat** [comment]
It also doesn't work with searx.me. I think it has something to do with the fact that these engines don't have the query in the url.

**Comment by CanisLupus** [comment]
Again (if you've seen the other issue :)), apologies for the long delay!

I can confirm the problem with searx.me, which is odd, considering that the engine uses the query in the URL (for example: https://searx.me/?q=webextensions&categories=general) but hides it by default when searching from Firefox.

Unfortunately (or fortunately :p) I had no problem using startpage.com with SSS. Could you tell me from where you added the search engine to Firefox?

Thanks for the report! :)

**Comment by OdinGitDat** [comment]
I just tried all of these:
https://addons.mozilla.org/en-US/firefox/addon/startpage/
https://addons.mozilla.org/en-US/firefox/addon/startpage-ssl/
https://addons.mozilla.org/en-US/firefox/addon/startpage-privacy-search-engin/
https://addons.mozilla.org/en-US/firefox/addon/startpage-https-privacy-search/
https://addons.mozilla.org/en-US/firefox/addon/startpage-fr/

But only the last one worked. Too bad it is french only so I can't use that one.

**Comment by CanisLupus** [comment]
Just an update.

I fear that I don't have much to say about this at this point, though I can confirm that only the last one works, as you reported.

I've been waiting for the search engines API to be implemented for WebExtensions, so that I can fully (or almost fully) port SSS and then check all other issues, such as this one, if they still happen there.

I apologize for the long lack of updates that results from this. At this point it doesn't make sense for me to update SSS in the deprecated SDK. SDK extensions are even already marked as "Legacy" in my Firefox (55 beta).

It seems Firefox is slowly progressing towards having that search API for WebExtensions, but there's still no documentation for it, so it may take a while.

- Daniel

**Comment by OdinGitDat** [comment]
fixed with the new WE version!

**Comment by CanisLupus** [comment]
Glad to know! :) Thanks for reporting. I'll still try to see what was causing this when I can, just to be sure it won't happen elsewhere.
