### ISSUE TITLE
Suggestion: Pop up menu when editable text is selected

### ISSUE THREAD

**Issue by aa3993** [CanisLupus/swift-selection-search#33]

**Comment by jdreesen** [comment]
This would be awesome! Currently I have to use the context menu for this.

**Comment by CanisLupus** [comment]
I've experimented with this a bit and wanted to ask you: what do you expect of this feature-to-be?

If it pops up whenever text is selected in a text input field I personally find it annoying, since it pops up after selecting text in Google's search field or when I'm editing an email in web Gmail, but it can be done. This functionality would be optional anyway, of course. ;)

I'm thinking of extending the Ctrl/Cmd+Shift+Space shortcut to make the popup appear even in input fields (it doesn't have any obvious cons since when you press the shortcut you _want_ it to appear). This probably won't feel any better than using the context menu, but it isn't annoying either.

Did you have other ideas in mind?

Cheers!

**Comment by Taurean75** [comment]
I would be contend with the current popup scheme as long as its CSS can be manipulated.  Personally, I find having to press shortcuts more annoying.

**Comment by aa3993** [comment]
Making it popup as an optional feature would work best I think.

**Comment by Taurean75** [comment]
Instead of shortcuts, how about a toolbar button?

**Comment by CanisLupus** [comment]
OK, I added this in the just-submitted version 3.6.0. You can now activate an option that lets the popup appear for editable fields (login forms, search bars, email composing windows, etc). The keyboard shortcut now also supports editable fields (it works even without the option I mentioned). :)

I think the toolbar button including the popup engines may be a good idea, but it is perhaps too similar to the context menu (which already works for editable fields) and would be less convenient than selection-based actions, I think.

I'm curious to know what you think of the support for editable fields. I mentioned that I find it annoying so I'll personally be leaving it off. I'm thinking that maybe keyboard selections (like shift left/right) shouldn't trigger the popup. In either case, maybe some things aren't working as you all wished, so I'll leave this open until I get feedback from you.

Cheers!

**Comment by Teko101** [comment]
You are the whole package bro :)
In my opinion SSS is actually the best search extension ever. 
I'll literally remove four of my addons after implementing "Current Site Search" feature. Issue #35 

As for the new option (editable fields popup): 
1- Would you please allow the popup, only if the selection made by mouse ?
Currently, If you try to select something using "Ctrl+A" or "Shift+Arrow" , SSS will show the popup menu.

2- The popup appears farther than it should from the the mouse arrow (out of the editable field box).

Regards :)

**Comment by CanisLupus** [comment]
Haha thanks! :D "Best search extension ever" sounds awesome. ;) Current Site Search will definitely be investigated after some other pending things.

Due to general agreement, version 3.6.1 disables the popup for keyboard selections in editable fields.

As for it appearing further away, that is true. It should only happen when the popup location option is set to the selection rectangle and not the cursor position. Unfortunately, I couldn't find a way to get the bounds of the selection inside an input field in JavaScript. Normally, the selection object gives me that, but for input fields there doesn't seem to be one, so I defaulted the position to the bottom right corner of the input field itself.

**I'll gladly accept any insight on this JS problem**, by the way. I'm leaving this issue open until I either fix it or create a new one just for this problem.

Cheers! :)
