### ISSUE TITLE
Suggestion: Popup when holding key combination

### ISSUE THREAD

**Issue by mpenguin** [CanisLupus/swift-selection-search#34]
Before using SSS, I was using another Addon (I forget which one) that had the option to only popup the menu when you held a key/key combination AND THEN highlighted text. So I might hold down the CTRL key, highlight text, and get the popup, whereas just highlighting text wouldn't.

This is similar to the option you have where you highlight the text first and then hit the key combination, but I find my suggestion to be more natural (the popup is the result of highlighting the text, not the result of the key combination).

Thanks! Glad to see you'll be converting it to a WebExtension!

**Comment by CanisLupus** [comment]
Hi there! Thank you for the suggestion. :) I see why some people would prefer that approach for selection, so it will definitely be considered later.

Last time I checked, WebExtensions didn't seem to let the _user_ specify keyboard shortcuts (they had to be set in stone in the add-on itself). My fear is that setting keys without the user being able to change them can cause incompatibilities with other add-ons or browser functions in some cases. In this case, the Ctrl key is apparently used in Firefox to be able to select multiple things (never knew that!). That said, just holding Ctrl to make the popup appear shouldn't be too bad, especially since that wouldn't be the default behaviour.

As you mentioned, I'm slowly working toward making SSS a WebExtension, as far as it has been made possible. :) That just means that all other issues, including this one, are considered non-critical until that is out of the way. But I will look into this later (no ETA, sorry!).

Cheers!
Daniel

**Comment by CanisLupus** [comment]
Well it took a long time for me to get back to your suggestion, @mpenguin!

Version 3.12.0 now has a new "Opening behaviour" that only opens the popup if you use Alt (Option on Mac) while selecting text. The reason for it being Alt and not Ctrl is because Ctrl is already used by Firefox to create multiple text selections and Alt seems to not cause evident problems (that I could see :p).

If you are using SSS, please do try this out. :) I'll be closing this issue but feel free to comment here and even reopen it if something is wrong.

Cheers!
Daniel
