### ISSUE TITLE
Suggestion: Current site search!

### ISSUE THREAD

**Issue by Teko101** [CanisLupus/swift-selection-search#35]
Hi Daniel,

If I may ask, would you implement an option (in the Pop-Up Menu) for searching the current site using google.
I mean, assume that you are on "www.example.com", then search term (in Google) would be: 
"SelectedWord(s) Site:example.com"

Also about Issue #33 , would you please take a look at it? 
some other extension (Selected Search I think) has that option of Popping-Up the menu if an editable text is selected, even from the Firefox search bar... It would be great if you could add that option.

Thank a lot Daniel for your time, and I'm really glad you figured out how to decode/read the search.json.mozlz4 file.

Cheers!

**Comment by CanisLupus** [comment]
Hello,

Suggestion noted. :) Issue 33 was also requested several times. I just didn't comment there because I answered the poster on another of his/her issues.

I'm also relieved to have been able to read the engines file. Thank you for the original suggestion! :)

Now I'm battling Firefox bugs on the add-on settings page from version 56 onward, such as dropdowns being completely off-place after scrolling the page, and dragging features not working at all (I was using those to reorder the engines). Firefox 57 doesn't fix this either. *sigh* There are still some other things not working as they should, but it's coming along.

Daniel

**Comment by Gitoffthelawn** [comment]
Naturally, allow the user to choose which search engine to use. :)

**Comment by Remonli** [comment]
Looking forward this very important feature

**Comment by CanisLupus** [comment]
Hey folks, I just submitted a new feature in v3.11.1 for this! I added support for a variable {hostname} that you can use in any search engine's URL. When clicking the engine (popup or context menu), {hostname} gets replaced by the domain of the website you are on, which allows engines like:

https://www.google.com/search?q={searchTerms} site:{hostname}

So please tell me if this is what you were expecting and if it is working well and I'll close this. :) It was really easy to add, too, which is always delightful. ;)

**Comment by Remonli** [comment]
Works well, thank you for great work!

**Comment by Taurean75** [comment]
@CanisLupus, I don't understand the concept. I've probably never searched that way. 

Would someone elaborate on this feature?

**Comment by Teko101** [comment]
Well, that really made my day :) It works flawlessly ! 
Thanks a lot Daniel for your incomparable work, I really appreciate it.

**Comment by CanisLupus** [comment]
Thanks! :D You're welcome! As always, if any problem comes up related to this, please re-open this issue or create a new one. Cheers!
