### ISSUE TITLE
Google popup of f.txt when searching

### ISSUE THREAD

**Issue by T-Halen** [CanisLupus/swift-selection-search#36]
SSS updated today for me to the WebExtensions version.  So far, pretty good.  Currently having trouble with Google though.

The search looks like this:
https://www.google.com/search?q={searchTerms}

But when clicked, I get the reults page I expect, and a Firefox "save-as" popup asking me where to save a small text file called 'f.txt' - which contains stuff relevent to what I searched for.  For example, if I highlight the word 'leads' and search Google for it, the file contains:
["leads",["leads","leads online","leads definition","leadslingers whiskey","leads synonym","leadstreet","leads meaning","leadscon","leads steers","leadslingers"]]

Any ideas?  Thanks again for all the time spent updating this!!

**Comment by T-Halen** [comment]
More info.  I have the settings saved for "open in new tab" when clicked (left mouse).  The tab opens only momentarily with my results, and then closes, and I'm presented with the save-as dialog.

**Comment by CanisLupus** [comment]
Hi! :) Well, I must say that that specific URL does not give me an f.txt file (not even in a clean Firefox install without other extensions), but someone on StackOverflow has [an explanation for the f.txt file](https://stackoverflow.com/questions/28535603/google-chrome-forcing-download-of-f-txt-file). It seems to be the way some sites protected themselves against an exploit on Adobe Flash (f.txt is the way Google named it themselves).

I remember having this issue when using Google normally a few years back, but I don't use Flash anymore. Do you have it installed? Could you try disabling it and seeing if that helps?

By the way, I do get files as pages when using some browser-imported engines, like amazon.com and yahoo.com, so I'll have to check that (it's not the same issue because in my case the txt file _is_ the page; it does not appear _in addition_ to the page).

**Comment by T-Halen** [comment]
Hmm, so far no luck.  Disabled flash, even uninstalled it, no change.
Disabled all plugins and extensions (except SSS) and no change.
Read a bunch of Google results on it, but still haven't come up with an explanation.

Only other thing I can think of right now is that FF auto-upgraded from 32b to 64b around the same time as the SSS plugin was updated. As far as I'm concerned the problem started with the change to WebExtensions version of SSS, but there must be something else going on.

**Comment by jdreesen** [comment]
I imported the search engines from the file in my browser profile folder and experience the same problem for google (and some others). 

The imported URL is: https://www.google.com/complete/search?client=firefox&q={searchTerms}

The default SSS google entry works, though - but only if they are not both named "Google". If both have the same name the imported one seems to win (even if it is disabled/unchecked) and I get the `f.txt` file download when searching with either of the entries. Sadly it's not possible to rename or delete the imported one at the moment, so I have to go with another name for the default one.

**Comment by T-Halen** [comment]
Thanks jdreesen.  Renaming my entry for Google to "Google1", has worked.  Looks a little funny in the context menu, but works just fine.  Must be some weird internal collision in the entries even though the one is unchecked.

**Comment by CanisLupus** [comment]
Hmm the name collision definitely looks like a bug! I have to leave for today but tomorrow I'll try to check that. Thanks for all the issue reports!

**Comment by CanisLupus** [comment]
OK, 2 things:

1. I fixed the bug that caused engines with the same name to conflict with each other. It should work fine in version 3.2.0, which I've just submitted to the add-ons market.
2. As Gitoffthelawn reported in issue #40, I was also using the wrong URLs when importing the browser engines! I used the autocomplete URLs, which are meant to suggest things as you write and not for searches themselves. This resulted in some odd behaviour, namely the "files as pages" I was seeing.

Point 1 may have aggravated point 2, causing an engine that appeared first in the list to get priority over others with the same name even if it was using the wrong autocomplete links.

This is all fixed in 3.2.0, I believe (though you'll have to reimport search.json.mozlz4. Sorry!).

@T-Halen, if you are able to check that version later, please tell me if you can still reproduce the problem even with 2 "Google"s. :) Or 3, or 4... :p

**Comment by T-Halen** [comment]
I upgraded to 3.2.0 this morning.  No real change with the f.txt issue, but I can now delete the imported entry that was causing the problem.

**Comment by CanisLupus** [comment]
I see... Unfortunately I have no other ideas for now. I wish I could reproduce this with some engine. Maybe someone else will give us a hint in the future.

**Comment by Taurean75** [comment]
I was having the same issue as jdreesen.  Just had to add it myself.

**Comment by CanisLupus** [comment]
Hey, I was checking back on a few issues from a long while ago. Has this ever happened again, @T-Halen? Or to someone else?

It was never clear what the problem was here, at least after the (now very old) update to version 3.2.0. I was thinking to close this issue but wanted to hear from you first.

Cheers!

**Comment by T-Halen** [comment]
No trouble for me since it was fixed.

**Comment by CanisLupus** [comment]
Thanks for replying. I'll be closing this until (if) something comes up. Cheers!
