### ISSUE TITLE
Export Functionality 

### ISSUE THREAD

**Issue by Taurean75** [CanisLupus/swift-selection-search#41]
People add an export functionality for saving settings and search engines. Thanks!

**Comment by CanisLupus** [comment]
Hello! This is planned, maybe using Firefox Sync. :) Still have to decide on a solution for the 100KB limit imposed on add-ons.

If it makes sense I may also add a non-Sync based solution (simply exporting a file with all settings).

**Comment by CanisLupus** [comment]
I'll keep this issue open until it's done, ok? Although it's planned, I'll still come here and update this when it gets done, so you get notified.

**Comment by Taurean75** [comment]
Sure.

**Comment by CanisLupus** [comment]
As I mentioned in your other issue about the icons, version 3.8.0 has export/import now! :)

Firefox Sync is a different story. I was able to use it easily and save/load to/from sync in the same Firefox install, but somehow it seems to not be uploading, because on another install I can't seem to download anything (it comes empty).

I don't think there's a way to check if it is actually uploading anything. I simply write in the sync storage, and Firefox uploads that from time to time (or by user request). So there's no error writing whatsoever, but it can still not upload and I can't know.

Will need to check.

**Comment by Taurean75** [comment]
We can close this now.

**Comment by CanisLupus** [comment]
Sure! Sync is something I'll have to try again in time.

**Comment by Taurean75** [comment]
As for sync, why not copy the code from other extensions -- such as uBlock -- that support it?

**Comment by CanisLupus** [comment]
Because other extensions' code will invariably be different than my own's, which is also the case with uBlock. :)

I have sync code implemented for SSS, as well as buttons to upload and download it on demand, but for some reason it was not syncing across to other instances of the browser (nor other computers), so I left it and decided to get back to it later. It's probably my mistake but I haven't checked again yet.

**Comment by Taurean75** [comment]
I didn't mean you to copy it as it is; I meant to study and incorporate it. Of course it's not going to work with your extension unless Mozilla provided it as an API package.

Anyway, thanks for your efforts!

**Comment by CanisLupus** [comment]
Sorry, yes, that's what I'll do if it keeps not syncing. You're welcome! :) Cheers!
