### ISSUE TITLE
Totally Stopped (V 3.4.0)

### ISSUE THREAD

**Issue by Teko101** [CanisLupus/swift-selection-search#45]
Hi Daniel,
It's good to see how fast SSS getting better :)
However, after updating to version 3.4.0 , SSS stopped working!

Right after the update (w/o restarting FF), I couldn't find SSS entry in the context menu, so I restarted FF and found that the popup wasn't working too :(
I tried to disable all of my addons one by one, but unfortunately that didn't help.

BTW I'm still on FF 55.0.3 hoping/waiting for a WE version for my other extensions .
*SSS 3.3.0 is working perfectly.

**Comment by jdreesen** [comment]
I just updated to SSS 3.4.0 and it works like it should on my side.
I'm on FF 56.0.2 (64 bit).

**Comment by CanisLupus** [comment]
Hi Teko101, sorry to hear you're having problems. Like jdreesen I'm also on 56.0.2 and everything seems to work with SSS 3.4.0 on my end. Legacy extensions still work on 56. I have a few and hope that they get updated. :\

I wonder what is causing these issues that I'm unable to reproduce. Can you see SSS in the addons menu? (about:addons) If so, do the settings seem okay to you? Neither the popup nor the context menu appear at all?

I can suggest removing SSS, restarting Firefox, and then trying to install SSS from the market again. However, since SSS doesn't have an export/sync feature yet, you would have to re-add everything and I don't want that.

**Comment by theorist-complex** [comment]
Using Waterfox 55.2.2 and can also confirm that after updating to 3.4.0, SSS has completely stopped working. No sign of the extension even being installed at all. Context menu option gone, no popup, no shortcut keybinds working.

I have tried uninstalling & reinstalling with multi-process enabled & disabled, resetting, etc. Nothing makes a difference.

Also, doubt this matters, but just to be thorough, the latest update/updates(?) right before 3.4.0 generally worked, BUT they seemed to break the popup on specific websites that HAD worked prior.

**Comment by CanisLupus** [comment]
Thank you for the additional report, theorist-complex. This issue is particularly critical but I can't reproduce it...

I went through my last code changes again and found something in 3.4.0 that could cause an error in certain circumstances, possibly blocking the context menus from working. None of that should block the extension from installing, though! That is really weird, even if it's not really standard Firefox in your case.

I've submitted the "fix" to the market as 3.4.1 but I'm not at all confident that this was the issue. Maybe the option to export all settings to a file will have to be done sooner so I can request info when something fails. And possibly a debug mode. :\

**Comment by Teko101** [comment]
Thanks Daniel for your reply...

Yes, I can see SSS in the addons menu, and settings looks okay too.

What I noticed after trying the extensions suggested here: https://github.com/CanisLupus/swift-selection-search/issues/39#issuecomment-340276786 that the context search icons didn't work using any of them!
So it might be a firefox bug or something (Not sure).

As for SSS (3.4.0 & 3.4.1), the popup works properly , after disabling "context menu" .
* Same result after removing SSS and reinstalling it.

(The only reason I didn't update to FF 56.* , is I couldn't find a replacement for this extension that shouldn't even have to be needed! : 
https://addons.mozilla.org/en-US/firefox/addon/add-bookmark-here-2/ )

Anyway, If no one else reported about this problem, then you can just forget about it and focus on your other SSS stuff..

Actually SSS became INDISPENSABLE So, after all I think I'm gonna have to update my FF.

**Comment by theorist-complex** [comment]
Well, I updated to 3.4.1 and was nearly ready to proclaim that it too was completely broken (for me) - and then Teko101 just commented again and I saw where he said that disabling the context menu in SSS causes his popup to work. So I did the same, disabling the context menu in SSS and sure enough, my popup works again and all settings except those pertaining to the context menu seem to work fine. 

BUT - I seem to still have the issue where the popup still refuses to work on certain websites - though in general, aside from that and the context menu thing, SSS seems to be working again.

**Comment by CanisLupus** [comment]
Thanks for the additional info! I'm now 99% sure of what the problem is, but may only be able to update this later today.

It's the context menu icons I introduced in 3.3.0. I was under the impression that they were not supported in WebExtensions, and truth is they probably weren't until very recently. I added the feature without checking older versions like Firefox 55, where they probably simply weren't supported yet. When you have an unsupported field like "icons", instead of ignoring it Firefox will throw an error. In this case, that stops the context menu and subsequent things from being setup, hence the problems you were seeing.

Sorry! Will check this as soon as possible.

Daniel

**Comment by CanisLupus** [comment]
PS: @theorist-complex can you please create a new issue with links to one or a few pages where the popup doesn't work? I may take a look at that afterwards.

**Comment by CanisLupus** [comment]
I can confirm that that was exactly it. :) Using WebExtensions, only Firefox 56 and newer support context menu icons on sub-options (in this case the engines), so my update broke older versions. Again, I'm sorry for that.

I submitted 3.4.2 to the market, which should fix this. Please confirm. Thanks to everyone for reporting!

**Comment by Teko101** [comment]
Confirmed ! SSS back to work :)

**Comment by theorist-complex** [comment]
@CanisLupus Yeah, sure thing, I can do that. Will have to be a bit later on today though, possibly even early evening. Sorry about that.

**Comment by CanisLupus** [comment]
Awesome!

Sure, theorist-complex, no worries. Whenever you can. :) Thanks!

**Comment by theorist-complex** [comment]
SSS 3.4.2 confirmed working on Waterfox 55.2.2
