### ISSUE TITLE
Open as link does not work for most several-word selections

### ISSUE THREAD

**Issue by Homme-Nuage** [CanisLupus/swift-selection-search#49]
Hello,

As you requested, I'm posting my problem here.  I think I've figured it out.

It works for single words and hyphened terms (e.g. African-American), but not for words separated by spaces (e.g. Swift Selection Search) or by the sign : (e.g. about:config). 

By the way, I can confirm that your extension no longer duplicates search engines.

Thanks.

**Comment by CanisLupus** [comment]
Hey! Thanks for the examples, that helps a lot. :) (and thanks for confirming that duplicates are not a problem anymore!)

In your opinion, what should happen when you try to open text with spaces as a link? I guess I neglected that use-case, since spaces are unsafe in URLs according to the spec (they are generally replaced with %20 or sometimes the + character). I can replace them with %20 so that at least the URL tries to open instead of nothing happening.

about:config is a good point. Maybe colons should be handled differently, though they are also used for ports (like localhost:8000).

I'll look into this. Cheers!

Daniel

**Comment by Homme-Nuage** [comment]
Well, I've never had to open a text with spaces as a link... but the impossibility to do so led me to believe the functionality didn't work at all.

There is about:config (whose preferences can be accessed directly with about:config?filter=Preference) as well as about:addons, about:performance, etc. 

Thank you for your answer.

**Comment by CanisLupus** [comment]
Alright, it was a relatively quick fix, so the new version 3.7.0 now at least tries to open the URL if there are spaces. ;) I should note that they're not unsafe from a security point of view; they're just unsafe to use in URLs because they are error prone (ex.: if one leaves a space at the end of a URL by mistake, should it be considered "relevant"?), so the spec considers spaces invalid if not changed to %20 or similar.

Fixing this actually fixed some other characters that would cause URLs to not open. I hadn't noticed this, so thanks!

As for about:<something> links, I checked and Firefox itself forbids it, unfortunately. For reference, this is the link that explains it:

https://developer.mozilla.org/Add-ons/WebExtensions/API/tabs/create

Quoting:
> For security reasons, in Firefox, [the url property] may not be a privileged URL. So passing any of the following URLs will fail:
>
> - chrome: URLs
> - javascript: URLs
> - data: URLs
> - file: URLs (i.e., files on the filesystem. However, to use a file packaged inside the extension, see below)
> - **privileged about: URLs (for example, about:config, about:addons, about:debugging).** Non-privileged URLs (e.g., about:blank) are allowed.
> - The New Tab page (about:newtab) can be opened if no value for URL is provided.
(emphasis mine)

Cheers!
Daniel

**Comment by Homme-Nuage** [comment]
Ok. Well, thank you for your reactivity.
