### ISSUE TITLE
Allow user to add an icon to open highlighted URL

### ISSUE THREAD

**Issue by Gitoffthelawn** [CanisLupus/swift-selection-search#5]
Sometimes a web page contains a URL that is not "hyperlinked"; in other words, it's just text.

It would be nice to have an option to allow the user to create an icon that, when clicked, opens the URL.

Ideally, the user could create either or both of the following icons:
1. Open in current tab
2. Open in new tab

**Comment by CanisLupus** [comment]
Like I mentioned in issue #6, version 2.13.3 contains an optional icon to open the selected text as if it were a link (i.e. no search on any engine; just assumes the selected text is a useful URL and tries to open it).

I decided to keep it as a single icon, because all icons already respect the differences between left mouse click and middle mouse click (middle opens in a new tab, though this is configurable in SSS), so you can open the URL as desired at the time. :)

Will be closing this too, but, as usual, feel free to comment or suggest things!

**Comment by Gitoffthelawn** [comment]
Thanks again! :)

**Comment by Gitoffthelawn** [comment]
This is working great... except when the URL is not prefaced with a protocol (http/https/etc.).

For example, the first 3 examples on this page will work, but the last 3 will not:
https://github.com/Gitoffthelawn/HTMLtest

Should be an easy fix. :)

**Comment by CanisLupus** [comment]
Indeed... Nice catch. Does it open a "resource://jid1-kdtticj6wxvafa-at-jetpack/data/www.example.com" kind of url for you? It does for me on Firefox 50, but I'm almost sure I've tested it before on a previous version (47?) and it worked.

What I do is simply set the url as the selected text. If it's something the browser considers a valid url, it opens the page, otherwise it will probably search using the default search engine. At least that was the idea. :)

Will definitely look into this when I'm able to work on SSS for a bit. Thanks!

**Comment by Gitoffthelawn** [comment]
Yep, that's what it does.  Thanks for looking into it! :)
