### ISSUE TITLE
eBay Favicon

### ISSUE THREAD

**Issue by Taurean75** [CanisLupus/swift-selection-search#50]
Hello --

I've tried...
https://www.ebay.com/favicon.ico
https://my.ebay.com/favicon.ico
https://pages.ebay.com/favicon.ico

But it doesn't show up on popup and settings page.

Advise please.

**Comment by Mattwmaster58** [comment]
I've tried every link, and they all work perfectly for me. Are you sure you are putting them in the icon link input?

Make sure you're on the latest version.

**Comment by Taurean75** [comment]
Yes, I am.

See...
![ebay](https://user-images.githubusercontent.com/8365855/32641408-94e4eb00-c582-11e7-8147-8631a1fce7b9.PNG)

**Comment by Mattwmaster58** [comment]
Does this issue occur on a fresh install?

**Comment by Taurean75** [comment]
It was working fine when I imported it from default engines but not after I manually added it.

On well.  I'll wait until I can export my settings since I've manually added over 12 sites..

**Comment by Mattwmaster58** [comment]
In the meantime you could try and reproduce it with a completely new profile.

**Comment by Taurean75** [comment]
Oddly, other icons work just fine.

**Comment by CanisLupus** [comment]
Thanks @Mattwmaster58 for the help!

@Taurean75, I was able to add and use all those icons successfully, though it did take a few seconds to get the first one. Can you tell me which Firefox version are you using? It may be unrelated, but this way I can try it out. This is odd. It may also have been a network problem (of several possible kinds). Is it still not working today?

Cheers!

**Comment by Taurean75** [comment]
@CanisLupus, it's still not working. So I substituted it with https://i.imgur.com/cb4pKZu.png

I'm using FF v56.02 x64 was SSS 3.63.

**Comment by Taurean75** [comment]
And others are working fine...
![settings](https://user-images.githubusercontent.com/8365855/32675019-3e131c56-c60a-11e7-80d2-d7c7bdf74b74.PNG)

**Comment by CanisLupus** [comment]
Hi @Taurean75, unfortunately I'm not sure what is going on here. :( I was using the same SSS and Firefox version as you are (I have updated SSS just now), so that's not the issue.

That said, I fixed an icon caching bug in version 3.7.0. It shouldn't be related to your problem but something might have caused the caching of an empty URL for those eBay icons (never saw that happen, though).

**Comment by Taurean75** [comment]
@CanisLupus, that's ok... I can just use substitutes.

**Comment by Remonli** [comment]
Still has problem with eBay favicon , SSS 3.81 on Firefox 58 beta 3 , Win10.

**Comment by Taurean75** [comment]
@Remonli, just use https://i.imgur.com/klLBu1n.png

**Comment by Remonli** [comment]
@Taurean75  @CanisLupus
Ok,thank you.

**Comment by CanisLupus** [comment]
Sorry for the delay, @Remonli, and thanks for the aid, @Taurean75. :)

In issue #52 we found that some plugins can cause some icons to fail to cache, so they appear in the options page but not in the popup. I don't know if this is that case, but the eBay icons work for me and for Mattwmaster58, so it's possible. For Taurean75 the culprit was "Fanboy's Annoyance / Social Blocking Lists" in uBlock Origin.

(By the way, @Taurean75, did you try adding the eBay icons after disabling that list in uBO?)

**Comment by Taurean75** [comment]
@CanisLupus, I tried it just now, and it comes up as broken even within the settings page; i.e., there's a placeholder with no icon. I'm thinking it could be my firewall Kaspersky that's blocking it. Just turning it off doesn't help. Don't want to uninstall that, though.

**Comment by Taurean75** [comment]
"Fanboy's Annoyance / Social Blocking Lists" were blocking only YouTube placeholder by the way, not eBay.
