### ISSUE TITLE
YouTube Disappeared from Popup

### ISSUE THREAD

**Issue by Taurean75** [CanisLupus/swift-selection-search#52]
Even though it's checked in the settings page, it doesn't appear on popup.  This started from v3.7.
![yt](https://user-images.githubusercontent.com/8365855/32702222-836c6994-c798-11e7-8123-274f548757d6.PNG)

![popup](https://user-images.githubusercontent.com/8365855/32702243-c54de11c-c798-11e7-8109-445c3dada90e.PNG)

I've tried re-add it, but that didn't help.

I'm using Firefox 57 x64.

**Comment by CanisLupus** [comment]
Sorry that you are encountering so many issues with the icons! I suspect this has something to do with icon caching, but I've not found the cause yet.

The fact that the YT icon appears on the options page but not on GitHub is likely because the icon was not cached by SSS, or was somehow cached wrongly. If that happens I let it fall back to use its URL directly (https://www.youtube.com/favicon.ico), but some pages simply block external images, as is the case with GitHub. Can you tell me if some other sites display the icon? If they do, the issue is almost definitely that.

Unfortunately, I can only think of one case that could cause this, which would be to write the icon URL and then leave the page faster than SSS can download and cache the icon (network connectivity issues could allow this). However, you tried re-adding it, so it's unlikely that the problem repeated.

I have a suggestion, though. I uploaded version 3.8.0, which now lets you save your settings+engines to a file and reimport them again. This forces the icon cache to clear itself and re-download the icons, which could fix this.

Please try updating SSS, scrolling to the bottom of the options page (section "Storage & Backup") and exporting everything to a file. Please open the file using any text editor and confirm that your settings and engines are there, just to be sure. Then try importing that same file.

Sorry for the inconvenience, but this is all I got for now!

**Comment by Taurean75** [comment]
@CanisLupus, I meant the search engine button doesn't appear at all on the popup.

**Comment by CanisLupus** [comment]
It doesn't appear on any website?

**Comment by Taurean75** [comment]
Yeah, and resetting it didn't help.

**Comment by CanisLupus** [comment]
Hmm... By resetting do you mean the export and import suggestion? If that didn't work then this isn't a caching issue. :s

I just tried that exact icon URL and it worked normally here. Do you have any add-ons that potentially block URLs? Any uncommon ad blocker?

**Comment by Taurean75** [comment]
Oddly, YouTube doesn't appear at all on the popup even with the default settings.  Export / import, reset settings and reinstall -- yes. Other engines work fine, though.

As for blocker, I only use uBO.

**Comment by Taurean75** [comment]
No YouTube at all...
![popup](https://user-images.githubusercontent.com/8365855/32702243-c54de11c-c798-11e7-8109-445c3dada90e.PNG)

**Comment by CanisLupus** [comment]
Is there any chance that the icon URL has a space or other whitespace character at the end? I was checking the code and found that this could cause caching to fail (it's very easy to fix; it was an oversight!).

**Comment by Taurean75** [comment]
Nope.  If you'd look at the screenshot above, there's no placeholder for YouTube at all even though it's checked in the settings.

**Comment by CanisLupus** [comment]
Yes, I see that. :) The popup in your screenshots has enough width to contain the YT icon but it's simply not there. I've submitted the fix for the whitespace problem, but if it isn't that then I suggest one more thing:

If you don't have any personal information or anything that you which to keep private, could you send me your exported settings file with all the engines? I can take a look at it and perhaps find the problem.

If you'd like it to be private, I understand completely. You can also try deleting every engine that is not YT before exporting it and sending me _that_.

Thanks!

**Comment by Taurean75** [comment]
It's fine in the context menu however.

I'll send it to you.

**Comment by Taurean75** [comment]
Sent.

**Comment by CanisLupus** [comment]
Thank you for sending the file. Unfortunately, there doesn't seem to be anything wrong here. I uninstalled SSS, reinstalled the newest version, imported your file and went to GitHub without changing anything. This was the result:

![screenshot](https://user-images.githubusercontent.com/532708/32704182-fe39783c-c7f8-11e7-93fd-0f6d9d9acb04.PNG)

It's really weird that it fails to show for you.

**Comment by Taurean75** [comment]
Thanks for your help.

I wonder why only YouTube isn't showing.  I now think it's a conflict with another extension.

**Comment by Taurean75** [comment]
Found the extension that's causing this problem. It's uBlock Origin.

**Comment by Taurean75** [comment]
Specifically, Fanboy's Social Blocking List.

**Comment by Taurean75** [comment]
Found the extension that's causing this problem. It's uBlock Origin.

Specifically, Fanboy's Annoyance / Social Blocking Lists.

You'd put a warning message about this on the extensions page.

**Comment by CanisLupus** [comment]
Alright, glad to know that was it. :) I noted down your suggestion for the warning message. I still have to decide what would be a good way to communicate this to the user without cluttering the options page with more text.

Cheers!
