### ISSUE TITLE
SSS dont work when set layout.css.servo.enabled to TRUE

### ISSUE THREAD

**Issue by liuxb** [CanisLupus/swift-selection-search#53]
After I enabled Stylo feature(via layout.css.servo.enabled;true), SSS' menu dont appear anymore.

firefox 56.0 32bit, windows 10 1709 32bit
SSS 3.8.1

**Comment by CanisLupus** [comment]
Hello! You're right, it seems that the popup is appearing at the bottom of the page (most of the time you should be able to see your scroll bar shrinking a bit).

The bad news is that I think this is (actually "was") an issue with the Servo engine. It's pretty much ignoring the formatting of the popup, since I set it via JavaScript instead of pure CSS since SSS version 3.6.0 (fixes another issue with sites blocking custom CSS).

The good news is that they seem to have fixed it. I tried it in Firefox 57 (beta; I think it launches tomorrow officially), where it should be enabled by default, and it works normally. Also works in the current versions of 58 and 59. Please let me know if it works for you when you are able to upgrade. :)

**Comment by CanisLupus** [comment]
Hey, I'm closing this. Let me know if something is wrong in Firefox 57 or newer!
