### ISSUE TITLE
Need help to make a search string!

### ISSUE THREAD

**Issue by rezpower** [CanisLupus/swift-selection-search#54]
First of all I am really sorry to post this here as I know this is not an issue, but a personal help request!
To make things short I have been able to make all my needed search strings like ex: "http://www.larousse.fr/dictionnaires/rechercher?q={searchTerms}&l=francais-anglais&culture=" and all my search strings work perfectly. There is only one site that I can't get to work. Its a PERSIAN Dictionary site. It would be really nice if someone could help me make a working string for it.
The Site address is: https://www.hooshyar.com/
As the site is in Persian (FARSI) I have to explain that naturally the word (query) goes in the search box. Non of the drop down menus need to change, except the first one (Just under the  search box on the right) I will need to be able to choose the first 4 options. (for this I probably need 4 separate strings).
It will be really cool if someone could help me with this.
Thanks in advance :)

**Comment by CanisLupus** [comment]
Hi rezpower! :) Hmm... unless the website lets you use parameters in the URL this might not be possible with SSS. :(

You are trying to create a string for searching that website, but it uses a POST request when you press the form button to submit the data. The content of this search is sent inside the request and not in the URL, so unless the website has another way that lets you create a URL for the search, I'm afraid I can't help, sorry. Maybe someone else has some idea!

Cheers!
Daniel

**Comment by rezpower** [comment]
Hi Daniel,
Thanks a lot for your response. I spent a long time last night trying to get that site to work and thought I was doing something wrong. Also a BIG thanks for this great add-on. It's by far my favorite FF add-0n and I already posted what I think when rating it on mozilla.org. (review by Remy.H)

**Comment by CanisLupus** [comment]
Yeah, I don't think you are doing anything wrong. It's probably just the website. You're welcome! Thanks for the kind words and for the review. It's much appreciated. :)

About your issue/help request, I'll leave this open for a while just so someone may chime in if they know a way. Otherwise I'll close it afterwards. Sorry I couldn't help!

**Comment by CanisLupus** [comment]
Hey, I'm closing this issue, but I added another to-do to my relatively big list about supporting "POST request" engines. It would allow searching these kinds of sites if necessary, but it's probably quite a lot of work. :)

Cheers!

**Comment by youk** [comment]
Hi there @CanisLupus 
I am wondering whether this is possible at all – maybe your research showed something? I have no experience in development of Firefox extensions, but I can do JavaScript programming. If there is any work to do just let me know.

**Comment by CanisLupus** [comment]
Hey youk!

I did no further research about implementing POST-based search engines. It should be possible if the engines were redone to support arguments and post style instead of just simple search URLs. The main problem is making it accessible to users and (greatly) changing the options interface so engines support both GETs and POSTs. :)

Unfortunately, I haven't had much time lately for anything. :( There were a few other things that needed to be done in SSS. I was working on them about two weeks ago but haven't completed them yet.

Cheers!
Daniel
