### ISSUE TITLE
"Copy to clipboard" doesn't work in input fields

### ISSUE THREAD

**Issue by cazssiew** [CanisLupus/swift-selection-search#55]
The "copy to clipboard" button doesn't seem to ~~do anything~~ work in input fields; the previous item stays in the clipboard. (I previously posted that it didn't do anything; restarting the browser seems to have fixed it in most cases, except for input fields as stated above).

(I don't know if this could be of any help, but the "copy text" button in the S3.Translator add-on does work in this use case)

Thanks for the amazing add-on !

**Comment by CanisLupus** [comment]
You're right! Thanks for reporting this. It seems the browser isn't doing anything when `document.execCommand("copy")` is called for input fields (maybe because they don't have a selection object?). It does work for non-input HTML with contentEditable.

I searched around and couldn't find anything about this issue yet. Nothing that says it shouldn't work either, but indeed it's not!

**Comment by CanisLupus** [comment]
Conclusion: clicking an engine icon was causing focus to move from the input field to the icon, so when the code tried to copy the selected text it did nothing because there was nothing selected in the icon.

It's now fixed in version 3.10.0. :) Cheers!

**Comment by cazssiew** [comment]
Aha! Awesome, thanks!
