### ISSUE TITLE
No popup in nested frames

### ISSUE THREAD

**Issue by cazssiew** [CanisLupus/swift-selection-search#56]
In case this is actually specific to this website rather than nested frames in general, this bug occurs in the ReadLang library reader. The popup won't show up, but the context menu works normally.

**Comment by CanisLupus** [comment]
Hey! Could you please give me a specific page to test this out? :)

For example, I went to http://readlang.com/de/library (I chose German as a random language) and then clicked the first link (at the time I'm writing this), which is http://readlang.com/library/59e5b2969bb523e82b57c96c/scroll/0. The frame below the video does not let me select anything (not even for the context menu. Also tried another page that was similar. Maybe you have a more concrete example.

Thanks! ;)

**Comment by cazssiew** [comment]
Sorry, I should have been more specific, you can try it on that same page by clicking on any word and opening the sidebar (hamburger button on the top right) to view the dictionary. Interestingly, it seems to exclusively affect nested dictionary pages, no matter the dictionary and no matter its use case (there are a number of different ways to access dictionaries, all have the same problem)

**Comment by hdd60311** [comment]
@CanisLupus 
I don't know whether related this issue or not but I also found some new certain sites addon doesn't work (both popup and autocopy).
1. https://www.komica.org/
2. https://kreen.org/3069/firefox-57-quantum-about-config
With this site addon just doesn't work in the comment area, in other area addon works normally.
![screenshot-2017-11-20 firefox 57](https://user-images.githubusercontent.com/5089290/32993031-4e2b016e-cd8d-11e7-8fd3-311b82ce3886.png)

**Comment by CanisLupus** [comment]
Nice, thank you both for the repros! I could see the problem in all of them, and I believe the 3 cases are the same and indeed related to nested frames. SSS is simply not registering with those frames because I only detect changes in tabs, and a frame is special. :) Will look into this. Haven't had much time this past week.

**Comment by T-Halen** [comment]
Not sure it's related, but the popup doesn't work for text in eBay descriptions either.

Example (almost any eBay page) https://www.ebay.com/itm/253247294240
Scroll down to the item description and select some text.  Selected text in other parts of the page work, just not in the Description.  Thanks.

**Comment by CanisLupus** [comment]
Interesting. Yes, that is also the same issue. Unfortunately, this is proving very hard to fix and took me the better part of the afternoon with no fix in sight.

It should be possible to get all the frames in a page and register with selection events in all of them. However, if the frames come from different domains there are security restrictions. For example, in https://kreen.org/3069/firefox-57-quantum-about-config the comments frame is from disqus.com.

So the other option I can see is to set browser.tabs.executeScript to run on every page frame. (It's okay if nobody knows what I'm talking about, it stays here for reference. :)). However, this is definitely not working as it should. I don't know if it is Firefox's fault, or if I'm supposed to do something else (it's very hard to find references about these things, honestly), but the first executed script usually only finds the main frame, causing everything else to fail.

I was able to get it working by only executing scripts after the page FULLY completes loading, which is pretty bad, since it forces everything to load before you can select text and see the popup at all. So that is no acceptable solution.

**Comment by dionymnia** [comment]
I don't know if it's for the same reason as these other examples, but it seems that SSS doesn't pop up when I select text on Mozilla add-on pages?

**Comment by CanisLupus** [comment]
Hi dionymnia, welcome and thanks for mentioning it. :) The Firefox add-ons website is actually a very special case, where I can't do anything. ;) From what I understand, Firefox simply blocks all add-ons from modifying those pages (the popup is a page modification), most likely to avoid add-ons trying to install other add-ons automatically or hiding competitors from view (bad!).

In the meantime, I've asked this on StackOverflow to see if anyone can help solve the nested frames issue, which I believe is the most important SSS issue currently:
https://stackoverflow.com/questions/47593407/how-to-executescript-on-all-frames-of-a-page-as-they-load-i-e-not-using-docume

**Comment by hdd60311** [comment]
@CanisLupus 
I found a addon [Selection Context Search](https://addons.mozilla.org/en-US/firefox/addon/selection-context-search/) and seems that its popup window can work normally in these nested frames websites, maybe is a reference?

**Comment by CanisLupus** [comment]
Hey everyone, my SO question has been answered so I have a possible way of solving this issue now, which is great news!

@hdd60311 Indeed, it works on all frames. Maybe Selection Context Search uses the approach suggested in the SO answer, but unfortunately I think that add-on is not open source, so I can't tell. :)

I'll still check if everything is working well before updating SSS. I'll also group the fix with a few other small things (should be soon, since those are done already).

Cheers!

**Comment by cazssiew** [comment]
Great news ! Thanks so much for your dedication !

**Comment by CanisLupus** [comment]
Thanks @cazssiew! :D

I just submitted version 3.12.0 which, among other things, finally fixes the frames issue, so SSS should now work on the reported websites (on my end it does).

The fix came with an unfortunate extra permission that you have to give SSS, which Firefox calls "webNavigation". I couldn't avoid this, unfortunately, but it's just used for this purpose. This reminded me of the "downloads" permission that I had to add a few updates back just so I could "download" the SSS settings backup file from the user's machine when he/she wishes to restore it... Soon SSS will need permissions for everything but just use each of them for some single very specific thing. *sigh* ;)

If you find that something isn't working right please tell me! ;)

Cheers!
Daniel
