### ISSUE TITLE
Add ability to drag and drop rows in the search engines table

### ISSUE THREAD

**Issue by Gitoffthelawn** [CanisLupus/swift-selection-search#58]
I saw this in the release notes of another extension, [Selection Context Search](https://addons.mozilla.org/firefox/addon/selection-context-search/):

***Open the Add-on Options page in a new tab. This will allow to drag-and-drop rows in the table.***

I wonder if this idea will help you.

**Comment by CanisLupus** [comment]
Hey, long time no write. ;) I actually found that out while testing alternatives when Firefox 56 introduced the problem, and the main bug report for that issue also mentions that it works if you set the settings page to open in a new tab. However, I prefer the embedded options page and didn't format the page to be rendered in a separate page either. :p The option to open in a new tab is set on the manifest so it's either on a new tab or embedded, every time.

What worries me the most is that I think nobody is assigned to this bug precisely because it is low priority since it works on a new tab! I honestly don't know if I should change it and risk confusing users or live with the annoying up/down buttons in the meantime.

**Comment by Gitoffthelawn** [comment]
It has been a while!  :)

Ya, it's kind of a weird situation with that bug.  Personally, I vote for opening up the settings in a new tab so that drag-n-drop works.  But if it's a lot of work, then it's no big deal.

**Comment by CanisLupus** [comment]
I tried something and I can at least open the settings page in a separate tab _from_ the normal "embedded" settings page and have dragging work there. It's not clear if this is any better that simply changing the settings page to always open in a new tab, but at least it wouldn't feel strange to current users. :)

I still have to solve the issue of the UI in the embedded settings page not updating when a user returns to it from the separate settings tab. ;)

**Comment by CanisLupus** [comment]
OK, solved that last problem and submitted it in v3.11.1. :) In the note where I mention the ↑/↓ buttons, I added a link that opens the settings page in a new tab and enables the dragging icons. It's still not ideal, but at least now it's possible to reorder engines by opening that tab, and it won't confuse current users that expect the settings to be in the embedded page.

I think I'll leave this open, probably until Firefox gets the fix. :)

**Comment by CanisLupus** [comment]
Just now noticed that this issue still exists.

I recently (v3.20.0) simply gave up waiting for a fix and decided that the options page now always opens in a different page, meaning that dragging always works. The ↑/↓ buttons were even removed from the code entirely. Problem solved, I guess... ;)

**Comment by Gitoffthelawn** [comment]
WFM! :)
