### ISSUE TITLE
Allow user to create an icon to copy the selected text to the clipboard

### ISSUE THREAD

**Issue by Gitoffthelawn** [CanisLupus/swift-selection-search#6]
It would be nice to have an option to allow the user to create an icon that, when clicked, copies the selected text to the clipboard.

I noticed that you were considering an option that _always_ copies the text to clipboard.  I think that will result in accidental overwrites too often, and possible privacy and security issues.

Allowing the user to create an icon for this functionality would meet the need while not introducing any potential issues.

**Comment by CanisLupus** [comment]
I agree! While the copy option only has "Off" and "Always" for now, it is presented as a dropdown, meaning that if I get to implement your suggestion (which I find useful) the option to add a copy button to the popup will go under that dropdown.

**Comment by Gitoffthelawn** [comment]
Thanks!  This will be a great feature! :+1:

**Comment by CanisLupus** [comment]
Finally! :p

I've updated SSS to version 2.13.3 and added an option for the "copy to clipboard" icon. I ended up creating a whole new option for the icon, instead of adding it under the dropdown I mentioned above, because I also added an icon for the "open as link" and it seemed better to have both icon options close to each other, as they relate to icons.

The "build" folder contains the new build if you want to try it out, but eventually Mozilla will review it too. :)

I'll close this issue, but feel free to comment or report any issue or further suggestion.

Cheers!
Daniel

**Comment by Gitoffthelawn** [comment]
Thanks!  Looking forward to trying it!

**Comment by T-Halen** [comment]
Nice addition, I may use it.  However, is there any way to move its position within the row of icons?  I enabled it, but it shows first ahead of all the other icons.  My preference would be to have it last.  I didn't see any way to affect its position, just checking to see if I've missed it somewhere.  Thanks again for the update, it's always getting better!

**Comment by CanisLupus** [comment]
Thank you! :) Currently there's no way, but I actually remembered that some people could prefer that. Well, adding an entry to the dropdown option to show the icon at the end is easy. However, if both icons (copy and open link) are set to "show at the end" one of them will necessarily be the second to last.

I'm not sure how important it would be to be able to order these two icons (between themselves). Currently the engines follow the order defined in the browser, which you can change, so only the order of the custom icons is relevant. I assume that it wouldn't matter too much (and most people will likely only activate the copy icon, if any), but it's worse if I add more custom icons.

Maybe a better solution would be to allow every icon to be custom-ordered, though that solution would take more time. Do you have any thoughts on this?

**Comment by T-Halen** [comment]
I probably would only use the CopyClipboard, but could also see the use for OpenLink.  I see the problem with being able to order the icons, and believe the only solution would be to completely customize the layout as a preference of some kind.  Otherwise, you'll always end up with someone wanting it differently.  (grin)

If it were me, I would probably keep my list of search engines in the top row of icons, and add a second row for the other things, like CopyClipboard and OpenLink.  This way you could keep the ordering of the search engines as a browser function, and only have to deal with the second row yourself.  But like I said, I'm sure everyone's personal preference would be something different.

Not sure it helps, but there ya go.  Thanks for listening.

**Comment by CanisLupus** [comment]
Thank you for your ideas. :) Even though I'm not yet sure about this, it gives me some more food for thought. I'm currently working on making SSS compatible with multiprocess Firefox, as that is pretty urgent. :)

**Comment by CanisLupus** [comment]
@T-Halen In version 2.24.0 I added the option to place the "copy" and "open link" icons at the end of the panel (extra option in their respective dropdowns). Copy always comes first when both use the same side.

I didn't have time to make the considerably more complex "re-orderable icons" version. It's still noted in my TO-DO list. :)

NOTE: Version 2.24.0 is not live yet but will be after review, eventually. You can also get swift-selection-search-2.24.0.xpi from the build folder in this repository if you want. :)

**Comment by Gitoffthelawn** [comment]
@CanisLupus Daniel, sorry for the long delay in praising you and your fine work!  I finally got a chance to play with the new version, and it's fantastic!  It's great to be able to copy to the clipboard from SSS!  Thank you! 😃

**Comment by CanisLupus** [comment]
Haha I'm glad that long delays end in praise of me and my "fine work". ;) Thank you! You're welcome.

**Comment by T-Halen** [comment]
I've enabled the 'copy' icon and have it at the end of my other icons, and it's working great.  Excellent feature!
