### ISSUE TITLE
Middle click on highlighted text to popup

### ISSUE THREAD

**Issue by ZIEXED** [CanisLupus/swift-selection-search#60]
Like #34 a previous extension that I was using before SSS had the option to popup when middle clicking on a highlighted text
this behavior is very comfortable once you start using it as it doesn't require using your keyboard and in the same time the engines list won't popup in unnecessary situations :)

in short

**Feature request**
- Opening behavior > Middle click on highlighted text to open
- +If Openning behavior is Middle click and "Allow popup on editable fields" is checked > auto popup on editable fields only

The exception for this behavior on editable fields becuase of firefox paste on middle click

**Comment by CanisLupus** [comment]
This is actually one of the oldest TODOs I have! :) Not here on GitHub, but one user suggested that (maybe in a review) a long time ago and I have it noted down. This issue will help me remember to see what I can do about it. Thanks! :)

**Comment by youk** [comment]
I second this is useful and will simplify the flow. In fact I came to GitHub to create a request like this.

Otherwise great add-on. Keep it up!

**Comment by CanisLupus** [comment]
Thank you, youk! :)

I came here to comment that I've been trying to implement this and I'm also finding it useful myself and regretting not doing it sooner heheh ;)

The reason it's not done yet are the editable fields. Before deciding what to do for users like ZIEXED that have activated the option to paste on middle click (didn't know that existed, by the way!), I have to deal with simply detecting middle clicks on text selected in an input field. The normal way to get the bounds of the selected text in JavaScript (to detect if the click is on the selection) does not work for input fields, which is also what causes issue #51.

I've asked a question on StackOverflow for this:
https://stackoverflow.com/questions/49017031/how-to-get-the-position-bounds-of-text-selected-in-an-input-field

The less-than-ideal solution would be to allow pressing anywhere in the input field itself.

After this I can add an option to stop it from happening on editable fields for users with "paste on middle click" active. I wasn't looking to make it auto-open on input fields if the user has the "Middle mouse click" option selected because it wouldn't really respect their setting, but it is always possible to use the Ctrl+Shift+Space shortcut to force it to open.

Cheers!
Daniel

**Comment by youk** [comment]
I see that you already released a version that allows to open popup on middle click. Works great for me, thank you.

Would it be possible to add an option to react on middle click outside the selected text? Anywhere on the page or near the selected text (not sure if the latter is possible)?

I find myself clicking outside the selected text as the cursor frequently ends up outside it when you select and immediately click.

**Comment by CanisLupus** [comment]
Hi youk,

You are welcome! :) I wanted to update this issue yesterday but ended up not having the time to do it.

Indeed, version 3.14.0 now has the "Middle mouse button" option. Regarding input fields, SSS allows you to click anywhere on the input field because I can't seem to find a way (if there is any) to detect if I'm clicking on selected text itself (no answers to my SO question yet).

I ended up making editable field middle-clicks work only if "Allow popup on editable fields" is on.  You should keep this option disabled if you have the option to paste on middle click active in Firefox. In any case, pressing Ctrl+Shift+Space will always work on editable fields. :)

Regarding your request: hard question hehehe. I see what you mean, though. Allowing it anywhere in the page is not recommended, because it effectively blocks the main middle mouse function, which is to scroll up and down continuously. However, adding a margin so you can click _near_ the selected text is something I can do. Maybe an option to choose a margin in pixels, and the option only appears when "Middle mouse button" is the chosen opening behaviour. How does that sound? NOTE: editable fields would not respect this setting due to the reasons above, but you can still click anywhere in the field.

Cheers!
Daniel

**Comment by youk** [comment]
Configurable margin for click area would be ideal. Thanks for your responsiveness.

Is this so that when you captured middle click event there is no way to propagate it further to other (potential) handlers? I have one add-on installed which is bound to middle click event. It seems to take over SSS and prevent it from reacting to middle click.

**Comment by CanisLupus** [comment]
Alright, I'll try working on that option next. :)

Yes, indeed. It is possible to let the event propagate (actually, you have to add specific instructions for the event NOT to propagate), but it was too awkward to let the middle click both open the popup AND start scrolling the page at the same time because you would have to press again to stop scrolling, so I don't let it propagate. :)

You are right, add-ons can mess with the behaviour of other add-ons (and the browser's) due to these events. The order of execution of the various add-ons is what determines which ones get it in these cases, but I believe Firefox manages that, for better or worse. :|

**Comment by CanisLupus** [comment]
Hey everyone, v3.15.0 adds a margin option for middle clicking slightly outside the text selection. Please report back if there's any issue with it. :) It should be available soon at the Mozilla add-ons page.

I'll close this issue eventually, but not for now. ;)

**Comment by CanisLupus** [comment]
Closing this issue today since no problems were reported. As usual, if you do find problems with the middle click feature feel free to comment here. :)
