### ISSUE TITLE
Icons roundness

### ISSUE THREAD

**Issue by ZIEXED** [CanisLupus/swift-selection-search#61]
Like "Popup roundness", "Icons roundness" will control the roundness of icons

**Comment by CanisLupus** [comment]
This is easy to implement (you meant "Icon roundness" the second time, right?). :) It will have zero effect on a few icons (those that are not square at all), though, but that's expected.

Thank you very much for all the suggestions! :D ♥

**Comment by ZIEXED** [comment]
Yep, corrected :$

**Comment by CanisLupus** [comment]
Hi ZIEXED! Just submitted SSS version 3.12.0 to Mozilla (after about 2 months of no updates! sorry about that) and added the icon roundness option, which was an easy addition. ;)

You will notice that the settings menu was also changed so that sections can be collapsed (SSS remembers their state). It was getting a bit too many options and showing them all at once felt a bit too much for me.

Cheers!
Daniel

**Comment by ZIEXED** [comment]
Thank you Daniel :D

_Icon roundness reset on mouse hover_

**Comment by CanisLupus** [comment]
Oh, wow, apparently I didn't try to hover the icons. Amazing... -.- Sorry!

I submitted version 3.13.0 now with a fix for this (and a new option to only show the popup if more than a certain number of characters are selected, which solves an annoyance in country-specific YouTube pages).

Also, I forgot to add that the colored highlight below the icon will be affected by the roundness setting, so it will curve as well. This is due to the way the highlight is implemented right now. :)
