### ISSUE TITLE
context menu

### ISSUE THREAD

**Issue by kariaricks** [CanisLupus/swift-selection-search#66]
Great replacement for DictionarySearch! - Thank you!!

I only have one suggestion:

It is unfortunately not possible to open the links directly from the context menu.

I have first to navigate to SwiftSelectionSearch
and then to the links below.

It would be great to have this option directly in the context menu (like DictionarySearch).

https://addons.mozilla.org/de/firefox/addon/dictionarysearch

Thanks!!

**Comment by CanisLupus** [comment]
Hey @kariaricks, you are welcome! Glad you like SSS. :)

Thanks for the suggestion but unfortunately I don't have good news about it. Mozilla states in [this link ](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus) that:

> If you have created more than one context menu item or more than one tools menu item, then the items will be placed in a submenu.

It automatically puts every option in a sub menu if there's more than one. I believe it can have nested sub menus, but not several options in the root of the context menu (I suppose this is to avoid cluttering by many extensions).

The extension you linked may do that because it is a pre-WebExtensions extension, which now doesn't work on Firefox 57+. Old extensions frequently did things that they cannot do now (SSS included, which could read the search engines from the browser automatically, and use custom keyboard shortcuts). :(

Sorry that I can't be of more help here!

Cheers!
Daniel
