### ISSUE TITLE
Go back to original tab after closing search tab

### ISSUE THREAD

**Issue by hambue** [CanisLupus/swift-selection-search#67]
I'm only using the context menu search of your addon with the setting "Open in new tab (next to current)"

When I use the context search which is included in Firefox, Firefox automatically goes back to the tab where I started my search. If I do the same with the context search provided by this addon, Firefox chooses the tab to the right of the search tab that I'm closing.

Is it possible to change this behaviour to the native Firefox way?

**Comment by CanisLupus** [comment]
Hello! Interesting... I never noticed that but you're right. I'll look into this (and several other things) when I can. I haven't been able to work on SSS since about a month ago, unfortunately!

Cheers!
Daniel

**Comment by CanisLupus** [comment]
Turns out this was easy to fix by telling Firefox which tab opened the new one. Then it automatically creates the desired behaviour.

Please check if SSS version 3.13.1 solves the issue for you (I just uploaded it so it may take a few minutes to be live) and, if there's nothing wrong, we can close this. :)

Cheers!

**Comment by hambue** [comment]
Yes. Thank you for looking into this and solving it.

**Comment by CanisLupus** [comment]
You're welcome, hambue! :)
