### ISSUE TITLE
3.13.0 is last working version for me

### ISSUE THREAD

**Issue by theorist-complex** [CanisLupus/swift-selection-search#71]
Not sure whats happening, but 3.13.0 is the last version that is fully working for me on Waterfox 64bit 56.0.3.

On both 3.13.1 and 3.13.2 the popup will "pop up" and all icons are present, also, the context menu is "there" with all search options, but neither one will actually work when clicking to search. Whether I click to search google, Wikipedia, IMDB, Discogs, etc, the extension never recognizes that I've actually clicked anything and thus never opens the corresponding search.

I have tried default reinstalls and importing my settings files, on both versions and nada.

3.13.0 works beautifully.

**Comment by CanisLupus** [comment]
Fortunately, I have my Firefox 52 install ready to test these things. Unfortunately I didn't catch this before. ;)

Thanks for the report. Just submitted version 3.13.4 with a fix for this. In the recent updates, to fix issue #67, I started using something that is not available pre-Firefox 57. I changed the code to not use that in those versions.

Just a heads up: this means that the (minor) issue it fixed won't be fixed in those versions, including yours. It's a relatively minor problem, though. :)

Can you please confirm if it solved the problem for you? Thanks!

Daniel

**Comment by theorist-complex** [comment]
Yep, working as expected now. A shame about the fixes not getting implemented pre v57, but thats no big deal at all - I can handle searches opening as last tab until Waterfox updates.

Thanks for the update!

**Comment by CanisLupus** [comment]
Oh, supposedly SSS will still respect last/next tab. The only issue is that when you open a non-background new tab with SSS and then close it, you should be returned to the previous tab. SSS was not doing that, but a small change fixed it. That's the change that older versions won't get, unfortunately, because they don't have the attribute I use.

You are welcome! :)
