### ISSUE TITLE
Open more than one search tab simultaneously

### ISSUE THREAD

**Issue by Songoku88** [CanisLupus/swift-selection-search#72]
Issue: Lets say I have a marked word like "sorp" so I can choose searching via Wikipedia or Google etc. But I want to have a button, that allows me to open Google AND Wikipedia simultaneously, so in this example two tabs would open. The first would search "sorp" in Google the second in Wikipedia. 

I want to search in Google AND Wikipedia AND Wiktionary.

Thank you.

**Comment by CanisLupus** [comment]
Hi Songoku88! Thanks for the suggestion! :)

As you may not be aware of it, there's an option to "Hide popup on search engine click" that is enabled by default. If you disable it, it will let you click other icons and search several websites without having to open the popup again. Have you tried this?

Essentially you want the possibility to create icons that search multiple sites at once, right? Do you feel like the above option doesn't solve the problem? It's okay if it doesn't, I just want to let you know about it. :) I realize it doesn't open multiple websites _at once_ but it's close and may be easier to use than configuring specific "multi-website" icons.

Daniel

**Comment by Songoku88** [comment]
Hi CanisLupus,
thank you for your help. 

The "Hide popup on search engine click" tick mark makes it easier. 
The next step would be to create icons that search multiple sites at once, like you have written. 

As I now use the middle mouse button to open background tabs, it works really great.
But of course I have to click 4 times instead of one time (one click-> open 3 tabs, and switch to the first openend tab window) 

Songoku

**Comment by Gitoffthelawn** [comment]
I'm curious where this leads.  The ultimate evolution would be for each button to run a macro, which, among other things, could load web pages.  I'm trying to think what other functionality would be useful.  Any ideas?

**Comment by CanisLupus** [comment]
OK, I see the reasoning behind this. :)

As for the macros, theoretically you could have "javascript" buttons that run user-defined code over the selection (or over something else), although that would probably be blocked by security policies in many websites. It's the same reason I haven't tried adding user-defined CSS to SSS: because sites may block it. :) But if there are more ideas regarding this, feel free to share!

**Comment by igorofc** [comment]
Hey all. I'm interested in working on this issue. Here are my ideas:

- Create a new **Add group** button between the existing "Add engine" and "Add separator" buttons on the 'Search engines' section;
- That button would behave the same as "Add engine" expect a new column of checkboxes would appear to let users pick the engines that would compose this new group;
- This column is hidden for other engines and only shows up when highlighting a group;
- The field reserved for the search url could show the names of the engines included in the group;
- Add a new setting to let the user choose what to do when clicking on a group icon.

Any suggestions?

**Comment by CanisLupus** [comment]
Hey Igor, thanks a lot for looking into this. Some things:

>     * That button would behave the same as "Add engine" expect a new column of checkboxes would appear to let users pick the engines that would compose this new group;
>     * This column is hidden for other engines and only shows up when highlighting a group;

Altering the existing engines table temporarily with those checkboxes is great to use existing code, but the user needs to understand very clearly how to select engines for the group, especially among the 2 columns of checkboxes that already exist and all the input fields in the table (Would we disable those while the group is being modified? How to exit that mode then?). I think new users are probably scared of the engines table already, to be honest. :p Do you think it would be clear enough?

To add something: what do you think about showing a popup screen with all engines in a simplified table with checkboxes (for example, icon and name, perhaps search URL), where the user can add what they want and then either finish creating the group or cancel? I have historically stayed away from popups in SSS but this could be clearer than the first option. But I'm not sure of what your full idea was. :)

>     * The field reserved for the search url could show the names of the engines included in the group;

This summary could work well, yes. :)

>     * Add a new setting to let the user choose what to do when clicking on a group icon.

I'm tending towards just using the click options for single engines, because otherwise we'd have to provide new options for "group left click", "group right click", "group middle click", etc, and I'd really like to avoid that. :p
 
Now some more things of note:

- It should be possible to add the same engine to multiple groups (I don't think anything you said goes against this, but I'm just noting it here).

- The groups would show up as icons on the popup / context menu, so they need an icon URL (perhaps with something to make them distinct but that's a detail).

- We'd likely need an easy way to modify the group (any of the above ideas with checkboxes work well with this).

- Care must be taken if an engine is deleted and is part of any groups.

- Does disabling an engine in the popup or context menu affect the groups that contain it in any way? The groups should probably still search using it, no?

- Just something a bit on the side: feature request #152 was similar to this one, but instead of requesting a search when clicking the group, it requested that the group acted as a "folder" of sorts, just to contain engines for reducing clutter. Not to say that it should be implemented as well, but if there's a way to make the changes for #72 not block us from adding "folders" later, it would be great. Maybe groups can be configured later as a "group" (click to search all) or a "folder" (click to...uh....expand?). We'd have more things to discuss about this, though.

Cheers!
Daniel

**Comment by igorofc** [comment]
@CanisLupus, thanks for sharing your thoughts on this issue.

What I had in mind was adding that new column **G.** (Group) to the right of the **C.** column. It would show only when the user clicked any of the text fields belonging to a group. The other columns would stay visible. Modifying a group would be as simple as checking or unchecking the engines. The first time the user creates a group we could make it clear that the G. column was created by showing up a popup pointing to it with some basic instructions. 

Now, I had also considered the idea of opening a popup to let the user choose the engines and it's a valid one too. The reason I stuck with the first option was to avoid having to create the popup as well as having to to add an **Edit** button to modify the group. In my view that button would be sitting alone on the expandable area of the group (unless something else could be there too?) and clicking on it would show popup again.

In my opinion both options would behave well and I'm okay going either way. You have the final say on this :)

As for the click options I agree we could use the existing options. In this case we need to think how to tell the user that "Open in this tab" will apply to the first engine of a group while the others would open in background tabs. Also "Open in new window" means opening a new window for each engine a group.

```
It should be possible to add the same engine to multiple groups...
```
Agreed. :)

``` 
The groups would show up as icons on the popup / context menu...
```
We could design a basic default icon for a group.

```
Care must be taken if an engine is deleted and is part of any groups.
```
I think deleting an engine must also remove it from whatever group it may be in. In this case we let the user know by asking for confirmation.

```
Does disabling an engine in the popup or context menu affect the groups that contain it in any way? The groups should probably still search using it, no?
```
Yes. If the user also wants to disable it in the group just edit it any time.

Regarding issue #152, it's really interesting. I'd be glad to implement it after this one. Maybe we don't have to make a group configurable as folder. I mean, by default, hovering a group would show the drop down menu (after a timeout?). The user can either click on the group icon (search with all the engines) or click a specific icon in the menu to make a normal search.

**Comment by CanisLupus** [comment]
> What I had in mind was adding that new column **G.** (Group) to the right of the **C.** column. It would show only when the user clicked any of the text fields belonging to a group. The other columns would stay visible. Modifying a group would be as simple as checking or unchecking the engines. The first time the user creates a group we could make it clear that the G. column was created by showing up a popup pointing to it with some basic instructions.
>
> Now, I had also considered the idea of opening a popup to let the user choose the engines and it's a valid one too. The reason I stuck with the first option was to avoid having to create the popup as well as having to to add an **Edit** button to modify the group. In my view that button would be sitting alone on the expandable area of the group (unless something else could be there too?) and clicking on it would show popup again.
> 
> In my opinion both options would behave well and I'm okay going either way. You have the final say on this :)

Well, I can't say for sure. I have a feeling that 3 columns of checkboxes could be confusing, but I have no proof whatsoever. :p Of course, we could disable the other checkboxes while the group one is active. The user may also misclick a checkbox or select an input field by accident in another engine and the group "editing mode" would presumably close (unless we had a "finish editing" / "save" button instead?).

In the alternative I think the Edit button would indeed be sitting there alone with that approach. Not a big issue, but not the best looking, no. ;)

All in all, I tend to prefer the popup from a mostly theoretical point of view. I'm completely okay if you feel option 1 is better and want to try doing that. We can check this again in the end.

Btw, a group should not be selectable to be added inside itself. Should other groups be possible? (i.e. hierarchies of groups) For this issue (72) it's probably of little use; for folders it would make more sense. Maybe a detail for later...?

> As for the click options I agree we could use the existing options. In this case we need to think how to tell the user that "Open in this tab" will apply to the first engine of a group while the others would open in background tabs. Also "Open in new window" means opening a new window for each engine a group.

That is a good point that I didn't remember! Yeah, opening in the same tab should probably do what you said. Opening in a new window should _probably_ open all the searches in the same (new) window, however. I think that would be more useful (i.e. grouping search results in a separate window) if we can achieve that.

There's also the thought of what happens for the very rare engines that have "Discard on open (Advanced)" enabled. I think that setting should be respected for the particular engine, regardless of the click behaviour, since those engines are very specific in what they do, like opening an external app. (Though I suspect that these kinds of engines wouldn't normally be added to any groups, there's probably someone somewhere that will want to do this. ;)).

> We could design a basic default icon for a group.

Sounds good. And it's overridden by the icon URL if present. Something like a "folder" icon? 

> I think deleting an engine must also remove it from whatever group it may be in. In this case we let the user know by asking for confirmation.

Great!

> Yes. If the user also wants to disable it in the group just edit it any time.

Those were my thoughts as well.

> Regarding issue #152, it's really interesting. I'd be glad to implement it after this one. Maybe we don't have to make a group configurable as folder. I mean, by default, hovering a group would show the drop down menu (after a timeout?). The user can either click on the group icon (search with all the engines) or click a specific icon in the menu to make a normal search.

That seems good! Maybe we'll talk about this again if it comes to that. Don't worry too much about that issue for now. It's already great that you want to handle THIS issue. Thanks! :)

(I still haven't had a lot of time to complete the commits for your previous PR, but it's coming at some point!)

**Comment by igorofc** [comment]
```
 I tend to prefer the popup from a mostly theoretical point of view...
```
Cool!. I'll try the popup then.

```
Opening in a new window should probably open all the searches in the same (new) window, however.
```
Yes. That makes more sense than opening multiple windows.

```
Btw, a group should not be selectable to be added inside itself. Should other groups be possible?
```
I'd say yes. I think a group could be nested inside another one. This allows the user to define different levels of specific engines. Great idea! We're gonna discuss this later in #152.

```
Something like a "folder" icon?
```
That's nice. It would be great if it was possible to let the user choose an RGB color for the folder.

So I'll start working on this now. I'll let you know if I need any help.

**Comment by igorofc** [comment]
Hey @CanisLupus, could you provide an SVG of SSS's icon?

**Comment by CanisLupus** [comment]
Awesome! :)

Here's the SSS icon (had to zip it for GitHub): [sss-icon.zip](https://github.com/CanisLupus/swift-selection-search/files/5213877/sss-icon.zip)

**Comment by igorofc** [comment]
Thanks!

**Comment by igorofc** [comment]
Hi @CanisLupus, some updates:

I designed a folder icon out of SSS's logo but I was having trouble getting it to work well, especially with the changing of color part. So I opted for a simple circle icon. Clicking on the icon (inside the popup) shows up the color picker. When creating a new group a random color is applied to the icon.

The popup is looking like this:

![Screenshot_2020-09-27_15-02-45](https://user-images.githubusercontent.com/8989075/94372267-8c2fb100-00d2-11eb-847b-d81f48b7a119.png)


Managed to get the behaviours back for the engines managed by the browser (and for groups). I will try to make it work for custom engines too.

I replaced the `clickType` property of the `EngineClickMessage` class for the `openingBehaviour` property. This was required to make groups work when clicking from the context menu. I can elaborate this later if needed.

It's almost ready!

**Comment by igorofc** [comment]
Hi @CanisLupus, some updates:

I designed a folder icon out of SSS's logo but I was having trouble getting it to work well, especially with the changing of color part. So I opted for a simple circle icon. Clicking on the icon (inside the popup) shows up the color picker. When creating a new group a random color is applied to the icon.

The popup is looking like this:

![Screenshot_2020-09-27_15-02-45](https://user-images.githubusercontent.com/8989075/94372267-8c2fb100-00d2-11eb-847b-d81f48b7a119.png)


Managed to get the behaviours back for the engines managed by the browser (and for groups). I will try to make it work for custom engines too.

I replaced the `clickType` property of the `EngineClickMessage` class for the `openingBehaviour` property. This was required to make groups work when clicking from the context menu. I can elaborate this later if needed.

It's almost ready!

**Comment by CanisLupus** [comment]
That is one good-looking popup for creating groups! ;)

> I designed a folder icon out of SSS's logo but I was having trouble getting it to work well, especially with the changing of color part. So I opted for a simple circle icon. Clicking on the icon (inside the popup) shows up the color picker. When creating a new group a random color is applied to the icon.

That's perfectly fine. I've also wondered before about what would make a good "default" icon, for example for invalid icon URLs. The first thing that came to mind was the first letter of the engine on a colored background. Just colors seem good as well! We can discuss more later.

Out of curiosity, if the user doesn't specify an icon URL for the group (and so the colored circle is used), is this colored circle converted into a "data" image for the page script or does the page script simply recreate the circle+color for drawing (like happens in the options page)?

> I don't know if SSS's engines should be in the list, though. What do you think?

I agree that they probably shouldn't. Neither copy nor open as link seem to be good candidates for grouping with engines.

> Managed to get the behaviours back for the engines managed by the browser (and for groups).

Cool!

> I replaced the `clickType` property of the `EngineClickMessage` class for the `openingBehaviour` property. This was required to make groups work when clicking from the context menu. I can elaborate this later if needed.

No problem, I believe it will become clear from your code later. :) Besides, I was using "ctrlClick" for more than just "mouse clicks" so the names were not the best by this point.

> It's almost ready!

Awesome! 🎉 :)

**Comment by igorofc** [comment]
> Out of curiosity, if the user doesn't specify an icon URL for the group (and so the colored circle is used), is this colored circle converted into a "data" image for the page script or does the page script simply recreate the circle+color for drawing (like happens in the options page)?

I've used the `canvas` tag to draw the circle. When saving the group the icon is converted to a "data" image.

**Comment by CanisLupus** [comment]
Thanks to @igorofc's implementation and some further adjustments we now have "group engines" in SSS version 3.47.0. ;) It allows adding any of your custom engines to a group to search using all of those engines simultaneously.

So, @Songoku88, if you still use SSS, sorry for the wait of almost 3 years, but it's done!

I'm closing this issue, but of course anyone should feel free to comment if there are any problems with this (or anything else, since there were quite a few changes internally).
