### ISSUE TITLE
Configurable keyboard shortcuts

### ISSUE THREAD

**Issue by hdd60311** [CanisLupus/swift-selection-search#75]
Just a notice that this has been improved in 60 nightly.
https://bugzilla.mozilla.org/show_bug.cgi?id=1421811

**Comment by CanisLupus** [comment]
Thank you for the info, hdd60311! That's good news. :)

**Comment by CanisLupus** [comment]
Just submitted SSS v3.22.0 with support for custom shortcuts on Firefox 60 or later. :)

It has its limitations since most shortcuts are already used by Firefox and silently fail, and I haven't included an error detection mechanism to check if the shortcut is plainly wrong, mostly because communication between the background script and the settings page is not always easy. I'll look into these at a later time.

Cheers!

**Comment by grahamperrin** [comment]
#233
