### ISSUE TITLE
Can't open search result in new tab with SSS in Firefox 59.0.2

### ISSUE THREAD

**Issue by CorpusBava** [CanisLupus/swift-selection-search#78]
I even tried a fresh install of Firefox Quantum with no other extensions added and Swift Selection Search will not open a new search result when you highlight text in a tab other than the one you did the search from.  Tried every one of the related options within SSS and no dice.  This is an otherwise excellent add-on that I find invaluable but it's annoying to have it never open search results in other tabs or windows.

**Comment by CorpusBava** [comment]
Hi Daniel,

Yes, it was me who also recently posted on the Mozilla addon review site about this same issue.  Well, it looks like it was my own fault in not understanding exactly how the Open in New Tab option works.  As it turns out it IS working just fine - as long as I select the SSS "Search For" option itself nestled in the context menu.   Using the SSS search engine popups that appear when you initially highlight the text you want to run a search on don't open in new tabs, however, only in the current tab.  This is the main feature of your addon that I find most valuable , that quick, instant ability to highlight text on a page  and have SSS search engines you configured pop up.  So I'd like to change this post to an Enhancement request.

**Comment by CanisLupus** [comment]
Hi! Hehe it sure looked like it was you. :)

OK, but are you changing the "Left mouse button behaviour" / "Middle mouse button behaviour" options? I couldn't understand that from your reply. :) These two options are for the icons that appear in the _popup_ (these options are under the section "Popup Behaviour"), which is what you want.

I ask because there's another option in the "Context menu" section that instead controls the behaviour for the _context menu_ (what you called "Search For"), and I'm guessing that you are using that one but you should try the other two. :)

If you are using those already then there's something else.

**Comment by CorpusBava** [comment]
Ahhh!  I'm such a fool!  Yes, I've been changing the Open New Tab behavior in the Context Menu options, and ot in the Popup Behavior menu!  Followed your instructions and now it works perfectly.  Looks like you earned that extra star on addons.mozilla.org :)  Another nice benefit of your excellent extension is that it eliminates the need for another context menu addon I've been using called Context Search Web-ext.  No point in using redundant addons.  I only had one search engine that wouldn't work properly with SSS's Popup feature - for YTS, and I shouldn't even be in a place like that.  Haha ;)

Thanks for your patience, Daniel.

**Comment by CanisLupus** [comment]
A-ha! Thanks for the updated review. :)

I believe this is important, actually, since you are not the first to mistakenly change that option instead of the popup ones. I'm guessing that I'm not making that obvious enough and that SSS needs some tweaks to avoid confusion, if possible. Feedback is important! :)

I'm curious about what is going on with YTS, though (even if you shouldn't be there ;)). Does an URL like this work for you?
https://yts.io/?s={searchTerms}

No problem! Glad I could help. ;)

**Comment by CorpusBava** [comment]
YTS seems to have several different domains, some of them probably quite shady, but only one seems useful because it returns reliable hits.  This is the one I tried to get working with SSS but couldn't: https://yts.am/browse-movies  Oddly enough, ContextSearch web-ext works fine with it but I much prefer your Context Menu Search extension to that one so I'm perfectly willing to give up YTS for the extras I get with SSS ;)

**Comment by CanisLupus** [comment]
I see. :) That domain is actually blocked on my end (by the ISP), as are a few others, so I can't check it, unfortunately.

Thanks! I'll close this issue now and try to make the options less prone to mistakes in the future. :)
