### ISSUE TITLE
"Open selection as link" in context menu?

### ISSUE THREAD

**Issue by neekt** [CanisLupus/swift-selection-search#84]
Would it be possible to add the "Open selection as link" option to the context menu? It currently shows with the popup, but not in the context menu. Same with the "Copy selection to clipboard" option.

Using Firefox 59.0.2 on macOS High Sierra 10.13.4

Thanks for such a great extension!

**Comment by CanisLupus** [comment]
Hello neekt!

To be honest, these options weren't included in the context menu because Firefox should already have both of them in there. :)

What I mean is that, when right-clicking on a page, Firefox already shows "Copy" if you have text selected and "Open link" if the selected text is found to be a link:
![firefox context menu](https://user-images.githubusercontent.com/532708/39087235-0e9f81b0-4596-11e8-89a1-da3897c93178.png)

These were both one click away so I thought that adding them to SSS's context menu was redundant. But I'm ready to reconsider. ;) Please tell me what you think and why would you add them.

Thanks for using SSS! :)

Cheers!
Daniel

**Comment by CanisLupus** [comment]
Ah, I see. I hadn't had that problem before but I see what you mean now. :)

I'll think about it. It isn't hard to add, but then some people might want to disable those icons in the context menu and by then I'll need to do issue #15 (being able to select which individual engines are active in the context menu, like you can do for the popup), and this may risk confusing users with too many checkboxes if not done right hehe. ;) I'll have to think about how to approach this. If #15 was already done I would have no problem doing this one now.

Thanks for the suggestion! :)

**Comment by CanisLupus** [comment]
So... #15 is now done, which means I had no excuse to not do this. :)

In version 3.26.1, which should soon be on the add-on market, you should find that you can use copy and open as link in the context menu. Separators as well. Just be sure to enable them for the context menu using the checkboxes in the table of search engines.

If you find any issues, feel free to comment here!

Cheers
Daniel

**Comment by neekt** [comment]
Thanks so much for adding this! Much appreciated :)

**Comment by CanisLupus** [comment]
You are welcome! :)
