### ISSUE TITLE
Ability to close tab are opening it / not open a tab?

### ISSUE THREAD

**Issue by mmf-Github** [CanisLupus/swift-selection-search#86]
Dear all,

I am using this awesome extension for opening Everything (voidtools.com) with es:{searchTerms}.

Works like a charme, but I'd like the tab to close afterwards or not to open a tab.

Here is how it works at the moment:
1) I mark a search term
2) I click on the Everything icon
3) SSS opens a tab with es:<SEARCHTERM>

Is there a possibility to include a step 4) Close tab or modify step 3 to 3) SSS opens Everything direct?

Thanks,

MMF

**Comment by CanisLupus** [comment]
Hey! That's interesting, I use Everything (it's fantastic, especially with a hotkey to toggle it open/closed) and never known it could open a protocol like that (if I understood correctly). How is the support for "es:" activated? I couldn't find info on it.

Indeed SSS always tries to create a new tab since I didn't consider that kind of usage. :) What about opening in the current page instead of a new tab (by default by clicking with the left mouse button)?

Implementing this would need either individually configurable properties for each engine, or (if at all possible), a way to detect protocols other than the most common ones, though this could lead to undesired errors too. :)

**Comment by mmf-Github** [comment]
Hi there,

it is a built-in feature! You can find it via Options --> General --> URL Protocol. And yes, opening in the current page does the trick. If you could include the default per search engine, that would be awesome :)
I also think that the protocol decision is too error-prone.

Thanks,

MMF

**Comment by CanisLupus** [comment]
Thanks, I wasn't finding it and that helped!

If I ever get around to adding engine-specific configurations I'll consider adding this as well. At least there's left click for now. ;)

**Comment by CanisLupus** [comment]
Hey @mmf-Github, sorry this took so long, but SSS version 3.43.0 (now 3.43.2) adds support for this. It's a per-engine option named "Discard on open" (you must select the engine in the list and this will be one of the sub-options). It should discard the search tab but still open in Everything.

If you still use SSS after all this time, please let me know if you see any problems! :)

Cheers!
Daniel

**Comment by mmf-Github** [comment]
Thanks Daniel, this is awesome. And yes, still a very happy user :)

**Comment by CanisLupus** [comment]
Ah great! ;) Cheers!

**Comment by mikelei8291** [comment]
It's possible to invoke the URI without opening and then closing a tab: https://stackoverflow.com/a/19452047
I think this removes the visual disturbance of a blank tab flashing.

**Comment by CanisLupus** [comment]
Hi Mike, thanks for the suggestion. I suppose you read my comment in the code...?

**Comment by CanisLupus** [comment]
Hi Mike, thanks for the suggestion. From your reply, I suppose you read my comment in the code...? :)

![image](https://user-images.githubusercontent.com/532708/89729461-d4651800-da2d-11ea-96f9-efc07005b691.png)

I open new tabs in the background script because I need to use the WebExtensions APIs to have control over how new tabs open, so I don't think I can use that kind of code there, since the code accesses the window object. I may be wrong, but that would probably have to be done in the page script itself. Something to look at.

Cheers!
