### ISSUE TITLE
Popup on YouTube video

### ISSUE THREAD

**Issue by PiotBar** [CanisLupus/swift-selection-search#87]
Please, do not show popup when I accidentally swipe on Youtube video.
Check an example. I just click (accidentally swipe) on YouTube video to pause/play
[Click to see](http://lektorski.pl/pobierz/firefox-addon-swift-selection-search-youtube.png)
Note that the "PL" next to YouTube logo is marked.

**Comment by CanisLupus** [comment]
Hey PiotBar! I'm annoyed by this as well, though in my case it's "PT". :) The problem is that the YouTube page layout allows that to happen when dragging the video, so about the selection itself I can't do much.

However, I previously added an option to counter this, which is "Minimum selected characters" under "Popup Behaviour". If you set it to 3, this should no longer happen (though it will block the popup for all selections with less than 3 characters). Another option is to change the popup "Opening behaviour" to something more restrictive, like "Hold Alt" or "Middle mouse button", so that you only trigger the popup when really needed.

See if any of the two options work for you. :)

Cheers,
Daniel
