### ISSUE TITLE
No popup at DuckDuckGo.Com

### ISSUE THREAD

**Issue by rmlrml** [CanisLupus/swift-selection-search#91]
The popup does not appear when selecting text in the search box on DuckDuckGo.Com.  This is whether the search box header is set to Fixed, Scrolling, or Dynamic in duckduckgo.com/settings, or whether SSS "Popup location" is set to "At cursor location" or "Bottom right corner of selection rectangle".  The popup _does_ appear when selecting results text.

**Comment by CanisLupus** [comment]
Hey there! :) Have you tried activating the checkbox for "Allow popup on editable fields"? It's under the section "Popup/icons behaviour" in the options page. Maybe you haven't noticed it. :) It is disabled by default since it can be annoying in some cases, though there are alternatives that can be used to open the popup only when needed.

Cheers!
Daniel

**Comment by rmlrml** [comment]
Ack!  That did it.  Thank you!
