### ISSUE TITLE
[SOLVED] Issue when an imported search engine has the same name as one of SSS' built-in engines

### ISSUE THREAD

**Issue by mazesy** [CanisLupus/swift-selection-search#96]
Hi,

I deleted all SSS's built-in search engines;
I imported my search engines (search.json.mozlz4);
One of the imported search engines had the same name as one of SSS's built-in engines: _YouTube_.
Testing from SSS's Option page showed no issue, but testing from several Web pages showed that _YouTube_ had vanished from SSS's popup display: **only in the popup** not in the context menu.

I rename _YouTube_ to _YouTube+_ and the issue disappears. I rename _YouTube+_ to _YouTube_ and the issue reappears.

I'm presuming the culprit is all in same engines names because only _YouTube_ is concerned in my scheme and _YouTube_ is the only search engines among those I imported to have exactly the same as one of SSS.

Thanks.

**Comment by CanisLupus** [comment]
Hey there! Interesting. Thanks for the detailed report! I'll try looking into this soon and let you know. Don't like it when bugs come up... :)

Cheers!
Daniel

**Comment by CanisLupus** [comment]
OK, I tried reproducing this but unfortunately couldn't.

I reinstalled SSS, opened the popup in a random page just to check, then went to the options page, deleted all default engines, imported my search.json.mozlz4 file (which has two engines with the same name as the default SSS ones: Google and YouTube) and tried opening the popup again on a page. All icons were there, for better or worse. :)

I'm not sure what is going on here! :| If you don't have personally identifiable information in your search.json.mozlz4 file and don't mind sending it to daniel.rb.lobo+sss@gmail.com, I would find it useful to take a look. It would also be useful if I could see your settings, if you could export them in the "Storage & Backup" section. Sorry for the trouble! It's okay if you don't want to, I understand.

There's a usual issue of the YouTube icon not appearing for some people which made me add this to the Troubleshooting portion of the Options page (doesn't look to be this problem, though, since changing the name works!):

> If an icon does not appear and its URL is correct, please check if that still happens if you disable your ad blocker and add the icon URL again. Some blocking lists in your ad blocker can stop certain images from downloading! (ex.: YouTube may be blocked by "Fanboy's Annoyance List").

**Comment by mazesy** [comment]
OK, @CanisLupus I'm sending you both, zipped, after commenting.

Because of this (pseudo) issue I had set my SSS _YouTube_ to be named _Youtube_ and no issues.
Setting again _YouTube_ to _Youtube_ (capital letter makes the difference!)
Then I just visited for checking 2 other sites : issue with _YouTube_, not with _Youtube_ ...
But here, on this very page (reloaded) as well as on other GitHub pages : no issue with _Youtube_ ...

It's not that the YouTube icon only doesn't appear (with an empty box), it's that the whole YouTube box vanishes : as if the engine item itself was omitted by SSS.

I hate bothering! I do hope the two files will bring you pertinent information.

Thanks again.

**Comment by CanisLupus** [comment]
Thanks a lot for submitting the files. :) The thing is...... it still doesn't happen here. x) I have tried both with and without the capital "T", both with and without first importing your settings, and it always shows for me on all sites I've tested. What is an example site where YT fails to show?

The fact that you mention it working on some websites but not on others seems to suggest that this is due to some specificity of the sites or of some installed addon, though I fail to see how the _name_ of the icon on the popup would have anything to do with it. :) Hmm...

Can you test this with any ad blockers disabled? If it still doesn't work, I would try ALL add-ons disabled. Sorry for all the requests! I find some of these issues rather puzzling heheh.

Daniel

**Comment by mazesy** [comment]
**Testing with _YouTube_:**
No issue on GitHub pages (tested several)

![1](https://user-images.githubusercontent.com/31442711/40589737-2fd24a24-61f3-11e8-8b07-5a69e990edd7.jpg)

Issue on all other sites I've tested (several), i.e. https://www.calendrier-365.fr/

![2](https://user-images.githubusercontent.com/31442711/40589746-5930cbb6-61f3-11e8-936e-3a58a5cf8806.jpg)

The YouTube engine/icon disappeared, following ones shifted of course.

@CanisLupus I want to thank you for this extra work. I have no clue. Because this is not essential to SSS I propose to just drop the issue, which is simply one of those non-reproducible annoyances (the worst) and consequently a nightmare for anyone not being able to reproduce it. A non-issue I'd say therefore, related obviously to something specific to my configuration.

I'll carry on with whatever new scenarios I can think of. For instance & to start with, I'll remove YouTube from my search.json.mozlz4 file, reset SSS (as first install), remove all SSS engines except YouTube, call search.json.mozlz4 file and see what that leads to ...

Please forget the annoyance. You've searched thoroughly and could not reproduce my issue, mine therefor not yours, not that of SSS.

If I find a clue I'll let you know. All runs great on SSS, just a funny scenario I believed at first to be independent of my configurations. No problem.

Thanks again, really.

**Comment by mazesy** [comment]
SOLVED

The issue was not pertaining to SSS, the issue was not pertaining to a whatever common search engine name. **The culprit was all in a filters list I use with the _uBlock Origin_ Firefox extension**

1- SSS : Reseted Engines => includes YouTube engine **without** loading my search.json.mozlz4
2- Opened a random Web page : _YouTube_ engine **did not** appear
3- Hence, problem with _YouTube_, the name
4- Opened again a random page, disabled uBO's Cosmetic filtering on that site : _YouTube_ engine appeared
5- Hence, it's a problem with _YouTube_ appearing in a **_filters list_**

6- Found the filters list : [Fanboy Ultimate List](https://fanboy.co.nz/filters.html)
7- [Downloaded](https://fanboy.co.nz/r/fanboy-ultimate.txt) this list to check it out more easily.
8- Found the culprit filter : `##img[title="YouTube"]` which blocked SSS YouTube engine/icon.

9- Understood why all sites were affected but not GitHub : the list contains the following exception:
`fark.com,github.com,github.io,marketplace.firefox.com,vvhp.net,wikipedia.org#@#img[title="YouTube"]`
10- Added `#@#img[title="YouTube"]` to _uBlock Origin / My Filters_ in order to block the problematic filter everywhere.

11- Tested: issue is solved
12- Came here to report.

So that was it. It had strictly nothing to do with SSS. Really sorry for the disturbance, I never could have imagined such a scenario. You learn every day.
